window.TGI_IMPORTED_FLASHCARDS = [
  {
    "id": "tgi-monitoria:56a720c0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os nomes do pontos marcados?",
    "a": "amarelo- vestíbulo bucal inferior\n\nazul escuro- M. Genioglosso\n\nverde escuro-M. Geniohióide\n\nbranco inferior-  M. Milohióide\n\nazul claro- Torus Tubário\n\nlaranja- óstio faríngeo da tuba auditiva\n\nvermelho- Prega salpingo palatina\n\npreto- Prega salpingo faríngea\n\nbranco superior- Tonsila faríngea\n\nVerde claro- recesso faríngeo",
    "frontImage": "tgi-monitoria/abf83400-cc11-1166-b14b-b331f9db8fc4.jpg",
    "backImage": null,
    "order": 0
  },
  {
    "id": "tgi-monitoria:56a795f0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os pontos marcados?",
    "a": "branco- Arco palatoglosso\n\namarelo- Arco palatofaríngeo\n\nazul- Tonsila palatina\n\nverde- Valécula\n\nvermelho- Cartilagem Epiglote",
    "frontImage": "tgi-monitoria/9ba038b0-d59d-1166-b14b-b331f9db8fc4.jpg",
    "backImage": null,
    "order": 1
  },
  {
    "id": "tgi-monitoria:56a7bd00-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os pontos azuis e o  preto?",
    "a": "Azuis- Sulco terminal da língua\n\nPreto- forame cego (resquício do ducto tireoglosso)",
    "frontImage": "tgi-monitoria/f05d1f90-43b0-1167-b14b-b331f9db8fc4.png",
    "backImage": null,
    "order": 2
  },
  {
    "id": "tgi-monitoria:56a7e410-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "o que está apontado pela seta amarela?",
    "a": "pregas gástricas",
    "frontImage": "tgi-monitoria/b1d0a620-991e-1167-b14b-b331f9db8fc4.jpg",
    "backImage": null,
    "order": 3
  },
  {
    "id": "tgi-monitoria:56a7e411-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais as porções marcadas?",
    "a": "vermelho- ceco\n\nroxo- Tênia livre\n\ndedo - Apêndice vermiforme\n\nalfinete- mesoapêndice",
    "frontImage": "tgi-monitoria/82eca8b0-9a02-1167-b14b-b331f9db8fc4.jpg",
    "backImage": null,
    "order": 4
  },
  {
    "id": "tgi-monitoria:56a80b20-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "espaço da pinça e os limites",
    "a": "forame omental (forame de winslow)\n\nLIMITES:\nSUP: Lobo Caudado do Fígado\nINF:1ª porção do duodeno\nanterior: V. Porta (componente da tríade portal)\nposterior: veia cava inferior\n\nOBS- Tríade portal;\nV. Porta (posterior\nA. Hepática própria(medial)\nDucto Colédoco (lateral) (=Ducto Cístico+ Ducto hepatico comum)",
    "frontImage": "tgi-monitoria/4eae69c0-e27e-1167-b14b-b331f9db8fc4.jpg",
    "backImage": null,
    "order": 5
  },
  {
    "id": "tgi-monitoria:56a80b21-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os musculos extrínsecos da lingua e inervação?",
    "a": "4 Músculos\n\nM.Genioglosso\nM.hioglosso\nM.Estiloglosso\nNERVO HIPOGLOSSO\n\nM. Palatoglosso- N. Vago",
    "frontImage": null,
    "backImage": null,
    "order": 6
  },
  {
    "id": "tgi-monitoria:56a83230-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura sinalizada ?",
    "a": "flexura duodenojejunal\n\nOBS- é fixada pelo M. Suspensor do duodeno (conteúdo do Lig. Treitz)",
    "frontImage": "tgi-monitoria/42b2a420-82e2-1180-ae41-596f50697215.jpg",
    "backImage": null,
    "order": 7
  },
  {
    "id": "tgi-monitoria:56a83231-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura na pinça?",
    "a": "ducto cístico ( oriundo da vesícula biliar)\n\nUm dos componentes do trígono de calot:\nDucto cístico, ducto hepático comum e a borda inferior do fígado\n\nCONTEÚDO DO TRÍGONO:\nA. Cística",
    "frontImage": "tgi-monitoria/eeda45f0-84c5-11aa-b65c-eb0d0ce250c6.png",
    "backImage": "tgi-monitoria/61aca9e0-3ab2-12eb-8775-1f8f280d18df.jpg",
    "order": 8
  },
  {
    "id": "tgi-monitoria:56a85940-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "defina a formação do ducto colédoco e a sua função:",
    "a": "Junção do: Ducto cístico da vesícula biliar e Ducto Hepático comum do fígado\n\nFunção: levar a bile para o duodeno",
    "frontImage": null,
    "backImage": null,
    "order": 9
  },
  {
    "id": "tgi-monitoria:56a85941-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome das estruturas marcadas?",
    "a": "Laranja- A. Mesenterica Inferior( ultimo ramo anterior da Aorta abdominal)\n\nRoxo- A. Cólica esquerda\n\nVermelho- Aa. Sigmóideas\n\nVerde- A. Retal superior\n\nRosa- V. Mesentérica inferior",
    "frontImage": "tgi-monitoria/723c50d0-6257-147c-83b6-a1077eeb5434.jpg",
    "backImage": null,
    "order": 10
  },
  {
    "id": "tgi-monitoria:56a88050-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura? e qual a patologia associada?",
    "a": "Recesso subfrênico- Acumulo de ar no abdômen, Pneumoperitônio\n\nOBS- Recesso subfrênico direito é o ponto mais alto do abdômen",
    "frontImage": "tgi-monitoria/ff13ee70-891c-11aa-b65c-eb0d0ce250c6.jpg",
    "backImage": null,
    "order": 11
  },
  {
    "id": "tgi-monitoria:56a88051-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura circulada?",
    "a": "lig. triangular do fígado, fixa o fígado a porção posterior do abdomen e ao diafragma\n\nOBS- é a junção dos ligamentos coronários (anterior e posterior) na lateral do fígado",
    "frontImage": "tgi-monitoria/857a21d0-8a73-11aa-b65c-eb0d0ce250c6.jpg",
    "backImage": null,
    "order": 12
  },
  {
    "id": "tgi-monitoria:56a88052-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura? e qual a função associada?",
    "a": "Goteiras paracólicas\n\no escoamento de líquidos abdominais se dá por essas goteiras.\n\nA porção direita impede o escoamento até o reto por causa da raiz do mesentério\n\nA porção esquerda possui apenas o ligamento frenocólico para tentar barrar essa passagem",
    "frontImage": "tgi-monitoria/c4e64170-8b6b-11aa-b65c-eb0d0ce250c6.png",
    "backImage": null,
    "order": 13
  },
  {
    "id": "tgi-monitoria:56a8a760-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome das estruturas sinalizadas? sao  envolvidos por qual estrutura?",
    "a": "Azul Superior: Veia porta (formada pela V. Mesentérica sup e V. Esplênica) \nVerde: Ducto colédoco\nVermelha: A. Hepática propria\n\nSao envolvidas pelo ligamento Hepatoduodenal\n(Tríade portal)",
    "frontImage": "tgi-monitoria/8f98e8a0-8cbb-11aa-b65c-eb0d0ce250c6.jpg",
    "backImage": null,
    "order": 14
  },
  {
    "id": "tgi-monitoria:56a8a761-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "Qual a irrigação do estômago?",
    "a": "A. Gástrica Esquerda- curvatura menor (Direta do tronco celíaco)\n\nA. Gástrica direita- curvatura menor (Ramo da A. Hepática Própria)\n\nCurvatura maior:\nA. Gastromental esquerda \n(oriunda da A. Esplênica)\n\nA. Gastromental direita (Oriunda da A. Gastroduodenal- Ramo da A. Hepática Comum)\n\n+++ Aa. Gástricas curtas que irrigam o fundo gástrico (Ramo da A. Esplênica)\n\nOBS: as vezes a A. Esplênica da A. Gástrica posterior",
    "frontImage": null,
    "backImage": "tgi-monitoria/1c6d41d0-9316-11aa-b65c-eb0d0ce250c6.png",
    "order": 15
  },
  {
    "id": "tgi-monitoria:56a8a762-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os ramos da Aorta abdomnial?",
    "a": "4 Anteriores:\nA. frênicas inferiores\nTronco celíaco\nA. Mesenterica sup\nA. Mesenterica inf\n\n3 Laterais:\nA. renais\nA. suprarrenais Médias\nA.Gonadais( A. Testicular nos homens e A. Ovárica nas mulheres)\n\n2 Posteriores:\nAa. Lombares \nA. Sacral mediana",
    "frontImage": null,
    "backImage": null,
    "order": 16
  },
  {
    "id": "tgi-monitoria:56a991c0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "explique a circulação colateral caso a A. Mesenterica inf seja ligada",
    "a": "A. Mesenterica inf dá como ramo a A. colica esquerda e Aa. Sigmóideas que se anastomosam com a A. Cólica direita, a A. Cólica Média e a A. Ileocólica (ramos da A. Mesentérica sup) , formando o arco justacólico",
    "frontImage": null,
    "backImage": null,
    "order": 17
  },
  {
    "id": "tgi-monitoria:56a991c1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a irrigação do pâncreas?",
    "a": "A Esplênica da os ramos;\n•A. Pancreatica dorsal\n( para a colo)\n•A. Pancreatica Magna\n( para o corpo)\n•A. da Cauda do Pâncreas \n(para a cauda)\n\nA A. Gastroduodenal (oriunda da A. Hepatica Comum) dá os ramos:\n\n•A. Pancreaticaduodenal sup anterior e posterior\n\nA A. Mesenterica sup da os ramos:\n•A. pancreaticaduodenal inf anterior e posterior",
    "frontImage": null,
    "backImage": null,
    "order": 18
  },
  {
    "id": "tgi-monitoria:56a9b8d0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "por que uma dor no peritonio visceral próximo ao diafragma é relacionada como uma dor localizada ?",
    "a": "porque o peritonio visceral nessa porção nao é mais inervado por nervos autônomos e sim pelo nervo frênico que é somático\n\nOBS- N. Frênico (C3-C5)",
    "frontImage": null,
    "backImage": null,
    "order": 19
  },
  {
    "id": "tgi-monitoria:56a9b8d1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome das estruturas?",
    "a": "azul: A. Hepatica propria\nvermelho: Ducto colédoco\nverde: veia porta\n\nformam a tríade portal - Conteúdo do Lig. Hepatoduodenal",
    "frontImage": "tgi-monitoria/5e280850-4f95-11ae-9dbb-89fe7c481a24.jpg",
    "backImage": null,
    "order": 20
  },
  {
    "id": "tgi-monitoria:56a9dfe0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome das estruturas?",
    "a": "Roxo: Tonsilas linguais\n\nVermelho: Prega Glossoepiglótica mediana\n\nAzul: Valécula\n\nVerde: Pregas Glossoepigloticas Laterais\n\nPreto: Cartilagem epiglote",
    "frontImage": "tgi-monitoria/fe27a830-4f70-11ae-9dbb-89fe7c481a24.jpg",
    "backImage": null,
    "order": 21
  },
  {
    "id": "tgi-monitoria:56a9dfe1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a formação da veia porta?",
    "a": "•V. Mesenterica Sup \n•V. Esplênica (recebe a V. Mesentérica inf)\n\nOBS- se forma posterior à cabeça do pâncreas",
    "frontImage": null,
    "backImage": null,
    "order": 22
  },
  {
    "id": "tgi-monitoria:56a9dfe2-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura?",
    "a": "processo papilar do lobo caudado do fígado",
    "frontImage": "tgi-monitoria/a1a9ebf0-5539-11ac-8827-1f60a763c933.jpg",
    "backImage": null,
    "order": 23
  },
  {
    "id": "tgi-monitoria:56aa06f0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura?",
    "a": "processo caudado do lobo caudado do fígado",
    "frontImage": "tgi-monitoria/fbf0d070-5560-11ac-8827-1f60a763c933.jpg",
    "backImage": null,
    "order": 24
  },
  {
    "id": "tgi-monitoria:56aa06f1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os ramos da A. Mesenterica Sup?",
    "a": "São 6 ramos\n\nCONVEXIDADE-\n• para o intestino delgado:\nAa. ileais (íleo)\nAa.Jejunais(jejuno)\n\nCONCAVIDADE-\n•Para o Duodeno+ pâncreas\nA. Pancreáticaduodenal inf (se divide em anterior e posterior)\n• para o Intestino Grosso:\nA. Cólica Média (colo transverso proximal)\nA. Cólica direita (colo ascendente)\nA. ileocólica- Dá o ramo apendicular para o apêndice (Ceco e apêndice)",
    "frontImage": null,
    "backImage": "tgi-monitoria/b1beb510-e7f7-13d2-956a-41bdeb6f8f37.jpg",
    "order": 25
  },
  {
    "id": "tgi-monitoria:56aa06f2-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura? qual a irrigação desse local?",
    "a": "esôfago cervical\n\nAa. Tireóideas inferiores",
    "frontImage": "tgi-monitoria/4f341720-eccc-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "order": 26
  },
  {
    "id": "tgi-monitoria:56aa2e00-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura?",
    "a": "recesso piriforme. Está relacionado com a comida que se deposita nesse local quando há engasgo",
    "frontImage": "tgi-monitoria/e1c29ca0-eceb-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "order": 27
  },
  {
    "id": "tgi-monitoria:56aa2e01-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais as estruturas marcadas?",
    "a": "vermelho- 2º segmento do fígado\n\nazul escuro- 3º segmento do fígado\n\nverde escuro-4º A segmento do fígado\n\nverde claro-4º B segmento do fígado\n\nlaranja-5º segmento do fígado\n\nazul claro-6º segmento do fígado\n\nbranco- 7º segmento do fígado\n\nroxo- 8º segmento do fígado\n\nOBS- O primeiro segmento do fígado é posterior",
    "frontImage": "tgi-monitoria/5204c6b0-8de8-1395-ba4d-adf186572cef.jpg",
    "backImage": null,
    "order": 28
  },
  {
    "id": "tgi-monitoria:56aa2e02-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura?",
    "a": "A. Cística (Ramo da A. Hepática direita)\n\n•Conteúdo do Trígono de Calot",
    "frontImage": "tgi-monitoria/5cc31110-edf9-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "order": 29
  },
  {
    "id": "tgi-monitoria:56aa7c21-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a irrigação das Suprarrenais? e a drenagem venosa?",
    "a": "irrigado pelas Artérias Suprarrenais superiores (oriundas das Aa. Frênicas inferiores)\n\nsuprarrenais Médias (oriundas da lateral da Aorta abdominal)\n\nArtérias suprarrenais inferiores (oriundas das A. Renais) \n\n\nDRENAGEM VENOSA:\nV. Suprarrenal direita- Drena diretamente para a V. Cava inf\n\nV. Suprarrenal esq- drena junto com uma V. Frênica inf Esq (há duas) para a V. Renal Esq",
    "frontImage": null,
    "backImage": "tgi-monitoria/4b5bb1e0-f718-1345-9031-0556ba2a088d.jpg",
    "order": 30
  },
  {
    "id": "tgi-monitoria:56aa5510-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o nome da estrutura?",
    "a": "papila duodenal maior\n\n(Local que a Ampola hepatopancreática desemboca// 2ª porção do duodeno- Descendente)\n\nOBS- Papila duodenal menor não dá pra ver na maioria das peças do laboratório",
    "frontImage": "tgi-monitoria/94e5a630-f389-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "order": 31
  },
  {
    "id": "tgi-monitoria:56aa5511-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o conteúdo dessas estruturas?",
    "a": "Prega umbilical mediana- úraco  obliterado\n\nPrega umbilical medial- arteria umbilical obliterada\n\nPrega umbilical lateral- Vasos epigástricos inferiores",
    "frontImage": "tgi-monitoria/a6cbe8f0-14a1-11c0-9c62-ffcaf112b942.jpg",
    "backImage": null,
    "order": 32
  },
  {
    "id": "tgi-monitoria:56aa5512-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os ramos do tronco celíaco?",
    "a": "A. Hepática Comum\nA. Gástrica Esq\nA. Esplênica",
    "frontImage": null,
    "backImage": null,
    "order": 33
  },
  {
    "id": "tgi-monitoria:56aa7c20-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "limites e conteúdo do trígono de calot?",
    "a": "lateral- Ducto cístico\nmedial- ducto hepático comum\nsuperior- face inferior do fígado\n\nConteúdo: A. Cística",
    "frontImage": null,
    "backImage": "tgi-monitoria/46beb6e0-6f23-147c-83b6-a1077eeb5434.jpg",
    "order": 34
  },
  {
    "id": "tgi-monitoria:56aaa330-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a inervação do fígado?",
    "a": "Plexo hepático (Plexo acessório do plexo celíaco -periarterial-)\n(N. Vago e continuação dos Nn. Esplâncnicos)",
    "frontImage": null,
    "backImage": null,
    "order": 35
  },
  {
    "id": "tgi-monitoria:56aaa331-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a irrigação do esôfago? quais os pontos de constrição?",
    "a": "Cervical: Aa. Tireóideas inferiores \n\nTorácico: 3 a 6 ramos esofágicos diretos da aorta\n\nAbdominal: A. Gástrica esquerda e Aa. Frênicas \ninferiores\n\n•Pontos de constrição:\nJunção faringoesofágico\nConstrição Broncoaórtica\nConstrição diafragmática (hiato esofágico)",
    "frontImage": null,
    "backImage": null,
    "order": 36
  },
  {
    "id": "tgi-monitoria:56aaa332-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o conteúdo do ligamento redondo do fígado?",
    "a": "V. Umbilical obliterada\n\n+Vv. Paraumbilicais",
    "frontImage": null,
    "backImage": null,
    "order": 37
  },
  {
    "id": "tgi-monitoria:56aaca40-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "por que acontece e o que ocorre depois de uma hipertensão porta do fígado?\n\nquais as VIAS HEPATOFUGAIS?",
    "a": "acontece por causa de cirrose.\n\nCirculação colateral pós Hipertensão portal\n=\nVIAS HEPATOFUGAIS:\n•Vv esofágicas que drenam para a V. Ázigos\n•V. Retal média que drenam para a VCI\n•V. Retal inf que drenam para a VCI\n•Vv. Paraumbilicais e Vv. Epigástricas (Causa sinal de cabeça de medusa)",
    "frontImage": null,
    "backImage": null,
    "order": 38
  },
  {
    "id": "tgi-monitoria:56aaf150-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os casos de hipertensão maligna a partir de problemas da irrigação Renal?",
    "a": "Estenose da A. Renal, faz com que o rim produza mais renina e angiotensina, em resposta à ''hipotensão''\n(causando vasoconstrição)\n\nTumor de suprarrenal aumenta a produção de catecolaminas pelas células cromafins causando hipertensão\nmaligna",
    "frontImage": null,
    "backImage": null,
    "order": 39
  },
  {
    "id": "tgi-monitoria:56aaf151-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apresentada?",
    "a": "N. Genitofemoral (está anterior ao M. Psoas maior)",
    "frontImage": "tgi-monitoria/19a45170-4c0d-1347-9031-0556ba2a088d.jpg",
    "backImage": null,
    "order": 40
  },
  {
    "id": "tgi-monitoria:56aaf152-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apontada?",
    "a": "N. cutâneo femoral lateral",
    "frontImage": "tgi-monitoria/5ec90030-f49e-135c-b0ea-9d9be027019e.jpg",
    "backImage": null,
    "order": 41
  },
  {
    "id": "tgi-monitoria:56ab1860-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apontada?",
    "a": "N. Ilioinguinal (indo para o canal inguinal )\n\nOBS- ele não entra pelo anel inguinal profundo",
    "frontImage": "tgi-monitoria/c9b47c30-f4b7-135c-b0ea-9d9be027019e.jpg",
    "backImage": null,
    "order": 42
  },
  {
    "id": "tgi-monitoria:56ab1861-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o conteúdo do hiato aórtico? e a formação?",
    "a": "Formado pelos pilares diafragmáticos (Direito e Esquerdo) e Lig. Arqueado mediano\n\nAorta \nDucto torácico\nV. Ázigos\nV. Hemiázigos \n\n\nOBS- Nn. Esplâncnicos passam por pequenas aberturas)",
    "frontImage": null,
    "backImage": null,
    "order": 43
  },
  {
    "id": "tgi-monitoria:56ab1862-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o conteúdo do hiato esofágico? qual a sua formação?",
    "a": "Formado pelo pilar direito do diafragma\n\nEsôfago \nVasos Esofágicos (ramos da Aorta torácica e da A. Gástrica esq)\nTroncos vagais (anterior- provem do N. Vago esquerdo e posterior- provem do N. vago direito)",
    "frontImage": null,
    "backImage": null,
    "order": 44
  },
  {
    "id": "tgi-monitoria:56ab3f70-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o conteúdo do forame da veia cava inferior do Diafragma?",
    "a": "V. Cava inferior\nRamos terminais do N. Frênico direito",
    "frontImage": null,
    "backImage": null,
    "order": 45
  },
  {
    "id": "tgi-monitoria:56ab3f71-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a irrigação do diafragma? e drenagem?",
    "a": "4 Ramos:\n\nRamos da Aorta\nAa. Frênicas superiores (aorta torácica)\n\nAa. Frênica inferiores (aorta abdominal)\n\nRamos da A. Torácica interna\nA. Pericardicofrênica\nA. Musculofrênica\n\nDrenagem:\nVeias do mesmo nome, exceto as veias frênicas inferiores (possuem duas) que uma drena para a VCI e outra se junta a V. Suprarrenal esq e tributam na V. Renal esq",
    "frontImage": null,
    "backImage": null,
    "order": 46
  },
  {
    "id": "tgi-monitoria:56ab3f72-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os nervos que tem relação com o M. Psoas Maior?",
    "a": "N. Genitofemoral (anterior)\nN. Obturatório (Medial)\nN. Femoral (lateral)\n\nLaterais e superiores:\nN. Subcostal\nN. Iliohipogástrico\n(OBS- As vezes N. Iliohipogástrico e N. Ilioinguinal saem juntos)\nN. Ilioinguinal\nN. Cutâneo femoral lateral (mais afastado)",
    "frontImage": null,
    "backImage": "tgi-monitoria/d6147dd0-760c-147c-83b6-a1077eeb5434.jpg",
    "order": 47
  },
  {
    "id": "tgi-monitoria:56ab6680-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os dermátomos importantes?",
    "a": "T4- Mamilo\nT10- Umbigo\nT12- Sínfise púbica",
    "frontImage": null,
    "backImage": null,
    "order": 48
  },
  {
    "id": "tgi-monitoria:56ab6681-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a inervação das vísceras abdominais?",
    "a": "Parassimpático- N. Vago (tronco vagal anterior- N. Vago Esq e posterior-N. Vago Dir)\n+ Nn. Esplâncnicos Pélvicos\n\nSimpático- Nn. Esplâncnicos abdominopélvicos (T5-T9 Maior// T10- T11 Menor// T12 Imo// Lombares// Sacrais)\n\nOBS- N. Vago inerva até a flexura esplênica do colo (Flexura esquerda)",
    "frontImage": null,
    "backImage": null,
    "order": 49
  },
  {
    "id": "tgi-monitoria:56ab8d90-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a função dos ramos comunicantes brancos e cinzentos?",
    "a": "Essa comunicação existe entre nervos do sistema nervoso autônomo e do somático, com o intuito de integrar maior número de fibras para as vísceras, aumentando o alcance da inervação de ambos",
    "frontImage": null,
    "backImage": null,
    "order": 50
  },
  {
    "id": "tgi-monitoria:56ab8d91-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual é a síndrome de quebra nozes?",
    "a": "É a compressão da V. Renal esquerda ao passar entre a Aorta abdominal e A. Mensetérica sup\n\nOBS- a V. Renal esquerda recebe a V. Gonadal esq e a V. suprarrenal esq\n(diferente da V. Renal direita que não recebe )",
    "frontImage": null,
    "backImage": null,
    "order": 54
  },
  {
    "id": "tgi-monitoria:56ab8d92-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os ramos da A. Ilíaca externa?",
    "a": "A. Circunflexa ilíaca profunda\nA. Epigástrica inferior",
    "frontImage": null,
    "backImage": null,
    "order": 57
  },
  {
    "id": "tgi-monitoria:56abb4a0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os ramos da A. Ilíaca Interna?",
    "a": "Tronco posterior:\nA. Iliolombar\nAa. Sacrais laterais\nA. Glútea sup\n\nTronco Anterior:\nA. Umbilical\nA. Obturatória\nA. Vesical inf\nA. Retal média\nA. Pudenda interna\nA. Glútea inf",
    "frontImage": null,
    "backImage": null,
    "order": 58
  },
  {
    "id": "tgi-monitoria:56abb4a1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os ramos da A. Hepática Comum e os ramos dos seus ramos?",
    "a": "•A. Gastroduodenal:\nA. Gastromental direita\nA. Pancreatica duodenal Sup (anterior e posterior)\n\n\n•A. Hepática Própria;\nA. Supraduodenal\nA. Hepática Direita\n(A. Cística)\nA. Hepática esquerda\nA. Gástrica direita",
    "frontImage": null,
    "backImage": null,
    "order": 59
  },
  {
    "id": "tgi-monitoria:56abb4a2-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a circulação colateral após obstrução da V. Cava inferior?",
    "a": "•Vv. Epigástricas (superior e inferior)\n\n•V. Ázigos a partir das Veias esofágicas\n\n•V. Toracoepigástrica Anastomose entre V. Torácica lateral e V. Epigástrica superficial\n\n•Sistema Venoso peridural da Medula espinhal (conecta Vv. Lombares e Vv. Intercostais posteriores)",
    "frontImage": null,
    "backImage": null,
    "order": 60
  },
  {
    "id": "tgi-monitoria:56abdbb0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a origem da cisterna do quilo? qual a sua drenagem?",
    "a": "está posterior e à direita da aorta abdominal (nível de tronco celíaco)\n\n\ndrena todos os membros inferiores \n\nducto torácico começa a partir dele e drena hemitórax Esq, MMSS Esq e cabeça e pescoço\n\nOBS- ducto torácico desemboca no ângulo venoso esquerdo",
    "frontImage": null,
    "backImage": "tgi-monitoria/1d659380-a61f-1396-9577-dd11e62f0ac2.jpg",
    "order": 61
  },
  {
    "id": "tgi-monitoria:56abdbb1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "Defina a linha arqueada",
    "a": "Formado a partir da  ausência de aponeurose dos músculos Oblíquo interno e M. Transverso do Abdômen que passam anteriormente \napós a Linha Arqueada\n\nOBS- ela é formada na visão posterior da parede do abdômen",
    "frontImage": null,
    "backImage": null,
    "order": 62
  },
  {
    "id": "tgi-monitoria:56abdbb2-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "defina hérnias inguinais diretas e indiretas",
    "a": "diretas- dentro do trígono inguinal (medial aos vasos epigástricos inferiores)\n\nindiretas- laterias aos vasos epigástricos inferiores",
    "frontImage": null,
    "backImage": null,
    "order": 63
  },
  {
    "id": "tgi-monitoria:56ac02c0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "defina a hérnia de spiegel e Epigástrica",
    "a": "Spiegel- na linha semilunar do abdômen \n\nEpigástrica- Entre o processo xifóide e o umbigo",
    "frontImage": null,
    "backImage": null,
    "order": 64
  },
  {
    "id": "tgi-monitoria:56ac29d0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os limites do trígono inguinal (Hasselbach)?",
    "a": "Medial- Borda lateral do M. Reto do abdômen \n\nLateral- Vasos epigástricos inferiores\n\nInferior- Lig. Inguinal",
    "frontImage": null,
    "backImage": "tgi-monitoria/6d9c9eb0-7808-147c-83b6-a1077eeb5434.jpg",
    "order": 65
  },
  {
    "id": "tgi-monitoria:56ac29d1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o conteúdo do funículo espermático?",
    "a": "7 componentes;\n\nA. Cremasterica\nA. Testicular\nA. do Ducto Deferente\nM. Cremáster\nDucto deferente\nPlexo pampiniforme\nRamo genital do N. Genitofemoral",
    "frontImage": null,
    "backImage": null,
    "order": 66
  },
  {
    "id": "tgi-monitoria:56ac50e0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "defina os limites e o conteúdo do canal inguinal",
    "a": "anterior- Aponeurose do M. Oblíquo externo\n\nposterior- Fáscia transversal\n\nSuperior- M. Oblíquo interno e M. Transverso do Abdômen \n\nInferior-Lig. Inguinal + Lig. Lacunar\n\nConteúdo:\nN. Ilioinguinal\n\n+ funículo espermático\n(homens)\nou\n+ Lig. Redondo do Útero (mulheres)",
    "frontImage": null,
    "backImage": null,
    "order": 67
  },
  {
    "id": "tgi-monitoria:56ac50e1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "defina a relação de lateralidade da Tríade portal",
    "a": "Posterior- V. Porta (posterior)\nLateral- Ducto colédoco\nMedial- A. Hepática própria",
    "frontImage": null,
    "backImage": null,
    "order": 68
  },
  {
    "id": "tgi-monitoria:56ac77f0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o conteúdo do Lig. Treitz? e qual a sua origem?",
    "a": "M. Suspensor do duodeno (abre o canal da flexura duodenojejunal)\n\nOriginado no pilar direito do diafragma",
    "frontImage": null,
    "backImage": null,
    "order": 69
  },
  {
    "id": "tgi-monitoria:56ac77f1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "diferencie diarréia digestiva alta e baixa",
    "a": "Alta- Antes da Válvula ileocecal (intestino delgado)\nSangramento\n\nBaixa- Após a válvula ileocecal (intestino grosso)\nSem sangramento",
    "frontImage": null,
    "backImage": null,
    "order": 70
  },
  {
    "id": "tgi-monitoria:56ac77f2-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "o que são as papilas duodenais?",
    "a": "Papila duodenal maior- abertura da ampola hepatopancreática\n\nPapila duodenal menor- Ducto pancreático acessório (as vezes nem existe)",
    "frontImage": null,
    "backImage": null,
    "order": 71
  },
  {
    "id": "tgi-monitoria:56ac9f00-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "defina o arco justacólico",
    "a": "também chamado de A. Marginal de Drummond \n\nanastomose de RIOLAN- menor mas também entre A. Mesentérica superior e A. Mesentérica inferior \n(não dá pra diferenciar na peça)\n\nINTESTINO GROSSO \n\nAnastomose entre:\nA. Mesentérica sup-\n•A. Cólica direita\n•A. Cólica média\nA. Mesentérica inf-\n• A.Cólica esquerda\n•Aa. Sigmóideas",
    "frontImage": null,
    "backImage": "tgi-monitoria/8aeb6dd0-c07d-139b-a9ac-153b904cfbed.jpg",
    "order": 72
  },
  {
    "id": "tgi-monitoria:56ac9f01-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o conteúdo do Lig. Esplenorrenal? e do Lig. Gastroesplênico?",
    "a": "Lig. Esplenorrenal- Vasos. Esplênicos\n\nLig. Gastroesplênicos- Vasos gastromentais e Gástricos curtos",
    "frontImage": null,
    "backImage": null,
    "order": 74
  },
  {
    "id": "tgi-monitoria:56ac9f02-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a irrigação do intestino delgado?",
    "a": "Duodeno-\nA. Supraduodenal (A. Hepática propria)\nA. Gastroduodenal (A. Hepática Comum) \n\nA. Pancreática duodenal sup (anterior e posterior)\n- ramo da A. Gastromental\n\nA. Pancreatico duodenal inf (anterior e posterior)\n- Ramo da A. Mesentérica sup\n\nJejuno e Ileo\nArtérias jejunais e ileais \nramos da A. Mesentérica sup (arco jejunoileal)",
    "frontImage": null,
    "backImage": null,
    "order": 75
  },
  {
    "id": "tgi-monitoria:56acc610-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os ramos da A. Esplênica?",
    "a": "5 ramos\n\nA. Gastromental esq\nAa. Gástricas curtas\nA. Pancreática Magna\nA. Pancreática dorsal\nA. da Cauda do Pâncreas\n\nOBS: as vezes ela dá a A. Gástrica posterior",
    "frontImage": null,
    "backImage": null,
    "order": 76
  },
  {
    "id": "tgi-monitoria:56acc611-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "defina o sinal de  cabeça de medusa",
    "a": "causado por hipertensão portal (cirrose hepática)\n\nAnastomose entre Vv. Paraumbilicais e Vv. Epigástricas",
    "frontImage": null,
    "backImage": "tgi-monitoria/3570dce0-9996-1396-9577-dd11e62f0ac2.jpg",
    "order": 77
  },
  {
    "id": "tgi-monitoria:56acc612-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o conteúdo da Papila duodenal maior? onde ela se localiza?",
    "a": "M. Esfíncter da Ampola Hepatopancreática\n\nlocaliza-se na 2ª porção do duodeno (descendente)\n\n\nOBS- Vasos mesentéricos superiores ultrapassam o duodeno na 3ª porção (horizontal)",
    "frontImage": null,
    "backImage": null,
    "order": 78
  },
  {
    "id": "tgi-monitoria:56aced20-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual ponto anatômico diferencia hemorragia digestiva alta e baixa?",
    "a": "Flexura duodenojejunal (Ângulo De treitz )\n\n\nAlta- Sangue Escuro\n\nBaixa- Sangue vivo/ claro",
    "frontImage": null,
    "backImage": null,
    "order": 79
  },
  {
    "id": "tgi-monitoria:56aced21-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o lobo do fígado próximo à VCI e ao ligamento redondo do fígado? o que separa os lobos do fígado?",
    "a": "Próximo à VCI: \nLobo Caudado\nCava- caudado\n\nPróximo ao Lig. Redondo do fígado\nLobo Quadrado\nRedondo-Quadrado\n\nO que separa os lobos do fígado é a Fissura do Lig. Venoso( componente do H do Fígado)\n\nOBS- Lobos caudado e quadrado são do Lobo Direito",
    "frontImage": null,
    "backImage": "tgi-monitoria/ce4d4860-fd6e-1399-a9ac-153b904cfbed.jpg",
    "order": 80
  },
  {
    "id": "tgi-monitoria:56ad1430-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual vaso pode ser lesado por uma corrosão da parede gástrica ?",
    "a": "A. Gastroduodenal que passa entre a primeira porção do duodeno e do canal pilórico",
    "frontImage": null,
    "backImage": null,
    "order": 81
  },
  {
    "id": "tgi-monitoria:56ad1431-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os órgãos retroperitoneais?",
    "a": "SAD PURCKE:\n\nS- Suprarrenal\nA- Aorta e VCI\nD- Duodeno (2ª-4ª porção)\n\nP- Pâncreas\nU- Ureter\nR- Reto (Colo)\nC- Colo (Ascendente e Descendente)\nK- Kidney (Rim)\nE- Esôfago abdominal",
    "frontImage": null,
    "backImage": null,
    "order": 82
  },
  {
    "id": "tgi-monitoria:56ad1432-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais as notas anatomoclínicas de cada parte do duodeno?",
    "a": "1ª porção- sai o Lig. Hepatoduodenal (tríade portal)\n\n2ª porção- possui a papila duodenal maior\n\n3ª porção- vasos mesentéricos superiores  passam anteriormente \n\n4ª porção- Local do Ângulo de Treitz- flexura duodenojejunal",
    "frontImage": null,
    "backImage": null,
    "order": 83
  },
  {
    "id": "tgi-monitoria:56ad3b40-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a formação da cisterna do quilo?",
    "a": "tronco linfático instestinal\ntronco lifático lombar direito\ntronco linfático lombar esquerdo",
    "frontImage": null,
    "backImage": null,
    "order": 84
  },
  {
    "id": "tgi-monitoria:56ad3b41-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "para onde as veias hepáticas drenam?",
    "a": "V. Hepática Dir- Drena para a VCI\n\nV. Hepática Média- Drena para a V. Hepática Esq\n\nV. Hepática Esq- Drena para a VCI",
    "frontImage": null,
    "backImage": null,
    "order": 85
  },
  {
    "id": "tgi-monitoria:56ad6250-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura na pinça?",
    "a": "Vasos epigástricos inferiores\n\nOBS- estão na prega umbilical lateral",
    "frontImage": "tgi-monitoria/ad19bcd0-82d9-139c-8cda-396e1cd69515.jpg",
    "backImage": null,
    "order": 86
  },
  {
    "id": "tgi-monitoria:56ad6251-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "o que as aponeuroses dos Mm. abdominais formam?",
    "a": "M. Reto do Abdômen- Linha alba\n\nM. Oblíquo ext- Fáscia Espermática Ext\n\nM. Oblíquo int- Fáscia Cremastérica",
    "frontImage": null,
    "backImage": null,
    "order": 87
  },
  {
    "id": "tgi-monitoria:56ad8960-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual marco de transição do andar supracólico para o infracólico?",
    "a": "Colo transverso",
    "frontImage": null,
    "backImage": null,
    "order": 88
  },
  {
    "id": "tgi-monitoria:56ad8961-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a irrigação da parede antero-lateral do abdômen?",
    "a": "A. Musculofrênica\nA. Epigástrica superficial\nA. Epigástrica superior\nA. Epigástrica inferior\nA. Circunflexa ilíaca superficial \nA. Circunflexa ilíaca profunda\nAa. Lombares (4 pares)",
    "frontImage": null,
    "backImage": null,
    "order": 89
  },
  {
    "id": "tgi-monitoria:56adb070-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apontada pelo alfinete azul?",
    "a": "A. Esofágica (ramo da A. Gástrica esquerda)",
    "frontImage": "tgi-monitoria/e42c0f70-9b02-13a6-84ff-e59428de54e7.jpg",
    "backImage": null,
    "order": 90
  },
  {
    "id": "tgi-monitoria:56adb071-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais as estruturas apontadas?",
    "a": "azul- prega umbilical medial (A. Umbilical obliterada)\n\nvermelho- vasos epigástricos inferiores\n(na prega umbilical lateral)",
    "frontImage": "tgi-monitoria/e42bd700-9b73-13a6-84ff-e59428de54e7.jpg",
    "backImage": null,
    "order": 91
  },
  {
    "id": "tgi-monitoria:56adb072-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "defina a inervação dos dentes",
    "a": "processos alveolares superiores\n\nN. Alveolar superior anterior e médio são ramos do N. Infraorbital (ramo do V2)\n\nN. Alveolar superior posterior é ramo direto do V2\n\nProcessos alveolares inferior- \nN. Alveolar inferior (ramo de V3)",
    "frontImage": null,
    "backImage": null,
    "order": 92
  },
  {
    "id": "tgi-monitoria:56add780-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "O que forma o esfíncter esofágico superior?",
    "a": "Espaço abaixo do M. Constritor inferior da faringe\n(transição faringoesofágica)",
    "frontImage": null,
    "backImage": null,
    "order": 93
  },
  {
    "id": "tgi-monitoria:56add781-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apresentada?",
    "a": "haustração cólica",
    "frontImage": "tgi-monitoria/811658b0-ed84-13a8-9245-e1d016fcd73e.jpg",
    "backImage": null,
    "order": 94
  },
  {
    "id": "tgi-monitoria:56add782-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apontada pela ponta da pinça?",
    "a": "V. Mesentérica inf (passa ao lado da flexura duodenojejunal",
    "frontImage": "tgi-monitoria/13a7d720-ed72-13a8-9245-e1d016fcd73e.jpg",
    "backImage": null,
    "order": 95
  },
  {
    "id": "tgi-monitoria:56adfe90-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais veias tributam na V. Porta?",
    "a": "V. Cística\nV. Gástrica direita\nV. Gástrica esquerda \nVv. Paraumbilicais\n\nOBS- Veias pancreáticas drenam para a V. Esplênica",
    "frontImage": null,
    "backImage": null,
    "order": 96
  },
  {
    "id": "tgi-monitoria:56adfe91-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais ligamentos formam os omentos?",
    "a": "omento menor: \nLig. Hepatoduodenal \nLig. Hepatogástrico\n\nomento maior:\nLig. Gastroesplênico (principal)\nLig. Gastrofrênico\nLig. Gastrocólico",
    "frontImage": null,
    "backImage": null,
    "order": 97
  },
  {
    "id": "tgi-monitoria:56ae25a0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "defina a síndrome de wikier",
    "a": "3ª porção do duodeno sendo comprimida pela AMS e a Aorta abdominal",
    "frontImage": null,
    "backImage": null,
    "order": 98
  },
  {
    "id": "tgi-monitoria:56ae25a1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a irrigação do ceco?",
    "a": "ramos da A. Ileocólica (A. Mesentérica sup)\n\nA. Cecal anterior \nA. Cecal posterior",
    "frontImage": null,
    "backImage": null,
    "order": 99
  },
  {
    "id": "tgi-monitoria:56ae25a2-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a irrigação do diafragma?",
    "a": "Aa. Frênicas superiores (aorta torácica)\n\nAa. Frênica inferiores (aorta abdominal)\n\nA. Musculofrênica (A. Torácica interna)\n\nA. Pericardicofrênica (A. Torácica interna)",
    "frontImage": null,
    "backImage": null,
    "order": 100
  },
  {
    "id": "tgi-monitoria:56ae4cb0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apontada em azul escuro?",
    "a": "V. Mesentérica inf \n\nOBS- tributa na V. Esplênica",
    "frontImage": "tgi-monitoria/56bafe30-2d0a-13bc-a2ad-db955403c929.jpg",
    "backImage": null,
    "order": 101
  },
  {
    "id": "tgi-monitoria:56ae4cb1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apontada?",
    "a": "A. Suprarrenal inf",
    "frontImage": "tgi-monitoria/95343b20-2d7a-13bc-a2ad-db955403c929.jpg",
    "backImage": null,
    "order": 102
  },
  {
    "id": "tgi-monitoria:56ae4cb2-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a inervação dos músculos da parede abdominal?",
    "a": "M. Oblíquo ext \nM. Reto do abdômen \n(T7-T12)\n\nM. Piramidal\n(T12)\n\nM. Oblíquo int\nM. Transverso do Abdômen \n(T7-L1)",
    "frontImage": null,
    "backImage": null,
    "order": 103
  },
  {
    "id": "tgi-monitoria:56ae73c0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais veias drenam para a VCI?",
    "a": "V. Frenica inf Dir\nV. suprarrenal dir\nVv. Renais\nV. Gonadal dir\nVv. Lombares\nVv. Ilíacas comuns\nVv. Hepáticas (dir, média e esq)",
    "frontImage": null,
    "backImage": null,
    "order": 104
  },
  {
    "id": "tgi-monitoria:56ae73c1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "o que é a linha de toldt?",
    "a": "fixação do colo ascendente e descendente a partir do peritônio com a parede do abdômen\n\nOBS- importante em cirurgias para acesso retroperitoneal (não há vascularização nessa área)",
    "frontImage": null,
    "backImage": "tgi-monitoria/96a200c0-688b-147c-83b6-a1077eeb5434.jpg",
    "order": 105
  },
  {
    "id": "tgi-monitoria:56ae73c2-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais camadas atravessadas até chegar dentro da cavidade abdominal?",
    "a": "Pele\nFáscia de Camper (Gordura)\nFáscia de Scarpa\nM. Oblíquo ext\nM. Oblíquo int\nM. Transverso do Abdômen \nFáscia transversal\nGordura extraperitoneal\nPeritônio Parietal\n\nOBS- Peritonio visceral é aderido à víscera",
    "frontImage": null,
    "backImage": null,
    "order": 106
  },
  {
    "id": "tgi-monitoria:56ae9ad0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a formação do ducto linfático?",
    "a": "•Tronco linfático subclávio direito\n•Tronco Linfático Broncomediastinal direito\n•Tronco Linfático Jugular direito",
    "frontImage": null,
    "backImage": null,
    "order": 107
  },
  {
    "id": "tgi-monitoria:56ae9ad1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual artéria pode ser lesada numa incisão no ponto de Mcburney?",
    "a": "A. Circunflexa ilíaca profunda( ramo da A. Ilíaca externa)",
    "frontImage": null,
    "backImage": null,
    "order": 108
  },
  {
    "id": "tgi-monitoria:56aec1e0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a inervação do peritônio?",
    "a": "peritônio parietal- Nn. Intercostais de T7-L1\n\nPetitônio visceral- Nn. aferentes autonômicos (N. Vago+ Nn. Toracoadbominais)",
    "frontImage": null,
    "backImage": null,
    "order": 109
  },
  {
    "id": "tgi-monitoria:56aee8f0-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais as funções do peritônio?",
    "a": "•movimento das vísceras\n\n•local de trânsito de vasos e nervos\n\n•absorção \n\n•proteção\n\n•armazenamento de gordura\n\n•hemodiálise \n\n•via de administração de medicamentos",
    "frontImage": null,
    "backImage": null,
    "order": 110
  },
  {
    "id": "tgi-monitoria:56aee8f1-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os únicos colos que podem sofrer torção? (volvo)",
    "a": "Colo transverso\nColo Sigmóide\n\npois são peritonizados// livres na cavidade abdominal\n\nOBS- Volvo de sigmóide- sinal de grão de café na radiografia",
    "frontImage": null,
    "backImage": null,
    "order": 111
  },
  {
    "id": "tgi-monitoria:56af1000-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais as estruturas apontadas pelo ponto preto e azul claro inferior?",
    "a": "Ponto preto- A. Cólica direita\n\nponto azul claro- A. Ileocólica",
    "frontImage": "tgi-monitoria/23c03f80-a8df-13d0-8de0-5188da034ea2.jpg",
    "backImage": null,
    "order": 112
  },
  {
    "id": "tgi-monitoria:56af1001-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "por que a dor referida de um peritonite do recesso subfrênico é na escápula?",
    "a": "porque o N. Frênico tem raízes C3-C5. O nervo se comunica com o N. Supraescapular (ramo do tronco superior do plexo braquial- C5-C6)",
    "frontImage": null,
    "backImage": null,
    "order": 113
  },
  {
    "id": "tgi-monitoria:56af1002-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a formação dos gânglios celíaco e aórtico renal?",
    "a": "Celíaco: Vago+ Esplâncnico maior\n\nAórtico Renal: Vago+ Esplâncnico menor e imo",
    "frontImage": null,
    "backImage": null,
    "order": 114
  },
  {
    "id": "tgi-monitoria:56af3710-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais as estruturas apontadas?",
    "a": "laranja- A. Pancreaticaduodenal superior\n\nazul- A. Gastromental direita\n\nbranco/ pinça- A. Gastroduodenal",
    "frontImage": "tgi-monitoria/e12eb2b0-1f34-13d1-946f-7f5a320575e5.jpg",
    "backImage": null,
    "order": 115
  },
  {
    "id": "tgi-monitoria:56af3711-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apontada pela pinça?",
    "a": "pinça- A. Sacral mediana",
    "frontImage": "tgi-monitoria/01fbafa0-23b5-13d1-946f-7f5a320575e5.jpg",
    "backImage": null,
    "order": 116
  },
  {
    "id": "tgi-monitoria:56af5e20-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais as estruturas apontadas?",
    "a": "azul-A. Pancreática dorsal\n\nlaranja- A. Pancreática dorsal (sao varios ramos) \n\nOBS- Pancreática magna é bem no corpo do pâncreas\n\namarelo- A. Da cauda do pâncreas",
    "frontImage": "tgi-monitoria/15dcf530-2881-13d1-946f-7f5a320575e5.jpg",
    "backImage": null,
    "order": 117
  },
  {
    "id": "tgi-monitoria:56af5e21-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "a estrutura na pinça é a AMS, quais os ramos presentes?",
    "a": "verde- A. Pancreatica duodenal sup\n\nAzul- A. Cólica média",
    "frontImage": "tgi-monitoria/e2c323e0-2af1-13d1-946f-7f5a320575e5.jpg",
    "backImage": null,
    "order": 118
  },
  {
    "id": "tgi-monitoria:56af5e22-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apontada pelo alfinete vermelho?\nOBS: Há variação",
    "a": "A. Frênica inferior esquerda saindo do tronco celíaco\n\nOBS- Normal é sair das laterais da Aorta abdominal",
    "frontImage": "tgi-monitoria/847165c0-e94b-13d3-a719-0dcaa380b7be.jpg",
    "backImage": null,
    "order": 119
  },
  {
    "id": "tgi-monitoria:56af8530-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a estrutura apontada pela pinça?",
    "a": "A. Hepática Média (saindo da A. Hepática direita)",
    "frontImage": "tgi-monitoria/763384c0-e419-13d3-a719-0dcaa380b7be.jpg",
    "backImage": null,
    "order": 120
  },
  {
    "id": "tgi-monitoria:56af8531-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a artéria que seria considerada a artéria da cauda nos animais?",
    "a": "A. Sacral mediana",
    "frontImage": null,
    "backImage": null,
    "order": 121
  },
  {
    "id": "tgi-monitoria:56af8532-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "quais os limites da bolsa omental?",
    "a": "anterior- estômago\n\nposterior- Pâncreas, aorta, rim e suprarrenal esquerdos\n\nsuperior- fígado e diafragma \n\ninferior- Mesocolo transverso",
    "frontImage": null,
    "backImage": null,
    "order": 122
  },
  {
    "id": "tgi-monitoria:56afac40-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual é a anastomose de Bühler?",
    "a": "Anastomose entre as arcadas pancreaticaduodenais\n\n(Tronco celíaco e A. Mesentérica superior)",
    "frontImage": null,
    "backImage": null,
    "order": 123
  },
  {
    "id": "tgi-monitoria:56afac41-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "as artérias do funículo espermático são ramos de quem?",
    "a": "A. Do ducto deferente- A. Vesical inferior\n\nA. Testicular- Aorta abdominal\n\nA. Cremastérica- A. Epigástrica inferior",
    "frontImage": null,
    "backImage": null,
    "order": 124
  },
  {
    "id": "tgi-monitoria:56afac42-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a irrigação do ducto colédoco?",
    "a": "3 artérias\n\nA. Pancreáticaduodenal sup posterior\nA. Hepática própria\nA. Cística",
    "frontImage": null,
    "backImage": null,
    "order": 125
  },
  {
    "id": "tgi-monitoria:56afd350-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual o primeiro ramo da A. Hepática própria?",
    "a": "A. Supraduodenal",
    "frontImage": null,
    "backImage": null,
    "order": 126
  },
  {
    "id": "tgi-monitoria:56afd351-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a relação de lateralidade dos vasos mesentéricos superiores com o pâncreas?",
    "a": "•Os vasos são anteriores ao colo do pâncreas\n\n•Os vasos são posteriores ao processo uncinado",
    "frontImage": null,
    "backImage": "tgi-monitoria/cea14db0-72c1-147c-83b6-a1077eeb5434.jpg",
    "order": 127
  },
  {
    "id": "tgi-monitoria:56afd352-3740-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-monitoria",
    "cat": 16,
    "src": "📥 TGI - Monitoria",
    "b": "b-unc",
    "q": "qual a relação de lateralidade dos vasos mesentéricos superiores com o duodeno?",
    "a": "eles passam anteriormente à 3ª porção do duodeno (porção horizontal)",
    "frontImage": null,
    "backImage": "tgi-monitoria/a55f3b60-7546-147c-83b6-a1077eeb5434.jpg",
    "order": 128
  },
  {
    "id": "tgi-prova-normal:fa9f3b10-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais os nomes do pontos marcados?",
    "a": "amarelo- vestíbulo bucal inferior\n\nazul escuro- M. Genioglosso\n\nverde escuro-M. Geniohióide\n\nbranco inferior-  M. Milohióide\n\nazul claro- Torus Tubário\n\nlaranja- óstio faríngeo da tuba auditiva\n\nvermelho- Prega salpingo palatina\n\npreto- Prega salpingo faríngea\n\nbranco superior- Tonsila faríngea\n\nVerde claro- recesso faríngeo",
    "frontImage": "tgi-prova-normal/abf83400-cc11-1166-b14b-b331f9db8fc4.jpg",
    "backImage": null,
    "order": 0
  },
  {
    "id": "tgi-prova-normal:fa9fd750-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais os pontos marcados?",
    "a": "branco- Arco palatoglosso\n\namarelo- Arco palatofaríngeo\n\nazul- Tonsila palatina\n\nverde- Valécula\n\nvermelho- Cartilagem Epiglote",
    "frontImage": "tgi-prova-normal/9ba038b0-d59d-1166-b14b-b331f9db8fc4.jpg",
    "backImage": null,
    "order": 1
  },
  {
    "id": "tgi-prova-normal:fa9fd751-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais os pontos azuis e o  preto?",
    "a": "Azuis- Sulco terminal da língua\n\nPreto- forame cego (resquício do ducto tireoglosso)",
    "frontImage": "tgi-prova-normal/f05d1f90-43b0-1167-b14b-b331f9db8fc4.png",
    "backImage": null,
    "order": 2
  },
  {
    "id": "tgi-prova-normal:fa9ffe60-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "o que está apontado pela seta amarela?",
    "a": "pregas gástricas",
    "frontImage": "tgi-prova-normal/b1d0a620-991e-1167-b14b-b331f9db8fc4.jpg",
    "backImage": null,
    "order": 3
  },
  {
    "id": "tgi-prova-normal:fa9ffe61-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais as porções marcadas?",
    "a": "vermelho- ceco\n\nroxo- Tênia livre\n\ndedo - Apêndice vermiforme\n\nalfinete- mesoapêndice",
    "frontImage": "tgi-prova-normal/82eca8b0-9a02-1167-b14b-b331f9db8fc4.jpg",
    "backImage": null,
    "order": 4
  },
  {
    "id": "tgi-prova-normal:faa02570-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "espaço da pinça e os limites",
    "a": "forame omental (forame de winslow)\n\nLIMITES:\nSUP: Lobo Caudado do Fígado\nINF:1ª porção do duodeno\nanterior: V. Porta (componente da tríade portal)\nposterior: veia cava inferior\n\nOBS- Tríade portal;\nV. Porta (posterior\nA. Hepática própria(medial)\nDucto Colédoco (lateral) (=Ducto Cístico+ Ducto hepatico comum)",
    "frontImage": "tgi-prova-normal/4eae69c0-e27e-1167-b14b-b331f9db8fc4.jpg",
    "backImage": null,
    "order": 5
  },
  {
    "id": "tgi-prova-normal:faa02571-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais os musculos extrínsecos da lingua?",
    "a": "4 Músculos\n\nM.Genioglosso\nM.hioglosso\nM.Estiloglosso\nInervados pelo NERVO HIPOGLOSSO\n\nM. Palatoglosso- N. Vago\n\nOBS- Logo, nem todos são inervados pelo N. Hipoglosso",
    "frontImage": null,
    "backImage": null,
    "order": 6
  },
  {
    "id": "tgi-prova-normal:faa02572-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura sinalizada ?",
    "a": "flexura duodenojejunal\n\nOBS- é fixada pelo M. Suspensor do duodeno (conteúdo do Lig. Treitz)",
    "frontImage": "tgi-prova-normal/42b2a420-82e2-1180-ae41-596f50697215.jpg",
    "backImage": null,
    "order": 7
  },
  {
    "id": "tgi-prova-normal:faa07390-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura na pinça?",
    "a": "ducto cístico ( oriundo da vesícula biliar)\n\nUm dos componentes do trígono de calot:\nDucto cístico, ducto hepático comum e a borda inferior do fígado\n\nCONTEÚDO DO TRÍGONO:\nA. Cística",
    "frontImage": "tgi-prova-normal/eeda45f0-84c5-11aa-b65c-eb0d0ce250c6.png",
    "backImage": "tgi-prova-normal/61aca9e0-3ab2-12eb-8775-1f8f280d18df.jpg",
    "order": 8
  },
  {
    "id": "tgi-prova-normal:faa07391-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "defina a formação do ducto colédoco e a sua função:",
    "a": "Junção do: Ducto cístico da vesícula biliar e Ducto Hepático comum do fígado\n\nFunção: levar a bile para o duodeno",
    "frontImage": null,
    "backImage": null,
    "order": 9
  },
  {
    "id": "tgi-prova-normal:faa09aa0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome das estruturas marcadas?",
    "a": "Laranja- A. Mesenterica Inferior( ultimo ramo anterior da Aorta abdominal)\n\nRoxo- A. Cólica esquerda\n\nVermelho- Aa. Sigmóideas\n\nVerde- A. Retal superior\n\nRosa- V. Mesentérica inferior",
    "frontImage": "tgi-prova-normal/723c50d0-6257-147c-83b6-a1077eeb5434.jpg",
    "backImage": null,
    "order": 10
  },
  {
    "id": "tgi-prova-normal:faa09aa1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura? e qual a patologia associada?",
    "a": "Recesso subfrênico- Acumulo de ar no abdômen, Pneumoperitônio\n\nOBS- Recesso subfrênico direito é o ponto mais alto do abdômen",
    "frontImage": "tgi-prova-normal/ff13ee70-891c-11aa-b65c-eb0d0ce250c6.jpg",
    "backImage": null,
    "order": 11
  },
  {
    "id": "tgi-prova-normal:faa0c1b0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura circulada?",
    "a": "lig. triangular do fígado, fixa o fígado a porção posterior do abdomen e ao diafragma\n\nOBS- é a junção dos ligamentos coronários (anterior e posterior) na lateral do fígado",
    "frontImage": "tgi-prova-normal/857a21d0-8a73-11aa-b65c-eb0d0ce250c6.jpg",
    "backImage": null,
    "order": 12
  },
  {
    "id": "tgi-prova-normal:faa0c1b1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura? e qual a função associada?",
    "a": "Goteiras paracólicas\n\no escoamento de líquidos abdominais se dá por essas goteiras.\n\nA porção direita impede o escoamento até o reto por causa da raiz do mesentério\n\nA porção esquerda possui apenas o ligamento frenocólico para tentar barrar essa passagem",
    "frontImage": "tgi-prova-normal/c4e64170-8b6b-11aa-b65c-eb0d0ce250c6.png",
    "backImage": null,
    "order": 13
  },
  {
    "id": "tgi-prova-normal:faa0c1b2-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome das estruturas sinalizadas? são  envolvidos por qual estrutura?",
    "a": "Azul Superior: Veia porta (formada pela V. Mesentérica sup- à  esquerda na foto- e V. Esplênica- à direita na foto) \nVerde: Ducto colédoco\nVermelha: A. Hepática propria\n\nSao envolvidas pelo ligamento Hepatoduodenal\n(Tríade portal)",
    "frontImage": "tgi-prova-normal/8f98e8a0-8cbb-11aa-b65c-eb0d0ce250c6.jpg",
    "backImage": null,
    "order": 14
  },
  {
    "id": "tgi-prova-normal:faa0e8c0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais os ramos da Aorta abdomnial?",
    "a": "4 Anteriores:\nA. frênicas inferiores\nTronco celíaco\nA. Mesenterica sup\nA. Mesenterica inf\n\n3 Laterais:\nA. renais\nA. suprarrenais Médias\nA.Gonadais( A. Testicular nos homens e A. Ovárica nas mulheres)\n\n2 Posteriores:\nAa. Lombares \nA. Sacral mediana",
    "frontImage": null,
    "backImage": null,
    "order": 16
  },
  {
    "id": "tgi-prova-normal:faa0e8c1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "explique a circulação colateral caso a A. Mesenterica inf seja ligada",
    "a": "A. Mesenterica inf dá como ramo a A. colica esquerda e Aa. Sigmóideas que se anastomosam com a A. Cólica direita, a A. Cólica Média e a A. Ileocólica (ramos da A. Mesentérica sup) , formando o arco justacólico",
    "frontImage": null,
    "backImage": "tgi-prova-normal/59a5b7a0-7ce7-147c-83b6-a1077eeb5434.jpg",
    "order": 17
  },
  {
    "id": "tgi-prova-normal:faa0e8c2-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "por que uma dor no peritonio visceral próximo ao diafragma é relacionada como uma dor localizada ?",
    "a": "porque o peritonio visceral nessa porção nao é mais inervado por nervos autônomos e sim pelo nervo frênico que é somático\n\nOBS- N. Frênico (C3-C5)",
    "frontImage": null,
    "backImage": null,
    "order": 19
  },
  {
    "id": "tgi-prova-normal:faa10fd0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome das estruturas?",
    "a": "azul: A. Hepatica propria\nvermelho: Ducto colédoco\nverde: veia porta\n\nformam a tríade portal - Conteúdo do Lig. Hepatoduodenal",
    "frontImage": "tgi-prova-normal/5e280850-4f95-11ae-9dbb-89fe7c481a24.jpg",
    "backImage": null,
    "order": 20
  },
  {
    "id": "tgi-prova-normal:faa10fd1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome das estruturas?",
    "a": "Roxo: Tonsilas linguais\n\nVermelho: Prega Glossoepiglótica mediana\n\nAzul: Valécula\n\nVerde: Pregas Glossoepigloticas Laterais\n\nPreto: Cartilagem epiglote",
    "frontImage": "tgi-prova-normal/fe27a830-4f70-11ae-9dbb-89fe7c481a24.jpg",
    "backImage": null,
    "order": 21
  },
  {
    "id": "tgi-prova-normal:faa10fd2-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a formação da veia porta?",
    "a": "•V. Mesenterica Sup \n•V. Esplênica (recebe a V. Mesentérica inf)\n\nOBS- se forma posterior à cabeça do pâncreas",
    "frontImage": null,
    "backImage": null,
    "order": 22
  },
  {
    "id": "tgi-prova-normal:faa136e0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura?",
    "a": "processo papilar do lobo caudado do fígado",
    "frontImage": "tgi-prova-normal/a1a9ebf0-5539-11ac-8827-1f60a763c933.jpg",
    "backImage": null,
    "order": 23
  },
  {
    "id": "tgi-prova-normal:faa136e1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura?",
    "a": "processo caudado do lobo caudado do fígado",
    "frontImage": "tgi-prova-normal/fbf0d070-5560-11ac-8827-1f60a763c933.jpg",
    "backImage": null,
    "order": 24
  },
  {
    "id": "tgi-prova-normal:faa15df0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais os ramos da A. Mesenterica Sup?",
    "a": "São 6 ramos\n\nCONVEXIDADE-\n• para o intestino delgado:\nAa. ileais (íleo)\nAa.Jejunais(jejuno)\n\nCONCAVIDADE-\n•Para o Duodeno+ pâncreas\nA. Pancreáticaduodenal inf (se divide em anterior e posterior)\n• para o Intestino Grosso:\nA. Cólica Média (colo transverso proximal)\nA. Cólica direita (colo ascendente)\nA. ileocólica- Dá o ramo apendicular para o apêndice (Ceco e apêndice)",
    "frontImage": null,
    "backImage": "tgi-prova-normal/b1beb510-e7f7-13d2-956a-41bdeb6f8f37.jpg",
    "order": 25
  },
  {
    "id": "tgi-prova-normal:faa15df1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura?",
    "a": "esôfago cervical",
    "frontImage": "tgi-prova-normal/4f341720-eccc-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "order": 26
  },
  {
    "id": "tgi-prova-normal:faa15df2-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura? qual a nota anatomoclínica do local?",
    "a": "recesso piriforme. \nEstá relacionado com a comida que se deposita nesse local quando há engasgo",
    "frontImage": "tgi-prova-normal/e1c29ca0-eceb-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "order": 27
  },
  {
    "id": "tgi-prova-normal:faa18500-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais as estruturas marcadas?",
    "a": "vermelho- 2º segmento do fígado\n\nazul escuro- 3º segmento do fígado\n\nverde escuro-4º A segmento do fígado\n\nverde claro-4º B segmento do fígado\n\nlaranja-5º segmento do fígado\n\nazul claro-6º segmento do fígado\n\nbranco- 7º segmento do fígado\n\nroxo- 8º segmento do fígado\n\nOBS- O primeiro segmento do fígado é posterior",
    "frontImage": "tgi-prova-normal/5204c6b0-8de8-1395-ba4d-adf186572cef.jpg",
    "backImage": null,
    "order": 28
  },
  {
    "id": "tgi-prova-normal:faa18501-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura?",
    "a": "A. Cística (Ramo da A. Hepática direita)\n\n•Conteúdo do Trígono de Calot",
    "frontImage": "tgi-prova-normal/5cc31110-edf9-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "order": 29
  },
  {
    "id": "tgi-prova-normal:faa18502-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o nome da estrutura?",
    "a": "papila duodenal maior\n\n(Local que a Ampola hepatopancreática desemboca// 2ª porção do duodeno- Descendente)\n\nOBS- Papila duodenal menor não dá pra ver na maioria das peças do laboratório",
    "frontImage": "tgi-prova-normal/94e5a630-f389-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "order": 31
  },
  {
    "id": "tgi-prova-normal:faa1d320-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o conteúdo dessas estruturas?",
    "a": "Prega umbilical mediana- úraco  obliterado\n\nPrega umbilical medial- arteria umbilical obliterada\n\nPrega umbilical lateral- Vasos epigástricos inferiores",
    "frontImage": "tgi-prova-normal/a6cbe8f0-14a1-11c0-9c62-ffcaf112b942.jpg",
    "backImage": null,
    "order": 32
  },
  {
    "id": "tgi-prova-normal:faa1d321-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais os ramos do tronco celíaco?",
    "a": "A. Hepática Comum\nA. Gástrica Esq\nA. Esplênica",
    "frontImage": null,
    "backImage": null,
    "order": 33
  },
  {
    "id": "tgi-prova-normal:faa1d322-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "limites e conteúdo do trígono de calot?",
    "a": "lateral- Ducto cístico\nmedial- ducto hepático comum\nsuperior- face inferior do fígado\n\nConteúdo: A. Cística",
    "frontImage": null,
    "backImage": "tgi-prova-normal/46beb6e0-6f23-147c-83b6-a1077eeb5434.jpg",
    "order": 34
  },
  {
    "id": "tgi-prova-normal:faa1fa30-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o conteúdo do ligamento redondo do fígado?",
    "a": "V. Umbilical obliterada\n\n+Vv. Paraumbilicais",
    "frontImage": null,
    "backImage": null,
    "order": 37
  },
  {
    "id": "tgi-prova-normal:faa1fa31-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a inervação das vísceras abdominais?",
    "a": "Parassimpático- N. Vago\nSimpático- Nn. Esplâncnicos (maior, menor, imo e sacrais)",
    "frontImage": null,
    "backImage": null,
    "order": 49
  },
  {
    "id": "tgi-prova-normal:faa1fa32-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual é a síndrome de quebra nozes?",
    "a": "É a compressão da V. Renal esquerda ao passar entre a Aorta abdominal e A. Mensetérica sup\n\nOBS- a V. Renal esquerda recebe a V. Gonadal esq e a V. suprarrenal esq\n(diferente da V. Renal direita que não recebe )",
    "frontImage": null,
    "backImage": null,
    "order": 54
  },
  {
    "id": "tgi-prova-normal:faa22140-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais os ramos da A. Hepática Comum e os ramos dos seus ramos?",
    "a": "•A. Gastroduodenal:\nA. Gastromental direita\nA. Pancreatica duodenal Sup (anterior e posterior)\n\n\n•A. Hepática Própria;\nA. Hepática Direita\n(A. Cística)\nA. Hepática esquerda\nA. Gástrica direita",
    "frontImage": null,
    "backImage": null,
    "order": 59
  },
  {
    "id": "tgi-prova-normal:faa22141-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "defina o conteúdo  da Tríade portal",
    "a": "Posterior- V. Porta (posterior)\nLateral- Ducto colédoco\nMedial- A. Hepática própria",
    "frontImage": null,
    "backImage": null,
    "order": 68
  },
  {
    "id": "tgi-prova-normal:faa22142-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "o que o ângulo de treitz define?",
    "a": "a flexura duodenojejunal",
    "frontImage": null,
    "backImage": null,
    "order": 69
  },
  {
    "id": "tgi-prova-normal:faa24850-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "o que são as papilas duodenais?",
    "a": "Papila duodenal maior- abertura da ampola hepatopancreática\n\nPapila duodenal menor- Ducto pancreático acessório (as vezes nem existe)",
    "frontImage": null,
    "backImage": null,
    "order": 71
  },
  {
    "id": "tgi-prova-normal:faa24851-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "defina o arco justacólico",
    "a": "também chamado de A. Marginal de Drummond \n\nIRRIGA O INTESTINO GROSSO:\n\nAnastomose entre:\nA. Mesentérica sup-\n•A. Cólica direita\n•A. Cólica média\nA. Mesentérica inf-\n• A.Cólica esquerda\n•Aa. Sigmóideas",
    "frontImage": null,
    "backImage": "tgi-prova-normal/8aeb6dd0-c07d-139b-a9ac-153b904cfbed.jpg",
    "order": 72
  },
  {
    "id": "tgi-prova-normal:faa26f60-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o conteúdo do Lig. Esplenorrenal? e do Lig. Gastroesplênico?",
    "a": "Lig. Esplenorrenal- Vasos. Esplênicos\n\nLig. Gastroesplênicos- Vasos gastromentais e Gástricos curtos",
    "frontImage": null,
    "backImage": null,
    "order": 74
  },
  {
    "id": "tgi-prova-normal:faa26f61-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a irrigação do intestino delgado?",
    "a": "•Duodeno-\nA. Gastroduodenal (A. Hepática Comum) \n\nA. Pancreática duodenal sup (anterior e posterior)\n- ramo da A. Gastromental\n\nA. Pancreatico duodenal inf (anterior e posterior)\n- Ramo da A. Mesentérica sup\n\n•Jejuno e Ileo\nArtérias jejunais e ileais \nramos da A. Mesentérica sup (arco jejunoileal)",
    "frontImage": null,
    "backImage": null,
    "order": 75
  },
  {
    "id": "tgi-prova-normal:faa26f62-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais os ramos da A. Esplênica?",
    "a": "5 ramos\n\nA. Gastromental esq\nAa. Gástricas curtas\nA. Pancreática Magna\nA. Pancreática dorsal\nA. da Cauda do Pâncreas\n\nOBS: as vezes ela dá a A. Gástrica posterior",
    "frontImage": null,
    "backImage": null,
    "order": 76
  },
  {
    "id": "tgi-prova-normal:faa29670-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "onde a papila duodenal maior se localiza?",
    "a": "localiza-se na 2ª porção do duodeno (descendente)\n\n\nOBS- Vasos mesentéricos superiores ultrapassam o duodeno na 3ª porção (porção horizontal)",
    "frontImage": null,
    "backImage": null,
    "order": 78
  },
  {
    "id": "tgi-prova-normal:faa29671-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual o lobo do fígado próximo à VCI e ao ligamento redondo do fígado? o que separa os lobos do fígado?",
    "a": "Próximo à VCI: \nLobo Caudado\nCava- caudado\n\nPróximo ao Lig. Redondo do fígado\nLobo Quadrado\nRedondo-Quadrado\n\nO que separa os lobos do fígado é a Fissura do Lig. Venoso( componente do H do Fígado)\n\nOBS- Lobos caudado e quadrado são do Lobo Direito",
    "frontImage": null,
    "backImage": "tgi-prova-normal/ce4d4860-fd6e-1399-a9ac-153b904cfbed.jpg",
    "order": 80
  },
  {
    "id": "tgi-prova-normal:faa29672-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual vaso pode ser lesado por uma corrosão da parede gástrica ?",
    "a": "A. Gastroduodenal que passa entre a primeira porção do duodeno e do canal pilórico",
    "frontImage": null,
    "backImage": null,
    "order": 81
  },
  {
    "id": "tgi-prova-normal:faa2bd80-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais as notas anatomoclínicas de cada parte do duodeno?",
    "a": "1ª porção- sai o Lig. Hepatoduodenal (tríade portal)\n\n2ª porção- possui a papila duodenal maior\n\n3ª porção- vasos mesentéricos superiores  passam anteriormente \n\n4ª porção- Local do Ângulo de Treitz- flexura duodenojejunal",
    "frontImage": null,
    "backImage": null,
    "order": 83
  },
  {
    "id": "tgi-prova-normal:faa2bd81-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura na pinça?",
    "a": "Vasos epigástricos inferiores\n\nOBS- estão na prega umbilical lateral",
    "frontImage": "tgi-prova-normal/ad19bcd0-82d9-139c-8cda-396e1cd69515.jpg",
    "backImage": null,
    "order": 86
  },
  {
    "id": "tgi-prova-normal:faa2bd82-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual marco de transição do andar supracólico para o infracólico?",
    "a": "Colo transverso",
    "frontImage": null,
    "backImage": null,
    "order": 88
  },
  {
    "id": "tgi-prova-normal:faa2e490-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais as estruturas apontadas?",
    "a": "azul- prega umbilical medial (A. Umbilical obliterada)\n\nvermelho- vasos epigástricos inferiores\n(na prega umbilical lateral)",
    "frontImage": "tgi-prova-normal/e42bd700-9b73-13a6-84ff-e59428de54e7.jpg",
    "backImage": null,
    "order": 91
  },
  {
    "id": "tgi-prova-normal:faa2e491-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura apresentada?",
    "a": "haustração cólica",
    "frontImage": "tgi-prova-normal/811658b0-ed84-13a8-9245-e1d016fcd73e.jpg",
    "backImage": null,
    "order": 94
  },
  {
    "id": "tgi-prova-normal:faa30ba0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura apontada pela ponta da pinça?",
    "a": "V. Mesentérica inf (passa ao lado da flexura duodenojejunal",
    "frontImage": "tgi-prova-normal/13a7d720-ed72-13a8-9245-e1d016fcd73e.jpg",
    "backImage": null,
    "order": 95
  },
  {
    "id": "tgi-prova-normal:faa332b0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais ligamentos formam os omentos?",
    "a": "omento menor: \nLig. Hepatoduodenal \nLig. Hepatogástrico\n\nomento maior:\nLig. Gastroesplênico (principal)\nLig. Gastrofrênico\nLig. Gastrocólico",
    "frontImage": null,
    "backImage": null,
    "order": 97
  },
  {
    "id": "tgi-prova-normal:faa332b1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a irrigação do ceco?",
    "a": "A. ileocólica",
    "frontImage": null,
    "backImage": null,
    "order": 99
  },
  {
    "id": "tgi-prova-normal:faa332b2-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura apontada em azul escuro?",
    "a": "V. Mesentérica inf \n\nOBS- tributa na V. Esplênica",
    "frontImage": "tgi-prova-normal/56bafe30-2d0a-13bc-a2ad-db955403c929.jpg",
    "backImage": null,
    "order": 101
  },
  {
    "id": "tgi-prova-normal:faa359c0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a inervação do peritônio?",
    "a": "peritônio parietal- Nn. Intercostais de T7-L1\n\nPetitônio visceral- Nn. aferentes autonômicos (N. Vago+ Nn. Toracoadbominais)",
    "frontImage": null,
    "backImage": null,
    "order": 109
  },
  {
    "id": "tgi-prova-normal:faa359c1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais as funções do peritônio?",
    "a": "•movimento das vísceras\n\n•local de trânsito de vasos e nervos\n\n•absorção \n\n•proteção\n\n•armazenamento de gordura\n\n•hemodiálise \n\n•via de administração de medicamentos",
    "frontImage": null,
    "backImage": null,
    "order": 110
  },
  {
    "id": "tgi-prova-normal:faa359c2-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais os únicos colos que podem sofrer torção? (volvo)",
    "a": "Colo transverso\nColo Sigmóide\n\npois são peritonizados// livres na cavidade abdominal\n\nOBS- Volvo de sigmóide- sinal de grão de café na radiografia",
    "frontImage": null,
    "backImage": null,
    "order": 111
  },
  {
    "id": "tgi-prova-normal:faa380d0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais as estruturas apontadas pelo ponto preto e azul claro inferior?",
    "a": "Ponto preto- A. Cólica direita\n\nponto azul claro- A. Ileocólica",
    "frontImage": "tgi-prova-normal/23c03f80-a8df-13d0-8de0-5188da034ea2.jpg",
    "backImage": null,
    "order": 112
  },
  {
    "id": "tgi-prova-normal:faa380d1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais as estruturas apontadas?",
    "a": "laranja- A. Pancreaticaduodenal superior\n\nazul- A. Gastromental direita\n\nbranco/ pinça- A. Gastroduodenal",
    "frontImage": "tgi-prova-normal/e12eb2b0-1f34-13d1-946f-7f5a320575e5.jpg",
    "backImage": null,
    "order": 115
  },
  {
    "id": "tgi-prova-normal:faa380d2-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura apontada pela pinça?",
    "a": "pinça- A. Sacral mediana",
    "frontImage": "tgi-prova-normal/01fbafa0-23b5-13d1-946f-7f5a320575e5.jpg",
    "backImage": null,
    "order": 116
  },
  {
    "id": "tgi-prova-normal:faa3a7e0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais as estruturas apontadas?",
    "a": "Rosa- A. Esplênica\n\nlaranja- A. Pancreática dorsal (sao varios ramos) \n\namarelo- A. Da cauda do pâncreas",
    "frontImage": "tgi-prova-normal/b2c9bef0-857d-147c-83b6-a1077eeb5434.jpg",
    "backImage": null,
    "order": 117
  },
  {
    "id": "tgi-prova-normal:faa3a7e1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura apontada pelo dedo?",
    "a": "A. Esplênica (ramo direto do tronco celíaco)",
    "frontImage": "tgi-prova-normal/847165c0-e94b-13d3-a719-0dcaa380b7be.jpg",
    "backImage": null,
    "order": 119
  },
  {
    "id": "tgi-prova-normal:faa3a7e2-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura apontada pelos alfinetes pretos??",
    "a": "Esquerda- A. Hepática comum (ramo direto do tronco celíaco)\n\nDireita- A. Hepática própria (ramo da A. Hepática comum)",
    "frontImage": "tgi-prova-normal/763384c0-e419-13d3-a719-0dcaa380b7be.jpg",
    "backImage": null,
    "order": 120
  },
  {
    "id": "tgi-prova-normal:faa3cef0-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a relação de lateralidade dos vasos mesentéricos superiores com o pâncreas?",
    "a": "•Os vasos são anteriores ao colo do pâncreas\n\n•Os vasos são posteriores ao processo uncinado",
    "frontImage": null,
    "backImage": "tgi-prova-normal/cea14db0-72c1-147c-83b6-a1077eeb5434.jpg",
    "order": 127
  },
  {
    "id": "tgi-prova-normal:faa3cef1-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a relação de lateralidade dos vasos mesentéricos superiores com o duodeno?",
    "a": "eles passam anteriormente à 3ª porção do duodeno (porção horizontal)",
    "frontImage": null,
    "backImage": "tgi-prova-normal/a55f3b60-7546-147c-83b6-a1077eeb5434.jpg",
    "order": 128
  },
  {
    "id": "tgi-prova-normal:faa3f600-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais as partes da vesícula?",
    "a": "colo, corpo, fundo e infundíbulo",
    "frontImage": null,
    "backImage": "tgi-prova-normal/38938350-a143-147c-83b6-a1077eeb5434.jpg",
    "order": 129
  },
  {
    "id": "tgi-prova-normal:faa3f601-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura apontada?",
    "a": "Processo uncinado do pâncreas\n\nOBS- Está na cabeça do pâncreas",
    "frontImage": "tgi-prova-normal/d960f360-8a89-147c-83b6-a1077eeb5434.jpg",
    "backImage": null,
    "order": 130
  },
  {
    "id": "tgi-prova-normal:faa3f602-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "quais as estruturas apontadas?",
    "a": "amarelo- curvatura maior do estômago\n\nvermelho- Incisura angular\n\nazul- Incisura cárdica\n\nbranco- Piloro (gabarito foi dado como esse na prova)",
    "frontImage": "tgi-prova-normal/957b4f00-8c01-147c-83b6-a1077eeb5434.jpg",
    "backImage": null,
    "order": 131
  },
  {
    "id": "tgi-prova-normal:faa41d10-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura apontada?",
    "a": "M. Genioglosso",
    "frontImage": "tgi-prova-normal/634d7920-8fd7-147c-83b6-a1077eeb5434.jpg",
    "backImage": null,
    "order": 132
  },
  {
    "id": "tgi-prova-normal:faa41d11-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura apontada?",
    "a": "apêndice vermiforme",
    "frontImage": "tgi-prova-normal/a3380d40-902f-147c-83b6-a1077eeb5434.jpg",
    "backImage": null,
    "order": 133
  },
  {
    "id": "tgi-prova-normal:faa41d12-3707-1815-aca6-0d3252dc11d2",
    "deckSlug": "tgi-prova-normal",
    "cat": 17,
    "src": "📥 TGI - Prova normal",
    "b": "b-ufc",
    "q": "qual a estrutura apontada?",
    "a": "infundíbulo da vesícula biliar",
    "frontImage": "tgi-prova-normal/015133a0-9050-147c-83b6-a1077eeb5434.jpg",
    "backImage": null,
    "order": 134
  }
];
