window.CABECA_PESCOCO_IMPORTED_FLASHCARDS = [
  {
    "id": "cp-11-0001",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que o N. Facial inerva na cabeça e pescoço?",
    "a": "Musculos da Mímica Facial\nM. Platisma( ramo cervical)\nM. Estapédio\nM. Estilo hióide\nVentre post do M. \nDigástrico\n\nTodas as glândulas exceto a Parótida\n\nsensibilidade gustativa de 2/3 anteriores da língua",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 0
  },
  {
    "id": "cp-11-0002",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do Mm. Infra-hióides?",
    "a": "M.EsternoHióide\nM. Esternotireóide\nM.Tireohióide  (C1)\nM. Omohióide\n\nInervados pela alça cervical\n\nEXCETO O M. Tireohióide (inervado por C1- via hipoglosso)\n\nAlça Cervical: C1,C2 e C3\nporção sup: C1 e C2\nPorção inf: C2 e C3",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 1
  },
  {
    "id": "cp-11-0003",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação dos Mm. Supra-hióides?",
    "a": "M. Geniohióide- C1 (fibras levados pelo Hipoglosso)\n\nM. Milohióide- N. para o músculo milo hióide\n (Ramo de V3)\n\nM. Digástrico- Ventre ant: N. Para o M. Milohióide (ramo de V3)\nVentre post: N. para o M. Digastrico (N. Facial)\n\nM. Estilohióide- N. Para o M. Estilohióide (N. Facial",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 2
  },
  {
    "id": "cp-11-0004",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação da laringe?",
    "a": "N. Laringeo recorrente inerva os musculos intrínsecos (EXCETO O M. CRICOTIREOIDEO\n e sensitivamente 1/3 inferior\n\nN. Laringeo superior da os ramos Ext e Int\n\nRamo Int- porção sensitiva 2/3 superiores da laringe\n\nRamo Ext- M. Cricotireóideo \n\nOBS- Ramo ext  inerva parassimpaticamente a tireóide",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 3
  },
  {
    "id": "cp-11-0005",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do tronco tireocervical?",
    "a": "3  ramos\n\nA. Tireoidea inferior (origina a A. Cervical Ascendente)\nA. Supraescapular\nA. Cervical Transversa",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 4
  },
  {
    "id": "cp-11-0006",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do tronco costocervical?",
    "a": "A. Cervical Profunda \nA. Intercostal suprema",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 5
  },
  {
    "id": "cp-11-0007",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quantos trígonos existem no pescoço?",
    "a": "8 trígonos:\n-4 anteriores\n-3 laterais\n-1 posterior\n\n•Anteriores:\nTrígono Submentual\nTrígono Submandibular\nTrígono Muscular\nTrígono Carótico\n\n•Laterais:\nTrígono Omoclavicular\nFossa supraclavicular menor \nTrígono Occipital\n\n•Posterior:\nTrígono Suboccipital",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 6
  },
  {
    "id": "cp-11-0008",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono submandibular?",
    "a": "Limites:\n\nVentres do M. Digástrico e Margem Inf da Mandíbula\nassoalho-M. Milohióide\n\nConteúdo:\nGlândula submandibular\nN. Hipoglosso\n Vasos faciais\nN. Para o M. Milo hióide",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/9fbbf8e0-e7e0-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 7
  },
  {
    "id": "cp-11-0009",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono submentual?",
    "a": "Limites:\n\ninf: Corpo do Osso Hióide \nLateral: Ventres anteriores do M. Digástrico esq e dir\nassoalho: M.Milohióide\n\nConteúdo:\npequenas veias que formam a Jugular anterior\nLinfonodos submentuais",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/8619f710-e9ee-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 8
  },
  {
    "id": "cp-11-0010",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono carótico?",
    "a": "Limites:\n\nLateral- Margem anterior do M. ECM\nMedial- Ventra sup do M. Omo-hióide\nSuperior- Ventre Post do M. Digástrico\n\n\nConteúdo-\nA. Carótida Comum\nV. Jugular Interna\nN. Vago\nSaio Carotídeo\nCIRCUNDADOS PELA BAINHA CARÓTICA\n+N. Hipoglosso\n+N. Acessório\n+Faringe e laringe",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/49eb89b0-ea1c-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 9
  },
  {
    "id": "cp-11-0011",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono muscular?",
    "a": "Limites:\n\nSuperior- Ventre sup do\n M. Omohióide\nLateral-Borda anterior do \nM. ECM\nMedial- Plano mediano do pescoço \n\nConteúdo:\nM. Esternohióide\nM. Esternotireóide\nGlândula Tireoide\nGlândula ParaTireoide",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/f69b0250-ee3e-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 10
  },
  {
    "id": "cp-11-0012",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono omoclavicular?",
    "a": "Limites:\n\nInf- Clavícula\nSup- ventre inf do M. Omohióide\nMedial: Borda Post do \nM. ECM\n\n\nConteúdo:\n3ª Parte da A. Subclávia\nA. Supraescapular",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/97f8c4a0-50be-135c-a54c-991bc20cfc86.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 11
  },
  {
    "id": "cp-11-0013",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono Occipital?",
    "a": "Limites:\n\nLateral- Borda Anterior do M. Trapézio\nInf- Ventre Inf do\n M. Omohióide\nMedial- Borda Post do\n M. ECM\n\nConteúdo:\ntroncos do plexo braquial, N. Acessório, A. Cervical transversa",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/3fd85da0-f182-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 12
  },
  {
    "id": "cp-11-0014",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono Suboccipital?",
    "a": "Limites:\n\nInf-M. Oblíquo Inf da Cabeça\nLateral-M. Oblíquo sup da Cabeça\nSuperior- M. Reto Post Maior da Cabeça\n\n\nConteúdo:\nA. Vertebral \nN. Suboccipital ( Ramo Post de C1- INERVA OS OBLÍQUOS E OS RETOS DA CABEÇA)",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/3eb71450-f3e1-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 13
  },
  {
    "id": "cp-11-0015",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono de Guyon?",
    "a": "Limites:\n\nV. Jugular Interna\nTronco tireolinguofacial\nVentre Post do M.\n Digástrico\n\nConteúdo:\nBifurcação da Carótida e N. Hipoglosso",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/86095510-ffc2-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 14
  },
  {
    "id": "cp-11-0016",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono de farabeuf?",
    "a": "V. Jugular interna\nTronco Tireolinguofacial\nN. Hipoglosso\n\nConteúdo: Bifurcação da A. Carótida Comum\n\nImportância- Ponto de referência cirúrgica",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/b0854a20-ffb2-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 15
  },
  {
    "id": "cp-11-0017",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é o tronco tireolinguofacial?",
    "a": "Junção de veias que vão tributar juntas na jugular interna:\n\nV. Facial\nV. Lingual\nV. Tireoidea sup",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 16
  },
  {
    "id": "cp-11-0018",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é e por que é perigoso tomar uma pancada no Ptério?",
    "a": "ptério é a área de encontro de 4 ossos:\nOsso Temporal\nOsso Frontal\nOsso Parietal\nOsso esfenóide\n\nPerigoso, porque é por onde passa ramo principal da A. Meningea Média, ramo frontal. O impacto pode causar uma lesão e, consequentemente, um hematoma Epidural/ Extradural",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/ed32a040-41f2-1313-822e-e5e73d524eff.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 17
  },
  {
    "id": "cp-11-0019",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos supra hióideos? qual a ação?",
    "a": "são 4 músculos com a função de abaixar a mandíbula\n\nM. Digástrico(2 ventres)\nM. Estilo- Hióide\nM. Genio hióide\nM.Milo Hióide",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 18
  },
  {
    "id": "cp-11-0020",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da tireóide? e a drenagem?",
    "a": "A. tireóidea sup (ramo da A. Carótida Ext)\n\nA. Tireóidea inf (ramo do Tronco tireocervical )\n\n\nDRENAGEM VENOSA:\nV. Tireóidea sup\nV. Tireóidea média\ndrenam para a V. Jugular interna\n\nV. tireóidea inf \ndrenam para a V. braquiocefálica",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 19
  },
  {
    "id": "cp-11-0021",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação das paratireóides?",
    "a": "Aa. Tireóideas inferiores, apenas",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 20
  },
  {
    "id": "cp-11-0022",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "A. Auricular posterior",
    "frontImage": "cabeca-pescoco-monitoria/c97663a0-3f14-1347-9031-0556ba2a088d.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 21
  },
  {
    "id": "cp-11-0023",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apresentada?",
    "a": "N. Laringeo recorrente esquerdo\n\npercorre o espaço traqueoesofágico",
    "frontImage": "cabeca-pescoco-monitoria/248421e0-4ea3-1347-9031-0556ba2a088d.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 22
  },
  {
    "id": "cp-11-0024",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Carótida externa?",
    "a": "anteriores: 4 ramos\n•A. Tireóidea sup\n•A. Lingual\n•A. Facial\n•A. Maxilar\n\nPosteriores: 2 ramos\nA. Occipital (sai no nível da A. Facial)\nA. Auricular post\n\nMedial: 1 ramo\nA. Faríngea ascendente\n\n\nSuperior: 1 ramo\nA. Temporal superficial \n(sai pra cima)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 23
  },
  {
    "id": "cp-11-0025",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação dos músculos escalenos?",
    "a": "anterior- C5-C8\nmédio-C3-C7\nposterior-C5-C8",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 24
  },
  {
    "id": "cp-11-0026",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo da fossa supraclavicular menor?",
    "a": "•Limites:\norigens do M. ECM (esternal e clavicular)+ Clavícula\n\n•Conteúdo:\nV. Jugular interna\n(local de acesso venoso central )",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/6f1f50f0-547c-135c-a54c-991bc20cfc86.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 25
  },
  {
    "id": "cp-11-0027",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação da V. Jugular externa e para onde ela drena?",
    "a": "V. Retromandibular\nV. Auricular posterior\n\ndrenam para a V. Subclávia\n(passam anteriormente ao ECM- ligadas a turgência jugular)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 26
  },
  {
    "id": "cp-11-0028",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação e para onde V. Jugular anterior drena?",
    "a": "Vv. submandibulares superficiais e drena para a V. Jugular EXTERNA",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 27
  },
  {
    "id": "cp-11-0029",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação da V. Jugular interna?",
    "a": "Seio sigmóide e Seio pretroso inferior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 28
  },
  {
    "id": "cp-11-0030",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo da bainha carótidea e sua lateralidade?",
    "a": "N. Vago posterior\nArtéria carótida medial\nV. Jugular interna lateral",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 29
  },
  {
    "id": "cp-11-0031",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do plexo cervical e qual a formação?",
    "a": "C1 - C4\n\nN. Cervical transverso\nN. Auricular Magno\nN. Occipital menor\nNn. Supraclaviculares",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/2b7e38d0-15df-1369-9bc8-a72790f82d72.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 30
  },
  {
    "id": "cp-11-0032",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do glomo e seios carotídeos? e aórticos?",
    "a": "carotídeos:\nN. Glossofaríngeo\n\nAórtico:\nN. Vago",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 31
  },
  {
    "id": "cp-11-0033",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da laringe?",
    "a": "Aa. Laringeas superiores e inferiores ramos das Aa. Tireóideas superiores e inferiores\n\nDrenagem:\nV. Laringea superior- V. Jugular interna\n\nV. laringea inf- V. Tireóidea inf",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/d6108da0-6698-135c-a54c-991bc20cfc86.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 32
  },
  {
    "id": "cp-11-0034",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação da faringe?",
    "a": "Plexo faríngeo do N. Vago\npara todos os músculos, exceto;\n\n M. Estilofaríngeo- N. Glossofaríngeo",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/b6e3e190-66aa-135c-a54c-991bc20cfc86.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 33
  },
  {
    "id": "cp-11-0035",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação da sensibilidade da face? por onde esses nervos emergem?",
    "a": "Trigêmeo:\nV1- Fissura orbital sup\n(dorso do nariz até galea aponeurótica)\n\nV2- Forame redondo\n(maxilas e dentes maxilares)\n\nV3- Forame oval\n(dentes inferiores e mandíbula)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 34
  },
  {
    "id": "cp-11-0036",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos da mastigação e sua inervação?",
    "a": "M. Temporal\nM. Masseter\nM. Pterigóideos (medial e lateral)\n\nTodos inervados por V3",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 35
  },
  {
    "id": "cp-11-0037",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é o trígono perigoso da face?",
    "a": "anastomose entre a V. Oftálmica superior (tributa no seio cavernoso) com a V. Angular.\n\nEssa anastomose pode levar bactérias para a circulação encefálica\n\nOBS- Há um vídeo no instagram da monitoria sobre o assunto (02/06/2025)",
    "frontImage": null,
    "backImage": "cabeca-pescoco-monitoria/fded0e80-698f-135c-a54c-991bc20cfc86.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 36
  },
  {
    "id": "cp-11-0038",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação da glândula parótida?",
    "a": "N. Glossofaríngeo encaminha fibras nervosas pelo N. Auriculotemporal (que inerva sensitivamente)\n\nApesar de passar o plexo parotídeo do N. Facial, ele nn inerva\n\nOBS- Localizada anterior ao masseter, seu ducto fura o M. Bucinador e desemboca no 2º molar superior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 37
  },
  {
    "id": "cp-11-0039",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "canal condilar (inconstante)\n\nconteúdo:\nVV. Emissárias \nA. Meníngea posterior",
    "frontImage": "cabeca-pescoco-monitoria/95f6c700-6df2-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 38
  },
  {
    "id": "cp-11-0040",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "forame estilomastóideo\n\nconteúdo: N. Facial",
    "frontImage": "cabeca-pescoco-monitoria/d6bd7010-7007-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 39
  },
  {
    "id": "cp-11-0041",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "forame jugular\n\n\nconteúdo: 9º,10° e 11º NC+ \nV. Jugular int + A. Meníngea posterior+ Seio petroso inf e Seio Sigmóide",
    "frontImage": "cabeca-pescoco-monitoria/ab0bf4b0-7079-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 40
  },
  {
    "id": "cp-11-0042",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "fossa incisiva \n\nConteúdo;  N. Nasopalatino e Anastomose da  A. Palatina maior e A. Esfenopalatina \n\nOBS- as duas artérias irrigam o nariz",
    "frontImage": "cabeca-pescoco-monitoria/618fffd0-71c2-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 41
  },
  {
    "id": "cp-11-0043",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "Forame Palatino menor\n\nVasos e N. Palatinos menores",
    "frontImage": "cabeca-pescoco-monitoria/055b0d10-7242-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 42
  },
  {
    "id": "cp-11-0044",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "Forame palatino maior\n\nConteúdo: Vasos e N. Palatino Maior",
    "frontImage": "cabeca-pescoco-monitoria/d9f68c20-72a6-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 43
  },
  {
    "id": "cp-11-0045",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "canal carotídeo\n\nconteúdo: A. Carótida Int",
    "frontImage": "cabeca-pescoco-monitoria/bfbd61e0-72dc-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 44
  },
  {
    "id": "cp-11-0046",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "forame lacerado\n\nConteúdo: \n\nN. Petroso maior // Sem conteúdo e tampado",
    "frontImage": "cabeca-pescoco-monitoria/d36f9b30-7355-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 45
  },
  {
    "id": "cp-11-0047",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "forame espinhoso\n\nConteúdo: Vasos Meníngeos médios + ramos meníngeos do trigêmeo (V3 principalmente)",
    "frontImage": "cabeca-pescoco-monitoria/5f54ef40-73b7-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 46
  },
  {
    "id": "cp-11-0048",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome das estruturas em azul?",
    "a": "Bregma (ponto de encontro das suturas parietais e sagital)\n\nLambda (ponto de encontro das suturas lambdóideas com a sagital)",
    "frontImage": "cabeca-pescoco-monitoria/82fa8bc0-7412-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 47
  },
  {
    "id": "cp-11-0049",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "Forame oval\n\nConteúdo: V3, A. Meníngea Acessória e N. Petroso menor",
    "frontImage": "cabeca-pescoco-monitoria/13cef2d0-74ae-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 48
  },
  {
    "id": "cp-11-0050",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo da fissura orbital superior?",
    "a": "3º NC, 4º NC, V1, 6º NC, V. Oftálmica superior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 49
  },
  {
    "id": "cp-11-0051",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo dos forames etmoidais anteriores e posteriores?",
    "a": "Vasos e Nervos com o mesmo nome",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 50
  },
  {
    "id": "cp-11-0052",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do forame redondo?",
    "a": "V2",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 51
  },
  {
    "id": "cp-11-0053",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do forame da mandíbula?",
    "a": "Vasos e N. Alveolar inferior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 52
  },
  {
    "id": "cp-11-0054",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo dos forames supraorbital, infraorbital e Mentual?",
    "a": "Vasos e Nervos do mesmo nome",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 53
  },
  {
    "id": "cp-11-0055",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo da fissura orbital inferior ?",
    "a": "V. Oftálmica inf",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 54
  },
  {
    "id": "cp-11-0056",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os círculos marcados?",
    "a": "verde- Astério\n(junção dos ossos occipital, parietal e temporal)\n\nVermelho- Ptério\n(junção dos ossos Frontal, esfenoide, parietal e temporal)",
    "frontImage": "cabeca-pescoco-monitoria/ddeec480-f2af-135c-b0ea-9d9be027019e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 55
  },
  {
    "id": "cp-11-0057",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada? e qual sua inervação ?",
    "a": "Gânglio cervical superior- inerva simpaticamente a cabeça e pescoço",
    "frontImage": "cabeca-pescoco-monitoria/e37d1db0-f3fa-135c-b0ea-9d9be027019e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 56
  },
  {
    "id": "cp-11-0058",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do Canal óptico?",
    "a": "A. Oftálmica\nN. Óptico (vasos centrais da retina dentro)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 57
  },
  {
    "id": "cp-11-0059",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação e a inervação do N. Frênico?",
    "a": "C3,C4 e C5\n\nPassa anterior ao M. Escaleno anterior e anterior ao hilo pulmonar",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 58
  },
  {
    "id": "cp-11-0060",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina toda a irrigação do couro cabeludo",
    "a": "5 artérias\n\nA. Carótida externa da 3 desses ramos :\n\nA. Temporal superficial\nA. Auricular post  \nA. Occipital\n\nA. Oftálmica dá 2 desses ramos:\n\nA. supraorbital\nA. Supratroclear",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 59
  },
  {
    "id": "cp-11-0061",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do meato acústico interno?",
    "a": "N. Facial\nN. Vestibulococlear \nA. do Labirinto (Ramo da A. Basilar)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 60
  },
  {
    "id": "cp-11-0062",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "M. Estilo hióide\n\n(posterior em relação ao Ventre post do Digástrico)",
    "frontImage": "cabeca-pescoco-monitoria/f65a40c0-144b-1369-9bc8-a72790f82d72.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 61
  },
  {
    "id": "cp-11-0063",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "plexo parotídeo- 2 TRONCOS\n\n\nTronco Temporofacial\n\nverde- R. Temporal\nazul- R. Zigomático\n\nAmarelo- R. Bucal( FORMADO PELOS DOIS TRONCOS)\n\nTronco Cervicofacial\n\nVermelho- R. Marginal da \nmandíbula\nOBS- Ramo cervical é desse tronco, mas não está na figura",
    "frontImage": "cabeca-pescoco-monitoria/1a707b50-1555-1369-9bc8-a72790f82d72.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 62
  },
  {
    "id": "cp-11-0064",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do seio cavernoso?",
    "a": "Veias oftálmicas (superior e inferior) \nV. Cerebral Média superficial\nSeio esfenoparietal\n\n\nOBS- O SEIO PETROSO INFERIOR CONECTA O CAVERNOSO À JUGULAR INTERNA",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 63
  },
  {
    "id": "cp-11-0065",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "vermelho- A. Facial (tortuosa e ramo da A. Carótida Externa)\n\nazul-V. Facial (continua como V. Angular e partipa da anastomose com a V. Supratroclear para o seio cavernoso)\n\nverde-Ducto parotídeo (anterior ao M. Masseter e fura o M. Bucinador no 2º molar superior)",
    "frontImage": "cabeca-pescoco-monitoria/36018f10-3cce-136b-9780-b10ab99f5338.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 64
  },
  {
    "id": "cp-11-0066",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apresentadas?",
    "a": "verde- A. Alveolar inf\nazul-A. Maxilar\nbranco- A. Meníngea média",
    "frontImage": "cabeca-pescoco-monitoria/8bac7fb0-fe4f-136e-96da-1bf036096190.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 65
  },
  {
    "id": "cp-11-0067",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "Plexo parotídeo:\n\nTronco temporofacial\namarelo- N. Temporal \nazul- N. Zigomático\n\n\nverde- N. Bucal(formado pelos dois troncos)\n\nTronco Cervicofacial\n\n+ N. Marginal da mandíbula\nN. Cervical",
    "frontImage": "cabeca-pescoco-monitoria/c2211840-637a-136f-96da-1bf036096190.jpg",
    "backImage": "cabeca-pescoco-monitoria/798c3990-6477-136f-96da-1bf036096190.png",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 66
  },
  {
    "id": "cp-11-0068",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "verde-R. Parietal\nazul- R. Frontal\nvermelho- A. Temporal superficial\namarelo-A. Facial transversa\n\nOBS- A. Facial transversa passa inferiormente ao arco zigomático",
    "frontImage": "cabeca-pescoco-monitoria/7333e340-64e5-136f-96da-1bf036096190.jpg",
    "backImage": "cabeca-pescoco-monitoria/99901b90-6601-136f-96da-1bf036096190.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 67
  },
  {
    "id": "cp-11-0069",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "N. Acessório \n\npassa posterior ao ECM e segue para o M. trapézio",
    "frontImage": "cabeca-pescoco-monitoria/76cb75d0-27c0-137d-80fc-fb3bcbf6d10a.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 68
  },
  {
    "id": "cp-11-0070",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "alfinete- N. Lingual",
    "frontImage": "cabeca-pescoco-monitoria/9f1c2c20-8595-1384-92f3-23a0bfa74904.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 69
  },
  {
    "id": "cp-11-0071",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "verde- A. Meníngea média\n\n\nazul-A. Maxilar (continua para dar mais ramos na fossa pterigopalatina)",
    "frontImage": "cabeca-pescoco-monitoria/d33ab410-a843-1384-92f3-23a0bfa74904.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 70
  },
  {
    "id": "cp-11-0072",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "cite 10 ramos da A. Maxilar",
    "a": "A. Alveolar inf( forame da mandíbula)\nA. Meníngea Média (forame espinhoso) \nA. Meníngea Acessória (forame oval)\nA. Temporal profunda \nanterior \nA. Temporal profunda posterior\nA. Pterigóidea lateral\nA. Pterigóidea medial\nA. Massetérica\nA. Esfenopalatina (Forame esfenopalatina + Área de kiesselbach)\nA. Infraorbital (forame infraorbital)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 71
  },
  {
    "id": "cp-11-0073",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina o anel linfático da faringe (de waldeyer)",
    "a": "De cima para baixo:\n\nTonsila faríngea\nTonsila Tubária (tuba auditiva)\nTonsila Palatina\nTonsila lingual",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 72
  },
  {
    "id": "cp-11-0074",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos do palato? e qual a sua inervação?",
    "a": "M. Tensor do Véu palatino\n(V3)\n\nM. da Úvula\nM. Levantador do véu palatino\nM. Palatoglosso\nM. Palatofaríngeo\n(Plexo faríngeo do N. Vago)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 73
  },
  {
    "id": "cp-11-0075",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "diga os limites da faringe",
    "a": "nasofaringe: \nanterior:coanas \nposterior: parede posterior da faringe \nsup: osso esfenóide\ninf: palato mole\n\norofaringe: \nanterior: Raiz da língua \nsup: palato mole\nposterior: istmo das fauces \ninf: Ponta da epiglote\n\nlaringofaringe:\nsup: ponta da epiglote\ninf: borda inferior da cartilagem cricóide\nposterior:",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 74
  },
  {
    "id": "cp-11-0076",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos da faringe?",
    "a": "M. Constritor superior\nM. Constritor médio\nM. Constritor inferior \nM. Salpingofaríngeo\nM. Palatofaríngeo\n(plexo faríngeo do N. Vago)\n\nM. Estilofaríngeo\n(N. Glossofaríngeo)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 75
  },
  {
    "id": "cp-11-0077",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que forma o esfíncter esofágico superior?",
    "a": "Espaço abaixo do M. Constritor inf da faringe\n(transição faringoesofágica)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 76
  },
  {
    "id": "cp-11-0078",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "A. Laringea superior",
    "frontImage": "cabeca-pescoco-monitoria/6f8bfb20-e539-13a8-9245-e1d016fcd73e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 77
  },
  {
    "id": "cp-11-0079",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos externos da orelha e a sua inervação?",
    "a": "M.Auricular posterior\nM.Auricular superior\nM. Auricular anterior\n\ninervação;\nN. Auricular posterior e Ramo temporal do N. Facial",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 78
  },
  {
    "id": "cp-11-0080",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do forame magno?",
    "a": "Bulbo\nArtéria vertebral\nMeninges\nRaiz espinhal do N. Acessório",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 79
  },
  {
    "id": "cp-11-0081",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "V. Jugular externa",
    "frontImage": "cabeca-pescoco-monitoria/24d029f0-e5d5-13af-af73-dba57ec0e66c.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 80
  },
  {
    "id": "cp-11-0082",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "Raiz medial do N. Mediano",
    "frontImage": "cabeca-pescoco-monitoria/b371f6d0-e5f2-13af-af73-dba57ec0e66c.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 81
  },
  {
    "id": "cp-11-0083",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites do trígono cervical anterior? quais os subtrígonos dentro?",
    "a": "posterior- Borda anterior do ECM\n\nanterior- Linha mediana do pescoço\n\nSuperior- margem inf da Mandíbula\n\n•Subtrígonos:\nTrígono Muscular\nTrígono Carotídeo\nTrígono Submentual\nTrígono Submandibular",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 82
  },
  {
    "id": "cp-11-0084",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites do trígono cervical lateral? quais os subtrígonos dele?",
    "a": "anterior- Borda posterior do ECM\n\nposterior - borda anterior do M. Trapézio \n\nInf- Clavícula\n\n•subtrígonos:\nTrígono Omoclavicular\nTrígono Occipital",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 83
  },
  {
    "id": "cp-11-0085",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da parótida?",
    "a": "A. Facial transversa\n\n(ramo da A. Temporal superficial)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 84
  },
  {
    "id": "cp-11-0086",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "V. Tireóidea Média",
    "frontImage": "cabeca-pescoco-monitoria/bad10c50-c59b-13d0-8de0-5188da034ea2.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 85
  },
  {
    "id": "cp-11-0087",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apresentada?",
    "a": "Ramo cervical do N. Facial\n\n(indo para o platisma)",
    "frontImage": "cabeca-pescoco-monitoria/9cd9df90-a7f1-13d6-8347-93585b352879.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 86
  },
  {
    "id": "cp-11-0088",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os números 24,25,32,33?",
    "a": "24- N. Alveolar inf\n25- N. Lingual + N. Corda do tímpano\n32- M. Levantador do véu palatino\n33-M. Tensor do véu palatino\n\n(M. tensor do véu palatino é mais lateral que o M. levantador do véu palatino)",
    "frontImage": "cabeca-pescoco-monitoria/76c7e280-f97d-13e8-ae36-6344e9df5f2f.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 87
  },
  {
    "id": "cp-11-0089",
    "cat": 11,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual vaso passa entre o tronco superior e médio do plexo braquial?",
    "a": "A. Dorsal da escápula",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 88
  },
  {
    "id": "cp-12-0001",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação da laringe?",
    "a": "N. Laringeo recorrente inerva os musculos intrínsecos (EXCETO O M. CRICOTIREOIDEO\n e sensitivamente 1/3 inferior\n\nN. Laringeo superior da os ramos Ext e Int\n\nRamo Int- porção sensitiva 2/3 superiores da laringe\n\nRamo Ext- M. Cricotireóideo \n\nOBS- Ramo ext  inerva parassimpaticamente a tireóide",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 3
  },
  {
    "id": "cp-12-0002",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do tronco tireocervical?",
    "a": "3  ramos\n\nA. Tireoidea inferior (origina a A. Cervical Ascendente)\nA. Supraescapular\nA. Cervical Transversa",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 4
  },
  {
    "id": "cp-12-0003",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do tronco costocervical?",
    "a": "A. Cervical Profunda \nA. Intercostal suprema",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 5
  },
  {
    "id": "cp-12-0004",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quantos trígonos existem no pescoço?",
    "a": "8 trígonos:\n-4 anteriores\n-3 laterais\n-1 posterior\n\n•Anteriores:\nTrígono Submentual\nTrígono Submandibular\nTrígono Muscular\nTrígono Carótico\n\n•Laterais:\nTrígono Omoclavicular\nFossa supraclavicular menor \nTrígono Occipital\n\n•Posterior:\nTrígono Suboccipital",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 6
  },
  {
    "id": "cp-12-0005",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é o tronco tireolinguofacial?",
    "a": "Junção de veias que vão tributar juntas na jugular interna:\n\nV. Facial\nV. Lingual\nV. Tireoidea sup",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 16
  },
  {
    "id": "cp-12-0006",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é e por que é perigoso tomar uma pancada no Ptério?",
    "a": "ptério é a área de encontro de 4 ossos:\nOsso Temporal\nOsso Frontal\nOsso Parietal\nOsso esfenóide\n\nPerigoso, porque é por onde passa ramo principal da A. Meningea Média, ramo frontal. O impacto pode causar uma lesão e, consequentemente, um hematoma Epidural/ Extradural",
    "frontImage": null,
    "backImage": "cabeca-pescoco-prova-normal/ed32a040-41f2-1313-822e-e5e73d524eff.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 17
  },
  {
    "id": "cp-12-0007",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos supra hióideos? qual a ação?",
    "a": "são 4 músculos com a função de abaixar a mandíbula\n\nM. Digástrico(2 ventres)\nM. Estilo- Hióide\nM. Genio hióide\nM.Milo Hióide",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 18
  },
  {
    "id": "cp-12-0008",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da tireóide?",
    "a": "A. tireóidea superior (ramo da A. Carótida Ext)\n\nA. Tireóidea inferior (ramo do Tronco tireocervical )",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 19
  },
  {
    "id": "cp-12-0009",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação das paratireóides?",
    "a": "Aa. Tireóideas inferiores, apenas",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 20
  },
  {
    "id": "cp-12-0010",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apresentada?",
    "a": "N. Laringeo recorrente esquerdo\n\npercorre o espaço traqueoesofágico\n\nOBS- Super importante dizer se é o esquerdo ou direito, pois muda de acordo com o trajeto de cada lado do nervo",
    "frontImage": "cabeca-pescoco-prova-normal/248421e0-4ea3-1347-9031-0556ba2a088d.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 22
  },
  {
    "id": "cp-12-0011",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Carótida externa?",
    "a": "anteriores: 4 ramos\n•A. Tireóidea sup\n•A. Lingual\n•A. Facial\n•A. Maxilar\n\nPosteriores: 2 ramos\nA. Occipital (sai no nível da A. Facial)\nA. Auricular posterior\n\nMedial: 1 ramo\nA. Faríngea ascendente\n\n\nSuperior:\nA. Temporal superficial \n(sai pra cima)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 23
  },
  {
    "id": "cp-12-0012",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo da bainha carótidea ?",
    "a": "N. Vago \nArtéria carótida Comum (externa e interna também// depende da ''altura'')\nV. Jugular interna",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 29
  },
  {
    "id": "cp-12-0013",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do plexo cervical superficial e qual a formação?",
    "a": "C1 - C4\n\nN. Cervical transverso\nN. Auricular Magno\nN. Occipital menor\nNn. Supraclaviculares",
    "frontImage": null,
    "backImage": "cabeca-pescoco-prova-normal/2b7e38d0-15df-1369-9bc8-a72790f82d72.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 30
  },
  {
    "id": "cp-12-0014",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação da sensibilidade da face? por onde esses nervos emergem?",
    "a": "Trigêmeo:\nV1-N. Oftálmico- Fissura orbital sup\n(dorso do nariz até galea aponeurótica)\n\nV2- N. Maxilar- Forame redondo\n(maxilas e dentes maxilares)\n\nV3- N. Mandibular- Forame oval\n(dentes inferiores e mandíbula)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 34
  },
  {
    "id": "cp-12-0015",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos da mastigação e sua inervação?",
    "a": "M. Temporal\nM. Masseter\nM. Pterigóideos (medial e lateral)\n\nTodos inervados por V3 (divisão mandibular do N. Trigêmeo)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 35
  },
  {
    "id": "cp-12-0016",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura apontada?",
    "a": "canal condilar",
    "frontImage": "cabeca-pescoco-prova-normal/95f6c700-6df2-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 38
  },
  {
    "id": "cp-12-0017",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura apontada?",
    "a": "forame estilomastóideo",
    "frontImage": "cabeca-pescoco-prova-normal/d6bd7010-7007-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 39
  },
  {
    "id": "cp-12-0018",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura apontada?",
    "a": "forame jugular",
    "frontImage": "cabeca-pescoco-prova-normal/ab0bf4b0-7079-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 40
  },
  {
    "id": "cp-12-0019",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura apontada?",
    "a": "fossa incisiva",
    "frontImage": "cabeca-pescoco-prova-normal/618fffd0-71c2-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 41
  },
  {
    "id": "cp-12-0020",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura apontada?",
    "a": "Forame Palatino menor",
    "frontImage": "cabeca-pescoco-prova-normal/055b0d10-7242-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 42
  },
  {
    "id": "cp-12-0021",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura apontada?",
    "a": "Forame palatino maior",
    "frontImage": "cabeca-pescoco-prova-normal/d9f68c20-72a6-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 43
  },
  {
    "id": "cp-12-0022",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura apontada?",
    "a": "canal carotídeo",
    "frontImage": "cabeca-pescoco-prova-normal/bfbd61e0-72dc-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 44
  },
  {
    "id": "cp-12-0023",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura apontada?",
    "a": "forame lacerado",
    "frontImage": "cabeca-pescoco-prova-normal/d36f9b30-7355-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 45
  },
  {
    "id": "cp-12-0024",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura apontada?",
    "a": "forame espinhoso",
    "frontImage": "cabeca-pescoco-prova-normal/5f54ef40-73b7-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 46
  },
  {
    "id": "cp-12-0025",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome das estruturas em azul?",
    "a": "Bregma (ponto de encontro das suturas parietais e sagital)\n\nLambda (ponto de encontro das suturas lambdóideas com a sagital)",
    "frontImage": "cabeca-pescoco-prova-normal/82fa8bc0-7412-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 47
  },
  {
    "id": "cp-12-0026",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura apontada?",
    "a": "Forame oval",
    "frontImage": "cabeca-pescoco-prova-normal/13cef2d0-74ae-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 48
  },
  {
    "id": "cp-12-0027",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os círculos marcados?",
    "a": "verde- Astério\n(junção dos ossos occipital, parietal e temporal)\n\nVermelho- Ptério\n(junção dos ossos Frontal, esfenoide, parietal e temporal)",
    "frontImage": "cabeca-pescoco-prova-normal/ddeec480-f2af-135c-b0ea-9d9be027019e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 55
  },
  {
    "id": "cp-12-0028",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação e a inervação do N. Frênico?",
    "a": "C3,C4 e C5\n\nPassa anterior ao M. Escaleno anterior e anterior ao hilo pulmonar",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 58
  },
  {
    "id": "cp-12-0029",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas pintadas?",
    "a": "vermelho- A. Facial (tortuosa e ramo da A. Carótida Externa)\n\nazul-V. Facial \n\nverde-Ducto parotídeo (anterior ao M. Masseter e fura o M. Bucinador no 2º molar superior)",
    "frontImage": "cabeca-pescoco-prova-normal/36018f10-3cce-136b-9780-b10ab99f5338.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 64
  },
  {
    "id": "cp-12-0030",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apresentadas?",
    "a": "verde- A. Alveolar inf\nazul-A. Maxilar\nbranco- A. Meníngea média",
    "frontImage": "cabeca-pescoco-prova-normal/8bac7fb0-fe4f-136e-96da-1bf036096190.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 65
  },
  {
    "id": "cp-12-0031",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "alfinete- N. Lingual\n\nBarbante- N. Alveolar inferior",
    "frontImage": "cabeca-pescoco-prova-normal/9f1c2c20-8595-1384-92f3-23a0bfa74904.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 69
  },
  {
    "id": "cp-12-0032",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que forma o esfíncter esofágico superior?",
    "a": "Espaço abaixo do M. Constritor inf da faringe\n(transição faringoesofágica)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 76
  },
  {
    "id": "cp-12-0033",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "V. Jugular externa",
    "frontImage": "cabeca-pescoco-prova-normal/24d029f0-e5d5-13af-af73-dba57ec0e66c.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 80
  },
  {
    "id": "cp-12-0034",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "Raiz medial do N. Mediano",
    "frontImage": "cabeca-pescoco-prova-normal/b371f6d0-e5f2-13af-af73-dba57ec0e66c.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 81
  },
  {
    "id": "cp-12-0035",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "verde- A. Carótida comum\n\namarelo- V. Jugular interna",
    "frontImage": "cabeca-pescoco-prova-normal/53183ca0-f7d4-1469-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 86
  },
  {
    "id": "cp-12-0036",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "Ventre posterior do M. Digástrico",
    "frontImage": "cabeca-pescoco-prova-normal/eb4a9c70-fa6d-1469-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 87
  },
  {
    "id": "cp-12-0037",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura pintada em verde?",
    "a": "N. Vago\n\n(N. Vago fica entre a A. Carótida Comum e a V. Jugular interna)",
    "frontImage": "cabeca-pescoco-prova-normal/8df69870-fc8a-1469-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 88
  },
  {
    "id": "cp-12-0038",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "verde- M. Temporal\n\nvermelho- Ventre occipital do M. Occipitofrontal\n\namarelo- M. Pterigóideo Lateral",
    "frontImage": "cabeca-pescoco-prova-normal/4724d520-0b3e-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 89
  },
  {
    "id": "cp-12-0039",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "Ventre superior do M. Omohióide",
    "frontImage": "cabeca-pescoco-prova-normal/f24c03f0-0bda-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 90
  },
  {
    "id": "cp-12-0040",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Quais os músculos suprahióides? qual a função?",
    "a": "M. Geniohióide\nM. Digástrico\nM. Estilohióide\nM. Milohióide\n\n\nFunção:  Levantar o osso hióide",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 92
  },
  {
    "id": "cp-12-0041",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "Seio esfenóide",
    "frontImage": "cabeca-pescoco-prova-normal/a11df4a0-0ecf-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 93
  },
  {
    "id": "cp-12-0042",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "verde- A. Facial (tortuosa)\n\nAmarelo- V. Facial (reta)\n\nVermelho- Ducto parotídeo (está na horizontal para furar o M. Bucinador)",
    "frontImage": "cabeca-pescoco-prova-normal/9655f6d0-0ffb-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 94
  },
  {
    "id": "cp-12-0043",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada em 1?",
    "a": "Trígono submandibular\n\nLimites: \n•Ventre anterior do M. Digástrico\n•Ventre posterior do M. Digástrico\n•Mandíbula",
    "frontImage": "cabeca-pescoco-prova-normal/0db1c0d0-1bcb-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 95
  },
  {
    "id": "cp-12-0044",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada em 2?",
    "a": "Trígono submentual\n\n(unilateral no corpo)\nLimites:\n•Ventre anterior do M. Digástrico esquerdo \n•Ventre anterior do M. Digástrico direito\n•Corpo do osso hióide",
    "frontImage": "cabeca-pescoco-prova-normal/b3fabf70-1bd3-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 96
  },
  {
    "id": "cp-12-0045",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada em 3?",
    "a": "Trígono carotídeo\n\n•Ventre posterior do M. Digástrico\n•M. ECM\n• ventre superior do M. Omohióide",
    "frontImage": "cabeca-pescoco-prova-normal/4143f140-1bdd-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 97
  },
  {
    "id": "cp-12-0046",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada em 4?",
    "a": "trígono occipital\n\nLimites:\n•M. Trapézio\n•M. ECM\n•Ventre inferior do M. Omohióide",
    "frontImage": "cabeca-pescoco-prova-normal/986c6870-1be8-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 98
  },
  {
    "id": "cp-12-0047",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada em 5?",
    "a": "fossa supraclavicular menor\n\nLimites:\n•Inserções do M. ECM\n•Clavícula",
    "frontImage": "cabeca-pescoco-prova-normal/8d11f280-1bff-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 99
  },
  {
    "id": "cp-12-0048",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada em 6?",
    "a": "Trígono Muscular\n\nLimites:\n•Linha mediana do pescoço\n•Ventre superior do M. omohióide\n•M. ECM",
    "frontImage": "cabeca-pescoco-prova-normal/84dd1d00-1c0a-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 100
  },
  {
    "id": "cp-12-0049",
    "cat": 12,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "Seio maxilar",
    "frontImage": "cabeca-pescoco-prova-normal/14531490-3136-146a-bec0-d9d050a7f33e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- PROVA NORMAL- Eduardo Lôbo",
    "deckSlug": "cabeca-pescoco-prova-normal-eduardo-lobo-2e9efe70",
    "deckOrder": 101
  }
];
