window.MMSS_IMPORTED_FLASHCARDS = [
  {
    "id": "mmss-0001",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos do manguito rotador? e sua função?",
    "a": "M. Infraespinal\nM.Supraespinal\nM.Subescapular\nM. Redondo menor\n\nProtegem e fixam a articulação do ombro",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 0
  },
  {
    "id": "mmss-0002",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Qual a ação e inervação  do M. Serratil anterior?",
    "a": "Protusão da escápula\nN. Torácico Longo \n(raízes C5,C6,C7)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 2
  },
  {
    "id": "mmss-0003",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "por onde passa e o que o  N. Supraescapular inerva?",
    "a": "passa por dentro do forame escapular e inerva os músculos; SupraEspinal e Infraespinal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 3
  },
  {
    "id": "mmss-0004",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Quais músculos possuem origem no epicôndilo medial?",
    "a": "5 músculos\n\nM. Flexor Ulnar do carpo\nM. Palmar Longo\nM. Flexor Radial Do carpo\nM. Pronador redondo\nM. Flexor superficial dos dedos",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 4
  },
  {
    "id": "mmss-0005",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do tronco tireocervical?",
    "a": "A. Tireoidea inferior (origina a A. Cervical ascendente)\n\nA. Supraescapular (passa por cima do forame escapular) \n\nA. Cervical Transversa",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 5
  },
  {
    "id": "mmss-0006",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do tronco costocervical?",
    "a": "A. Cervical Profunda\nA. Intercostal suprema( dá as primeiras duas intercostais posteriores)\n\n\nOBS- o resto das Aa. Intercostais posteriores são originadas diretamente da Aorta",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 6
  },
  {
    "id": "mmss-0007",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Axilar?",
    "a": "A. Axilar delimitada pelo M. Peitoral menor;\n\n1ª porção- A. Torácica superior\n\n2ª porção- A. Torácica Lateral e A. Toracoacromial\n\n3ª porção- A. Circunflexa anterior do úmero; A. Circunflexa posterior do úmero e A.Subescapular\n\nA. SUBESCAPULAR RAMOS; A. TORACODORSAL E \nA. CIRCUNFLEXA DA ESCÁPULA",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 7
  },
  {
    "id": "mmss-0008",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Limites e conteúdo do espaço quadrangular",
    "a": "Limites:\n Sup: M.Redondo menor\nInf: M.Redondo Maior\nLateral: Úmero \nMedial: Cabeça longa do Tríceps braquial\n\n\n\nConteúdo: Vasos Circunflexoes posteriores do úmero \nN. Axilar",
    "frontImage": null,
    "backImage": "mmss/90fb9550-32ef-1331-9cc0-355567e37b0c.jpg",
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 8
  },
  {
    "id": "mmss-0009",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "limites e conteúdo do espaço triangular",
    "a": "Limites-\nSup: M.Redondo Menor\nInf: M Redondo Maior\nLateral: Cabeça longa do tríceps braquial\n\nconteúdo: Vasos Circunflexos da Escápula",
    "frontImage": null,
    "backImage": "mmss/1fbfa120-3316-1331-9cc0-355567e37b0c.jpg",
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 9
  },
  {
    "id": "mmss-0010",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "limites e conteúdo do intervalo triangular",
    "a": "Limites-\nSup: M.Redondo Maior\nMedial: Cabeça Longa do tríceps braquial\nLateral: Cabeça lateral do tríceps braquial\n\nConteúdo: N. Radial e Vasos Braquiais profundos",
    "frontImage": null,
    "backImage": "mmss/f90cfa00-332e-1331-9cc0-355567e37b0c.jpg",
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 10
  },
  {
    "id": "mmss-0011",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Explique a circulação colateral ao ligar a A. Axilar acima da A. Subescapular",
    "a": "Ligação deve ocorrer na A. Axilar antes de dar o ramo Subescapular \n\nA Circulação colateral é feita pela anastomose da A. Dorsal da escápula, A. Supraescapular e A. Circunflexa da escápula.\n\nA circunflexa da escápula tem seu fluxo invertido e passa a nutrir o braço\n\n\nA. DORSAL DA ESCÁPULA É RAMO DA A. SUBCLÁVIA OU A. CERVICAL TRANSVERSA",
    "frontImage": null,
    "backImage": "mmss/e8b4af40-46e2-11f2-b45c-895a1a4eb351.jpg",
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 11
  },
  {
    "id": "mmss-0012",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do Arco palmar superficial? quais seus ramos?",
    "a": "A. Ulnar mais o Ramo superficial da A. Radial\n\nAa. Palmares digitais comuns-> Aa. Palmares digitais próprias",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 13
  },
  {
    "id": "mmss-0013",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do Arco palmar profundo? quais os seus ramos?",
    "a": "A. Radial mais o Ramo profundo da A. Ulnar\n\nA. Principal do polegar\nA. Radial do Indicador\nAa. Metacarpais palmares",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 14
  },
  {
    "id": "mmss-0014",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o limite e conteúdo da fossa cubital?",
    "a": "Medial- M. Pronador redondo\nLateral- M. Braquiorradial\nSuperior- Linha entre os epicondilos\n\nCONTEÚDO:\nMEDIAL PARA LATERAL\n\nNAT\nN. mediano\nA. Braquial\nT. do M. Bicéps braquial\n\nOBS- Superiormente não é assim, pois no nível da fossa cubital, a artéria e o nervo trocam de lugar, tornando o nervo mais medial\n\nN. Radial- passa por baixo do epicondilo lateral",
    "frontImage": null,
    "backImage": "mmss/2b50e560-c76b-1461-a90c-a74bdbbf5f93.jpg",
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 15
  },
  {
    "id": "mmss-0015",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "diferencie o N. Toracodorsal e o N. Dorsal da Escápula",
    "a": "N. Toracodorsal é ramo do fascículo posterior e inverva o M. Latíssimo do Dorso\n\nN. Dorsal da escápula é oriundo de C5 e inerva os Mm. rombóides",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 16
  },
  {
    "id": "mmss-0016",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Quais os limites da tabaqueira Anatômica e o conteúdo?",
    "a": "Limites: ''sanduíche de curto''\n\nLateral- T. do M. Abdutor Longo do Polegar e T. do M. Extensor curto do polegar \n\nMedial: T. do M. Extensor Longo do polegar \n\n(sanduíche de curto, pois o único curto está no meio dos longos)\n\nConteúdo-\nA. Radial e \nRamo superficial do N. Radial\nV. Cefálica",
    "frontImage": null,
    "backImage": "mmss/87248510-3348-1331-9cc0-355567e37b0c.jpg",
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 17
  },
  {
    "id": "mmss-0017",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os principais ramos da A. Braquial?",
    "a": "A. Braquial profunda (passa pelo intervalo triangular)\nA. Colateral Ulnar superior\nA. Colateral Ulnar Inferior\n\n\nA. Braquial profunda termina em:\nA. Colateral radial\nA. Colateral média\n\nA. Braquial ao chegar na Fossa cubital se divide em;\nA. Ulnar e A. Radial",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 18
  },
  {
    "id": "mmss-0018",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do N. Musculocutâneo?",
    "a": "oriundo do fascículo lateral.\n\nFura o M. Coracobraquial, percorrendo entre o biceps braquial e o braquial. Assim, inerva todo o compartimento anterior do braço, emerge como N. Cutâneo lateral do antebraço após o biceps braquial",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 19
  },
  {
    "id": "mmss-0019",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Qual a inervação do N. Radial?",
    "a": "Oriundo do Fascículo posterior.\n\nInerva o M. Tríceps braquial, passa pelo intervalo triangular, passa anterior ao epicondilo lateral e inerva todos os \nM. Extensores do Antebraço\n\n\nAo passar pelo epicondilo lateral, da os ramos profundo e superficial \n\nProfundo FURA O M. SUPINADOR (CANAL DO SUPINADOR) inerva- M. Extensores Do antebraço \nSuperficial- Cutâneo no dorso da mao e dos dedos",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 20
  },
  {
    "id": "mmss-0020",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Qual a inervação do N. Mediano?",
    "a": "Oriundo do fascículo lateral e medial.\n\nMais medial na fossa cubital e inerva todos os M. Flexores do Antebraço (exceto metade medial do M. Flexor profundo dos dedos (4º e 5º dedo)\n o M. Flexor Ulnar do Carpo e o M. Braquiorradial)\n\nPassa pelo túnel do carpo e inerva:\n\nMúsculos tenares:\nAbdutor curto do polegar\nflexor curto do polegar \noponente do polegar\n+\n1º e 2º lumbricais",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 21
  },
  {
    "id": "mmss-0021",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do N. Ulnar?",
    "a": "Oriundo do Fascículo medial\n\nPassa POSTERIORMENTE ao epicôndilo medial\n\nInerva o M. Flexor ulnar do carpo e a metade Medial do M. Flexor profundo dos dedos(T. do 4º e 5º dedo)\n\npassa pelo túnel de guyon (túnel ulnar) e inerva:\n\nMúsculos hipotenares:\nM. Abdutor curto do dedo mínimo\nM. Flexor curto do dedo mínimo\nM. Oponente do dedo mínimo\nM. Palmar curto \n+ interósseos palmares e dorsais\n+ 3º e 4º lumbricais\n+ M. Adutor do polegar",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 22
  },
  {
    "id": "mmss-0022",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a circulação colateral feita pela ligação da A. Braquial?",
    "a": "A nutrição continua pela A. Braquial profunda, logo, a ligação da A. Braquial deve ser feita após esse ramo",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 23
  },
  {
    "id": "mmss-0023",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do M. Braquiorradial e qual a sua ação?",
    "a": "Inervado pelo N. Radial e ele faz a flexão do antebraço (é a exceção do antebraço)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 24
  },
  {
    "id": "mmss-0024",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é e o que passa pelo tunel ulnar ou loja de guyon? diga os limites",
    "a": "Um Trajeto \n\nLocalização-\n\nanterior(em cima) ao retináculo dos flexores/ Tunel do Carpo \n\nENTRE O PISIFORME E HÂMULO DO HAMATO\n(Ligamento palmar do carpo/ Lig. Pisohamato)\n\nassoalho: Piramidal e Hamato\n\nConteúdo-\nVasos Ulnar e N. Ulnar- Nervo é mais medial",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 25
  },
  {
    "id": "mmss-0025",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do túnel do carpo?",
    "a": "Limites:\nLateral- Escafoide e trapezoide\nMedial-Pisiforme e Hâmulo do hamato\nTeto- Retináculo dos MM. flexores\n\nConteúdo: 9 Tendões e 1 Nervo\nM. Flexor Superficial dos dedos\nM. Flexor Profundo dos desos\nM. Flexor Longo do polegar\nN. Mediano",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 26
  },
  {
    "id": "mmss-0026",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Ulnar?",
    "a": "Origem- Fascículo Medial\n\nMão em garra",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 27
  },
  {
    "id": "mmss-0027",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Radial?",
    "a": "Origem- Fascículo Posterior\n\nMão caída",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 28
  },
  {
    "id": "mmss-0028",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Torácico Longo?",
    "a": "Origem C5, C6 e C7\n\nEscápula alada- lesão do M. Serrátil Anterior\n\nOBS- relacionado com câncer de mama, pois as vezes há lesão durante a cirurgia de retirada da mama",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 29
  },
  {
    "id": "mmss-0029",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Toracodorsal?",
    "a": "Origem- Fascículo Posterior\n\nLesão do Escalador- M. Latíssimo do dorso",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 30
  },
  {
    "id": "mmss-0030",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Axilar?",
    "a": "Origem- Fascículo Posterior\n\nOmbro caído- não abduz o braço(SINAL DE DRAGONA)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 31
  },
  {
    "id": "mmss-0031",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Mediano?",
    "a": "Origem- Fascículo medial e Lateral\n\nNivel de punho- Mão em símio\nNivel de cotovelo- Mão em benção",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 32
  },
  {
    "id": "mmss-0032",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Dorsal da escápula?",
    "a": "Origem- Raiz C5\n\nPerda da função dos músculos inervados:\nInerva os rombóides e o levantor da escápula\n\nOBS- ELE NÃO INERVA O M. LATÍSSIMO DO DORSO",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 33
  },
  {
    "id": "mmss-0033",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do tronco superior?",
    "a": "Paralisia de Erb- Duchenne// Mão de Garçom",
    "frontImage": null,
    "backImage": "mmss/c4fe7aa0-7e44-1315-822e-e5e73d524eff.jpg",
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 34
  },
  {
    "id": "mmss-0034",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do Tronco Inf?",
    "a": "Paralisia de Klumpke- Causa Mão em garra",
    "frontImage": null,
    "backImage": "mmss/29052b50-7e6a-1315-822e-e5e73d524eff.jpg",
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 35
  },
  {
    "id": "mmss-0035",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação da V. Basílica e da V. Cefálica? onde elas tributam?",
    "a": "Arco venoso dorsal da mão é a origem comum\n\na V. Basílica junto com veias braquiais formam a V. Axilar, local que a V. Cefálica tributa",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 36
  },
  {
    "id": "mmss-0036",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que passa pelo forame da escápula? e por cima?",
    "a": "N. Supraescapular(Tronco superior)  por dentro e A. Supraescapular por cima (Tronco Tireocervical)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 37
  },
  {
    "id": "mmss-0037",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do N. Axilar?",
    "a": "Oriundo do fascículo posterior, rodeia o colo cirúrgico do úmero e inerva:\nM. Deltóide\nM. Redondo menor\n\nLesão: Sinal de dragona",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 38
  },
  {
    "id": "mmss-0038",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação sensitiva do antebraço?",
    "a": "N. Cutâneo medial do antebraço oriundo do fascículo medial\n\nN. Cutâneo lateral do antebraço (continuação do N. Musculocutâneo)\n\nN. Cutâneo Post. Do antebraço (Ramo do N. Radial)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 39
  },
  {
    "id": "mmss-0039",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do Manguito Rotador?",
    "a": "M. Redondo Menor- N. Axilar\n\nM. Infraespinhal- N. Supraescapular\n\nM. Supraespinhal- N. Supraescapular\n\nM. Subescapular- N. Subescapular sup+ Subescapular inf\n\nOBS- M. Redondo Maior- Inervado pelo N. Subescapular INF",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 40
  },
  {
    "id": "mmss-0040",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Subescapular?",
    "a": "A. Circunflexa da Escápula\n\nA. Toracodorsal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 41
  },
  {
    "id": "mmss-0041",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Axilar 1ª porção?",
    "a": "A. Torácica superior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 43
  },
  {
    "id": "mmss-0042",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Axilar 2ª parte?",
    "a": "A. Toracoacromial\nA. Torácica lateral\n (emerge depois)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 44
  },
  {
    "id": "mmss-0043",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Axilar 3ª parte?",
    "a": "A. Circunflexa anterior do úmero\nA. Circunflexa posterior do úmero\nA. Subescapular (dá os ramos A. Toracodorsal e A. Circunflexa da escápula)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 45
  },
  {
    "id": "mmss-0044",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas marcadas?",
    "a": "laranja- A. Toracoacromial\n\nvermelho- A. Axilar\n\nroxo- A. Torácica lateral\n\nverde// pinça- N. Musculocutâneo \n\nAzul- N. Mediano\n\nPreto- N. Ulnar\n\nbranco- A. Braquial",
    "frontImage": "mmss/0ec3c0f0-9579-132e-a096-f3df8bb26e61.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 46
  },
  {
    "id": "mmss-0045",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais músculos fazem rotação medial?",
    "a": "3 músculos\n\nM. Redondo Maior\nM. Latíssimo do dorso\nM. Subescapular",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 47
  },
  {
    "id": "mmss-0046",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina o desfiladeiro torácico",
    "a": "locais em que estruturas nobres podem ser comprimidas (vasos subclávios e nervos)\n\n3 espaços;\nEntre os escalenos (Ant e médio)- Intercostoescalênico\n\nEntre a 1ª costela e a clavícula\nEspaço Costoclavicular\n\nAbaixo do M. Peitoral menor\nEspaço Retrocoracopeitoral",
    "frontImage": null,
    "backImage": "mmss/585b6430-3701-1331-9cc0-355567e37b0c.png",
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 48
  },
  {
    "id": "mmss-0047",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura marcada?",
    "a": "Verde- A. Circunflexa anterior do úmero \nVermelha- A. Circunflexa posterior do úmero",
    "frontImage": "mmss/fa98ec00-921e-1330-8af0-7b97e391788e.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 50
  },
  {
    "id": "mmss-0048",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura marcada?",
    "a": "Pinça- A. Subescapular",
    "frontImage": "mmss/fd895290-9289-1330-8af0-7b97e391788e.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 51
  },
  {
    "id": "mmss-0049",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura marcada? qual o conteúdo?",
    "a": "Espaço Quadrangular:\nredondo menor\nredondo maior\ncabeça Longa do M. Tríceps braquial\nÚmero\n\nConteúdo:\nVASOS. Circunflexa post do Úmero\nN. Axilar",
    "frontImage": "mmss/29380a90-fe4f-1330-9cc0-355567e37b0c.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 52
  },
  {
    "id": "mmss-0050",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura marcada? qual o conteúdo?",
    "a": "Espaço Triangular:\nRedondo menor\nRedondo maior\nCabeça longa do M. Tríceps braquial\n\nconteúdo: \nVASOS. Circunflexa da escápula\n (ramo da A. Subescapular)",
    "frontImage": "mmss/365b0300-ffce-1330-9cc0-355567e37b0c.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 53
  },
  {
    "id": "mmss-0051",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura marcada? e o conteúdo?",
    "a": "intervalo triangular:\n\nN. Radial\nVASOS. Braquial profunda",
    "frontImage": "mmss/6267b6f0-0c03-1331-9cc0-355567e37b0c.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 54
  },
  {
    "id": "mmss-0052",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada? quais tendões formam? qual o conteúdo?",
    "a": "Tabaqueira Anatômica\n\nMedial- M. Extensor Longo do polegar\n\nLateral- M. Extensor curto do polegar\nM. Abdutor longo do polegar\n\nConteúdo:\nA. Radial e Ramo superficial do N. Radial\n+ V. Cefálica",
    "frontImage": "mmss/a6ab43c0-1394-1331-9cc0-355567e37b0c.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 55
  },
  {
    "id": "mmss-0053",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada com a pinça?",
    "a": "N torácico Longo\n (C5,C6 e C7)",
    "frontImage": "mmss/1ebfd990-3143-1331-9cc0-355567e37b0c.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 56
  },
  {
    "id": "mmss-0054",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada com a pinça?",
    "a": "Verde- A. Circunflexa anterior do úmero\n\nvermelho- A. Circunflexa post do úmero",
    "frontImage": "mmss/8b8b08e0-319a-1331-9cc0-355567e37b0c.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 57
  },
  {
    "id": "mmss-0055",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada com a pinça?",
    "a": "A. Subescapular (3ª porção da A. Axilar)",
    "frontImage": "mmss/a7f6e6d0-3202-1331-9cc0-355567e37b0c.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 58
  },
  {
    "id": "mmss-0056",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas PINTADAS de azul e vermelho?",
    "a": "São ramos da A. Subescapular (3ª porção da A. Axilar)\n\nazul- A. Toracodorsal\n\nvermelho- A. Circunflexa da escápula",
    "frontImage": "mmss/6ed75bc0-325f-1331-9cc0-355567e37b0c.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 59
  },
  {
    "id": "mmss-0057",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais locais de compressão que podem causar desfiladeiro torácico",
    "a": "3 locais\n\n1- entre o M. Escaleno anterior e o M. Escaleno médio\nEspaço interescalênico\n\n2- entre a clavícula e a 1ª costela\nEspaço costoclavicular\n\n3- abaixo do M. Peitoral menor\nEspaço retropeitoral",
    "frontImage": null,
    "backImage": "mmss/f52f03a0-38ac-1331-9cc0-355567e37b0c.png",
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 60
  },
  {
    "id": "mmss-0058",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais são os músculos tenares? qual a inervação?",
    "a": "M. Abdutor curto do polegar\nM. Flexor curto do polegar\nM. oponente do polegar\nInervação: N. Mediano\nM. Adutor do polegar \n(N. Ulnar)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 61
  },
  {
    "id": "mmss-0059",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais são os músculos hipotenares? qual a inervação?",
    "a": "M. Abdutor do dedo mínimo\nM. Flexor  do dedo mínimo\nM. Oponente do dedo mínimo\nM. Palmar curto\n\nInervados pelo N. Ulnar",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 62
  },
  {
    "id": "mmss-0060",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos da mão?",
    "a": "Tenares: 4\nM. Oponente do polegar\nM. Flexor curto do polegar\nM. Abdutor curto do polegar \nM. Adutor do Polegar\n\nHipotenares: 4\nM. Oponente do dedo mínimo\nM. Flexor curto do dedo mínimo\nM. Abdutor curto do dedo mínimo\nM. Palmar curto \n+ \nMm. Interósseos dorsais e palmares \nMm. Lumbricais",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 63
  },
  {
    "id": "mmss-0061",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "diferencie as funções dos interósseos e dos lumbricais",
    "a": "Interósseos dorsais: Abdução (IDAB)\n\nInterósseos palmares: adução (IPAD)\n\nLumbricais: Flexão das articulações metacarpofalangianas",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 64
  },
  {
    "id": "mmss-0062",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação dos músculos da mão?",
    "a": "Tenares(EXCETO O M. ADUTOR DO POLEGAR) + 1º e 2º lumbricais- Ramo Recorrente do N. Mediano\n\nHipotenares + 3º e 4º lumbricais + Interósseos (dorsais e palmares)+ Adutor do polegar - N. Ulnar",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 65
  },
  {
    "id": "mmss-0063",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do M. Palmar curto?",
    "a": "N. ulnar",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 66
  },
  {
    "id": "mmss-0064",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura da pinça?",
    "a": "Canal do Supinador\n\nConteúdo: Ramo profundo do nervo radial (pode ser comprimido)",
    "frontImage": "mmss/75a7ce70-4fd0-133a-ba74-fb87ffa62fd3.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 67
  },
  {
    "id": "mmss-0065",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura marcada?",
    "a": "Ramo dorsal do N. Ulnar\n\n\n\n OBS- O QUE PASSA PELO CANAL DE GUYON É O N. ULNAR EM SI",
    "frontImage": "mmss/05e2ada0-50b9-133a-ba74-fb87ffa62fd3.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 68
  },
  {
    "id": "mmss-0066",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do Arco palmar superficial?",
    "a": "Aa. digitais Palmares comuns (dão os ramos digitais palmares próprios)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 69
  },
  {
    "id": "mmss-0067",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais músculos tem origem no epicondilo lateral?",
    "a": "6 Músculos; Inervados pelo N. Radial (Ramo profundo) \n\nM. Extensor Radial curto do carpo\nM. Extensor dos dedos\nM. Extensor do dedo mínimo\nM. Extensor ulnar do carpo\nM. Supinador\nM. Ancôneo",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 70
  },
  {
    "id": "mmss-0068",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação dos músculos escalenos?",
    "a": "M. Escaleno Anterior-\nC5-C8\n\nM. Escaleno Médio-\nC3-C7\n\nM. Escaleno Posterior:\nC5-C8",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 71
  },
  {
    "id": "mmss-0069",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Toracoacromial?",
    "a": "4 ramos:\n\nRamos acromiais\nRamos Deltóideos\nRamos Cervicais\nRamos peitorais",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 72
  },
  {
    "id": "mmss-0070",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas marcadas?",
    "a": "azul-A. Braquial\nvermelho-Ramo muscular (avulso)\nbranco-A. Recorrente radial\nverde-A. Ulnar",
    "frontImage": "mmss/8be6d280-82eb-1346-9031-0556ba2a088d.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 73
  },
  {
    "id": "mmss-0071",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais nervos acompanham as artérias interósseas  ?",
    "a": "A. Interóssea anterior- acompanhada pelo \nN. Interósseo anterior \n(ramo do N. Mediano)\n\nA. Interósseos post- Acompanhada pelo \nN. Interósseo post\n(Ramo do N. Radial)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 74
  },
  {
    "id": "mmss-0072",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as anastomoses existente na fossa cubital?",
    "a": "A. Colateral ulnar sup- A. Recorrente ulnar posterior\n(Ramo da A. Ulnar)\n\nA. Colateral ulnar Inf- A. Recorrente ulnar anterior\n(Ramo da A. Ulnar)\n\nA. Colateral média- A. Recorrente interóssea\n(Ramo da A. Interóssea post)\n\nA. Colateral radial- A. Recorrente radial\n(Ramo da A. Radial)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 75
  },
  {
    "id": "mmss-0073",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina o que é a mão de gorjeta de garçom",
    "a": "lesão dos rotadores laterais do braço, tornando a rotação medial preponderante",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 76
  },
  {
    "id": "mmss-0074",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "N. Palmar digital comum\n\npodem ser ramos do N. Mediano ou do N. Ulnar (caso seja mais medial )",
    "frontImage": "mmss/eb14b140-d2a4-136b-bd6e-975666b455ef.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 77
  },
  {
    "id": "mmss-0075",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que os Nn. Interósseos inervam?",
    "a": "N. Interósseo anterior (ramo do N. Mediano)\n•M. Flexor Longo do polegar \n•M. Pronador quadrado\n•Metade lateral do Flexor profundo dos dedos\n\nN. Interósseo post (Ramo do N. Radial) \ntodos os músculos extensores do antebraço\n(exceto o M. Braquiorradial, os extensores radiais do carpo, o ancôneo e o supinador )",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 78
  },
  {
    "id": "mmss-0076",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "V. Basílica",
    "frontImage": "mmss/c0d4ffe0-e58e-13a8-9245-e1d016fcd73e.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 79
  },
  {
    "id": "mmss-0077",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apresentada?",
    "a": "V. Jugular externa",
    "frontImage": "mmss/4478c5f0-e585-13af-af73-dba57ec0e66c.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 80
  },
  {
    "id": "mmss-0078",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "Raiz medial do N. Mediano",
    "frontImage": "mmss/e4cfa690-e5ad-13af-af73-dba57ec0e66c.jpg",
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 81
  },
  {
    "id": "mmss-0079",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do arco carpal dorsal? quais os ramos?",
    "a": "R. Carpal dorsal da A. Radial\n+\nR. Carpal dorsal da A. Ulnar\n\n\nRamos terminais:\nAa. Metacarpais dorsais",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 82
  },
  {
    "id": "mmss-0080",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os pontos de bloqueio do plexo braquial por anestésicos?",
    "a": "interescalênico\nSupraclavicular\nInfraclavicular\nAxilar",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 83
  },
  {
    "id": "mmss-0081",
    "cat": 15,
    "src": "ZIP",
    "b": "b-zip",
    "q": "lesão de colo cirúrgico do úmero afeta principalmente qual nervo?",
    "a": "N. Axilar\n\nEle rodeia o colo cirúrgico do úmero",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMSS MONITORIA - Eduardo Lôbo",
    "deckSlug": "mmss-monitoria-eduardo-lobo-2e9efe70",
    "deckOrder": 84
  }
];
