window.GENITO_MMII_IMPORTED_FLASHCARDS = [
  {
    "id": "gm-13-0001",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a localização do ureter em relação ao ducto deferente?",
    "a": "Ureter passa embaixo e lateral. O ureter vem dos rins (de cima)\n\nducto deferente sai pelo canal inguinal e circunda a bexiga até chegar às glândulas seminais pra virar ducto ejaculatório",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 0
  },
  {
    "id": "gm-13-0002",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da bexiga?",
    "a": "XX: A. Vesical sup\nA. Uterina\n\n\nXY:\nAa. Vesicais inferiores (são ramos da A. Ilíaca interna)\n\nAa. Vesicais superiores (são ramos da A. umbilical que é ramo da A. Iliaca int)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 1
  },
  {
    "id": "gm-13-0003",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a função da glândula seminal?",
    "a": "secretam líquido alcalino rico em frutose no ducto deferente  (antes de ele entrar, ele da a ampola do ducto deferente)\n\ntransforma-se em ducto ejaculatório depois de receber os ductos das glândulas seminais",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 2
  },
  {
    "id": "gm-13-0004",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do funículo espermático?",
    "a": "7 principais estruturas\n\nA. do ducto deferente \nDucto deferente \nA. Testicular\nPlexo Panpiniforme\nRamo genital do N. Genitofemoral\nM. Cremáster\nA. Cremastérica",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 3
  },
  {
    "id": "gm-13-0005",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da próstata?",
    "a": "A. prostática( ramo da A. Vesical inf)\n\nA. Retal media\n\nA. pudenda interna",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 4
  },
  {
    "id": "gm-13-0006",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação do ducto deferente?",
    "a": "A. do ducto deferente (A. Vesical sup )\n\n+ Ramos da A. Epigástrica inf\n+Ramos da A. Retal Média",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 5
  },
  {
    "id": "gm-13-0007",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da Aorta Abdominal?",
    "a": "ANTERIOR; 4 ramos\nAa. frênicas inferiores (duas)\nTronco Celíaco\nA.Mesenterica sup\nA. Mesenterica inf\n\nLATERAL: 3 ramos\nAa. Suprarrenais\nAa. renais\nAa. Gonadais( Testicular ou ováricas)\n\nPOSTERIOR: 2 ramos\nAa. Lombares\nA. Sacral Mediana",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 6
  },
  {
    "id": "gm-13-0008",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a localização do rim e o que fixa ele?",
    "a": "são retroperitoneais e estão \nanteriores ao M. Psoas maior e ao M. Quadrado lombar\n\nfixado por gordura\n\nde interno para externo:\nCápsula fibrosa do rim\nGordura perirrenal\nFáscia renal (de gerota)\nGordura pararrenal\n\nOBS- o contato do rim com os Nn. Iliohipogástrico e Ilioinguinal tem relação com a dor irradiada para as genitálias a partir  de patologias renais",
    "frontImage": null,
    "backImage": "genito-urinario/f9053ca0-4aa0-11fb-a928-c99a9b7e2895.jpg",
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 7
  },
  {
    "id": "gm-13-0009",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas sinalizadas?",
    "a": "amarelo- Coluna renal (separa as pirâmides renais)\n\nAzul- papila renal (ápice da pirâmide renal)\n\nverde- Cálice menor\n\nvermelho- Cálice maior\n\npreto- Pelve renal",
    "frontImage": "genito-urinario/249992e0-dd76-1395-ba4d-adf186572cef.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 8
  },
  {
    "id": "gm-13-0010",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a relação de lateralidade do hilo renal?",
    "a": "VAP (anterior para posterior)\n\nV. Renal\nA. Renal\nPelve renal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 9
  },
  {
    "id": "gm-13-0011",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Renal?",
    "a": "A. suprarrenal inf\nA. Da pelve renal+ uretérica\n\n5 Ramos;\n\nA. Segmentar posterior\nA. Segmentar superior\nA. Segmenter anterior superior\nA. Segmentar anterior inferior\nA. Segmenter inferior\n\nOBS- Após isso, eles dão os ramos Aa. Interlobares-> Aa. Arqueadas ->Aa. Interlobulares",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 10
  },
  {
    "id": "gm-13-0012",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "as veias testiculares/ ováricas drenam o sangue para onde?",
    "a": "Direita- V. Cava Inf\n\nEsquerda- Veia renal esquerda (causa predisposição à varicocele nos homens)\n\nOBS- varicocele= varizes no escroto (ocorre devido ao ângulo da incidência da veia do lado esquerdo)",
    "frontImage": null,
    "backImage": "genito-urinario/6ec973c0-ad64-1441-9836-cf09eb925424.jpg",
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 11
  },
  {
    "id": "gm-13-0013",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que ocorre numa fratura de penis?",
    "a": "rompimento da tunica albugínea",
    "frontImage": null,
    "backImage": "genito-urinario/65c76550-591c-11fb-a928-c99a9b7e2895.jpg",
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 12
  },
  {
    "id": "gm-13-0014",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do penis?",
    "a": "Parassimpático: Nn. Esplâncnicos pélvicos levam fibras até o plexo hipogástrico inferior\n\n\nSimpático: Tronco simpático lombar a partir do plexo hipogástrico inferior\n\nSensitivo e Motor:\nN. Dorsal do Penis, ramo terminal do N. pudendo \n\nOBS- Plexo Prostático é um subplexo do plexo hipogástrico inferior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 13
  },
  {
    "id": "gm-13-0015",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da suprarrenal?",
    "a": "A. Suprarrenal superior\nramo das Frenicas inferiores \n\nA. Suprarrenal media\nramo lateral da aorta abdominal \n\nA. Suprarrenal inf\nRamo da A. Renal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 14
  },
  {
    "id": "gm-13-0016",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "veia suprarrenal esquerda",
    "frontImage": "genito-urinario/ffa17710-7ea6-11fb-a928-c99a9b7e2895.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 15
  },
  {
    "id": "gm-13-0017",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "azul- prega interuretérica\nbranco- óstios uretéricos (direito e esquerdo)\nlaranja- óstio interno da \nuretra\n\nbrancos+ laranja formam o trígono vesical",
    "frontImage": "genito-urinario/7a65c150-8982-11fb-a928-c99a9b7e2895.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 16
  },
  {
    "id": "gm-13-0018",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do ducto ejaculatório?",
    "a": "Ducto deferente( dilata-se formando a ampola do ducto deferente)+ ducto da glandula seminal\n\nDucto ejaculatório-desemboca na uretra prostática",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 17
  },
  {
    "id": "gm-13-0019",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais musculos da ereção do penis?",
    "a": "Mm. Isquiocavernosos e M. Bulbo esponjoso",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 18
  },
  {
    "id": "gm-13-0020",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o principal ramo da A. Iliaca Int que nutre o Útero?",
    "a": "A. Iliaca Int dá o ramo A. Uterina que se anastomosa com a A. Ovárica, nutrindo esses órgãos",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 19
  },
  {
    "id": "gm-13-0021",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome das escavações e do espaços no períneo da mulher? e do homem?",
    "a": "escavação vesicouterina (entre a bexiga e o útero )\nescavação retouterina\n(entre o reto e o útero)\n\nEspaço retropúbico\n(posterior à sínfise púbica)\n\nEspaço Retrorretal (posterior do reto)\n\nOBS- Escavações são entre órgãos e Espaços são entre órgão e osso\n\nHomem:\nEscavação Retovesical\n\nEspaço retropúbico\nEspaço Retrorretal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 20
  },
  {
    "id": "gm-13-0022",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "diferencie a rima do pudendo e o vestíbulo vaginal",
    "a": "rima do pudendo- espaço delimitado pelos Labios maiores\napresenta:\nlábios menores\n\nVestíbulo da vagina- espaço delimitado pelos labios menores\n\napresenta:\nclitóris\nÓstio externo da uretra\nCanal vaginal \nGlândula vestibulares maiores desembocam aí",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 21
  },
  {
    "id": "gm-13-0023",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ligamentos do utero?",
    "a": "Ligamento redondo do utero, passa pelo canal inguinal e se insere no labio maior (anteriorizado)\n\nLigamento Largo do Útero \n(formado por\n•Mesosalpinge\n•Mesoovário\n•Mesométrio)\n\nLigamento Retouterino\n(prende o útero ao reto)\n\nLigamento úteroovárico\n(prende o útero ao ovário)\n\nLigamento cardinal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 22
  },
  {
    "id": "gm-13-0024",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais estruturas apontadas pelo alfinete azul e pelo dedo?",
    "a": "alfinete azul- lig. redondo do útero \n\nDedo- lig. suspensor do ovário (contem os vasos ováricos)",
    "frontImage": "genito-urinario/cfa31960-3038-1217-a8ce-794105d6e1d7.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 23
  },
  {
    "id": "gm-13-0025",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "São as divisões da tuba uterina\n\nazul- porção uterina da tuba uterina \nlaranja-istmo da tuba uterina\nbranco-ampola da tuba uterina\nvermelho- infundíbula da tuba uterina",
    "frontImage": "genito-urinario/4a01eac0-32b3-1217-a8ce-794105d6e1d7.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 24
  },
  {
    "id": "gm-13-0026",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "amarelo- labios maiores da vagina\n\nvermelho - Rima do pudendo",
    "frontImage": "genito-urinario/f6f02d90-3737-1217-a8ce-794105d6e1d7.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 25
  },
  {
    "id": "gm-13-0027",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "laranja- ostio externo da uretra\nvermelho- clítoris\nazul- ostio da vagina",
    "frontImage": "genito-urinario/f0a24f20-38c4-1217-a8ce-794105d6e1d7.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 26
  },
  {
    "id": "gm-13-0028",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do ligamento suspensor do ovário?",
    "a": "Vasos ováricos (Sem nervos)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 27
  },
  {
    "id": "gm-13-0029",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura do alfinete azul escuro?",
    "a": "ligamento utero ovarico (próprio do ovário)",
    "frontImage": "genito-urinario/e22f9740-d67e-1219-a2e2-c396852c9ade.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 28
  },
  {
    "id": "gm-13-0030",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome das estruturas apontadas pelos dedos? (dentro do canal vaginal)",
    "a": "Carúnculas himenais\n\n(sem chance de cair//só por desencargo de consciência)",
    "frontImage": "genito-urinario/8e5489d0-d6d5-1219-a2e2-c396852c9ade.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 29
  },
  {
    "id": "gm-13-0031",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome da estrutura no alfiente laranja na bexiga?",
    "a": "úraco obliterado (está na prega umbilical mediana)\n\nOBS- Relacionado com extravasamento de urina pelo umbigo em processos de persistência do úraco",
    "frontImage": "genito-urinario/309d5ce0-d7a2-1219-a2e2-c396852c9ade.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 30
  },
  {
    "id": "gm-13-0032",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da Arteria Iliaca Interna?",
    "a": "Tronco Posterior (3 ramos)\nA. Iliolombar\nAa. Sacrais laterais\nA. Glútea sup\n\n\nTronco Anterior(6 ramos)\nA. Umbilical (gera a A. Vesical sup)\nA. Obturatória\nA. Vesical Inf\nA. Retal Média\nA. Pudenda Interna\nA. Glútea Inf",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 31
  },
  {
    "id": "gm-13-0033",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do Tronco Post da Iliaca INT?",
    "a": "A. Iliolombar\nAa. Sacrais Laterais (duas)\nA. Glútea sup",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 32
  },
  {
    "id": "gm-13-0034",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do tronco ANT da Iliaca INT?",
    "a": "A. Umbilical\nA. Obturatória\nA.Vesical Inf\nA. Retal Média\nA. Pudenda int\nA. Glútea inf\n\nOBS- pode dar A. Uterina e A. Vaginal nas mulheres \n(comum trocar vesical inferior por uterina nas mulheres)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 33
  },
  {
    "id": "gm-13-0035",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação do reto?",
    "a": "A. Retal superior- Ramo da A. Mesenterica Inf\n\nA.Retal Media- Ramo da A. Iliaca Int\n\nA.Retal Inf- Ramo da A. Pudenda Int",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 34
  },
  {
    "id": "gm-13-0036",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o caminho do N. Pudendo? e os seus ramos?",
    "a": "Passa pelo forame isquiático maior saindo e depois pelo forame isquiatico menor voltando para a pelve no canal do N. Pudendo(entre o M. Obturador interno e o Diafragma da pelve)\n\nRAMOS\nR. Dorsal do Pênis/ Clitóris\nR. Perineal\nR. Escrotal posterior\nR. Retal inferior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 35
  },
  {
    "id": "gm-13-0037",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a origem da A. Vesical Superior?",
    "a": "Originada da A. Umbilical",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 36
  },
  {
    "id": "gm-13-0038",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas pelos barbantes e papéis?",
    "a": "papel superior- Espaço Retropúbico\n\nPapel do meio- Escavação Vesicouterina\n\nbarbante amarelo- Escavação retouterina\n\nbarbante vermelho- uretra\n\nBarbante verde- Canal Vaginal",
    "frontImage": "genito-urinario/8e0b2120-f75d-1228-957e-4d6ca258a83d.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 37
  },
  {
    "id": "gm-13-0039",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura sinalizada ?",
    "a": "A. Renal Acessória// A. Polar\n\nresquício embrionário patológico caso seja anterior ao ureter(pode causar hidronefrose por comprimir o ureter)",
    "frontImage": "genito-urinario/2b80f3a0-3c63-123c-b87b-f1a56b58144a.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 38
  },
  {
    "id": "gm-13-0040",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura sinalizada?",
    "a": "cápsula fibrosa do rim",
    "frontImage": "genito-urinario/447d5550-3ee4-123c-b87b-f1a56b58144a.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 39
  },
  {
    "id": "gm-13-0041",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura sinalizada?",
    "a": "sulco balanoprepucial",
    "frontImage": "genito-urinario/af399c70-3f28-123c-b87b-f1a56b58144a.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 40
  },
  {
    "id": "gm-13-0042",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura sinalizada?",
    "a": "bulbo do pênis\n\nOBS- esse pênis está virado (torto)",
    "frontImage": "genito-urinario/ccce9340-3f9f-123c-b87b-f1a56b58144a.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 41
  },
  {
    "id": "gm-13-0043",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura sinalizada?",
    "a": "canal do colo uterino",
    "frontImage": "genito-urinario/41c60930-3fc3-123c-b87b-f1a56b58144a.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 42
  },
  {
    "id": "gm-13-0044",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura sinalizada?",
    "a": "veia dorsal profunda do penis",
    "frontImage": "genito-urinario/b1b2b440-4050-123c-b87b-f1a56b58144a.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 43
  },
  {
    "id": "gm-13-0045",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura sinalizada?",
    "a": "Lig. Suspensor do Penis\n\n(Foto está mal representada)",
    "frontImage": "genito-urinario/b7153240-4079-123c-b87b-f1a56b58144a.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 44
  },
  {
    "id": "gm-13-0046",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas sinalizadas?",
    "a": "Barbante- A. Renal direita\nAlfinete- V. Suprarrenal esq\n\nOBS: A pelve renal é vista melhor posteriormente",
    "frontImage": "genito-urinario/a56d2250-4128-123c-b87b-f1a56b58144a.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 45
  },
  {
    "id": "gm-13-0047",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas sinalizadas?",
    "a": "verde- Mesovário\namarelo-ovário\nverde- mesosalpinge\nazul escuro - Infundíbulo da tuba uterina\nazul claro-lig. próprio do ovário (útero-ovárico)",
    "frontImage": "genito-urinario/9c285440-4df5-1347-9031-0556ba2a088d.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 46
  },
  {
    "id": "gm-13-0048",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "diferencie os pontos:\n\n11,12,26,28,30,",
    "a": "11- Corpo Esponjoso \n\n12- Corpos cavernosos\n\n26-Uretra esponjosa\n\n28- V. Dorsal profunda do pênis\n\n30- Túnica albugínea",
    "frontImage": "genito-urinario/855f3be0-bd9b-137a-8088-55ff7fb77bdf.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 47
  },
  {
    "id": "gm-13-0049",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "explique o caminho que o ducto deferente faz",
    "a": "ele sai da cauda do epidídimo e percorre no funículo espermático até o anel inguinal profundo\n\nrodeia os vasos ilíacos externos e depois a bexiga\n\ndilata-se ( ampola) para formar o ducto ejaculatório com os ductos das glândulas seminais",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 48
  },
  {
    "id": "gm-13-0050",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "explique onde ocorre a vasectomia",
    "a": "corte do ducto deferente no nível do escroto\n\nNão leva mais os espermatozoides produzidos no testículo\n\nOBS- É reversível",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 49
  },
  {
    "id": "gm-13-0051",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação das glândulas seminais?",
    "a": "Aa. para as glândulas seminais (ramos da A. Vesical inf e A. Retal Média)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 50
  },
  {
    "id": "gm-13-0052",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "diferencie os corpos cavernosos e esponjoso",
    "a": "cavernosos: ficam superiormente (dorso)  e possuem os RAMOS  do pênis\n\nesponjoso: possui a uretra e e está inferior- possui o BULBO do pênis",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 51
  },
  {
    "id": "gm-13-0053",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais artérias realizam a ereção quando o pênis está flácido?",
    "a": "Aa. Helicinas são preenchidas pelo sangue vindo das Aa. Profundas do pênis (ramos da A. Pudenda interna)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 52
  },
  {
    "id": "gm-13-0054",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "divida as porções da uretra masculina",
    "a": "Uretra Intramural (próximo a saída da bexiga\n\nUretra Prostática (dentro da próstata)\n\nUretra membranácea (istmo da próstata até o M. esfíncter externo da uretra)\n\nUtetra esponjosa- Pós músculo esfíncter externo da uretra até o final do pênis (dilata-se como fossa navicular)\nOBS- recebe as glândulas bulbouretrais",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 53
  },
  {
    "id": "gm-13-0055",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que a uretra prostática recebe?",
    "a": "seios prostáticos\nUtrículo prostático (útero não desenvolvido)\nColículo Seminal (apenas uma elevação)\nDuctos Ejaculatórios\n\nOBS: As glândulas bulbouretrais",
    "frontImage": null,
    "backImage": "genito-urinario/6ff60ea0-3c00-13d3-956a-41bdeb6f8f37.jpg",
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 54
  },
  {
    "id": "gm-13-0056",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação do escroto?",
    "a": "Aa. Escrotais anterior- Ramos da A. Pudenda externa\n\nAa. Escrotais posteriores- Ramos da A. Pudenda Interna",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 55
  },
  {
    "id": "gm-13-0057",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "diferencie o M. Cremáster e o M. Dartos",
    "a": "M. Cremáster- Realiza o controle da aproximação do escroto ao corpo\n\nM. Dartos- Enrugamento do Escroto + Aproximação \n\nOs dois controlam a temperatura do testículo",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 56
  },
  {
    "id": "gm-13-0058",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ligamentos do ovário?",
    "a": "Lig.Útero ovárico (próprio do ovário)\nLig. Suspensor do ovário\n+ parte do Lig. Largo do Útero (mesoovário)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 57
  },
  {
    "id": "gm-13-0059",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "vermelho- V. Renal Esq",
    "frontImage": "genito-urinario/a0331790-cb9f-137a-8b03-d504a99caa4a.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 58
  },
  {
    "id": "gm-13-0060",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da Vagina?",
    "a": "Aa. Vaginais:\n\nsuperior- A. Uterina\nmédio- A. Vaginal\ninferior-A. Pudenda int",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 59
  },
  {
    "id": "gm-13-0061",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do Diafragma da Pelve? e a inervação?",
    "a": "M. Levantador do Ânus:\n•M. Puborretal\n•M. Pubococcígeo\n•M. Iliococcígeo\n\n(Inervados pelo N. para o M. Levantador do Ânus- direto da raiz S4)\n\n+ M. Isquiococcígeo\n (S4 e S5)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 60
  },
  {
    "id": "gm-13-0062",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do M. Esfíncter externo do ânus?",
    "a": "N. Anal inferior (ramo do N. Pudendo)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 61
  },
  {
    "id": "gm-13-0063",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a raiz do penis?",
    "a": "ramos do pênis e bulbo do pênis",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 62
  },
  {
    "id": "gm-13-0064",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que forma os forames isquiaticos?",
    "a": "Lig. Sacrotuberal\nLig. Sacroespinhal",
    "frontImage": null,
    "backImage": "genito-urinario/89505300-b438-1441-9836-cf09eb925424.jpg",
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 63
  },
  {
    "id": "gm-13-0065",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "um cálculo (nefrolitíase) pode causar o que no sistema pielocalicial?",
    "a": "hidronefrose- Acúmulo de urina- nós cálices (menor e maior) + Pelve renal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 64
  },
  {
    "id": "gm-13-0066",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as camadas de revestimento do escroto?",
    "a": "Externo-> Interno\n\nPele\nTúnica dartos (M. Dartos)\nFáscia espermática externa\nFáscia cremastérica (M. Cremáster)\nFáscia espermática interna\nTúnica Vaginal (Lâmina visceral e parietal)\nTúnica Albugínea\n\n\nOBS- essas camadas são resquícios de outras substâncias: \n\nTúnica dartos\nFáscia espermática externa- M. Oblíquo externo\nFáscia cremastérica- \nM. Oblíquo interno\nFáscia Espermática Interna- Fáscia transversal\nTúnica Vaginal- Peritônio",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 65
  },
  {
    "id": "gm-13-0067",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual zona da próstata dá HPPB e neoplasia?",
    "a": "HPPB- Zona de Transição \n\nNeoplasia- Zona periférica",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 66
  },
  {
    "id": "gm-13-0068",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do M. Cremáster?",
    "a": "Ramo genital do N. Genitofemoral",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 67
  },
  {
    "id": "gm-13-0069",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais músculos comprimem a vagina?",
    "a": "4 músculos\n\nM. Pubovaginal\nM. Esfíncter externo da uretra\nM. Esfíncter Uretrovaginal\nM. Bulbo esponjoso",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 68
  },
  {
    "id": "gm-13-0070",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as posições do útero ?",
    "a": "Em relação à pelve:\nanteversofletido\n\nEm relação à vagina:\nantevertido\n\nsobre ele mesmo:\nantefletido",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 69
  },
  {
    "id": "gm-13-0071",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais são os limites da vagina?",
    "a": "Anterior:  parede posterior da bexiga\n\nPosterior:  parede anterior do reto\n\nsuperior: útero\n\ninferior: vestíbulo vaginal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 70
  },
  {
    "id": "gm-13-0072",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "azul- glândula seminal\n\nverde- ampola do ducto deferente\n\n\nOBS- Ampola do ducto deferente é mais medial",
    "frontImage": "genito-urinario/97c991e0-2c4f-13bc-a2ad-db955403c929.png",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 71
  },
  {
    "id": "gm-13-0073",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "A. Suprarrenal inferior direita",
    "frontImage": "genito-urinario/d23ff210-2dad-13bc-a2ad-db955403c929.jpg",
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 72
  },
  {
    "id": "gm-13-0074",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os pontos de constrição da uretra masculina?",
    "a": "óstio interno da uretra\n\nparte membranácea da uretra\n\nóstio externo da uretra",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 73
  },
  {
    "id": "gm-13-0075",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as divisões do ducto deferente?",
    "a": "Escrotal\nInguinal\nPélvica\nAmpola",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 74
  },
  {
    "id": "gm-13-0076",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da uretra?",
    "a": "XY: Vesical inf e Retal Média\n\nXX: Uterina e Vaginal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 75
  },
  {
    "id": "gm-13-0077",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do períneo anatômico e trígonos urogenital e anal",
    "a": "períneo:\n\nLinhas que ligam o Tuber isquiatico à sínfise púbica e Ápice do cocci\n\nTrígono Urogenital\n\nTransverso superficial do períneo\nTuber isquiatico\nSínfise púbica \n\nAnal:\n\nTuber isquiatico\nTransverso superficial do períneo\nÁpice do cocci",
    "frontImage": null,
    "backImage": "genito-urinario/13cc4f60-4ad5-13fc-b661-e51c280a1c5f.jpg",
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 76
  },
  {
    "id": "gm-13-0078",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos do períneo?",
    "a": "M. Transverso superficial do períneo\n\nM. Bulbo esponjoso\n\nM. Isquiocavernoso\n\nM. Tranverso profundo do períneo\n\nM. Esfíncter ext da uretra\n\nM. Esfíncter ext  do anus",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 77
  },
  {
    "id": "gm-13-0079",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do gubernáculo femino?",
    "a": "Lig. Redondo do útero\nLig. Uteroovarico",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 78
  },
  {
    "id": "gm-13-0080",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do gubernáculo masculino?",
    "a": "camadas do escroto\n\nTúnica dartos- Fascia superficial \n\nFáscia espermática ext- M. Oblíquo ext\n\nFáscia cremastérica-M. Oblíquo int\n \nFáscia espermática int- Fáscia transversal\n\nTúnica Vaginal- Peritônio",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 79
  },
  {
    "id": "gm-13-0081",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os nomes da junções dos lábios maiores do pudendo?",
    "a": "superiormente- Comissura anterior \n\ninferiormente- comissura posterior",
    "frontImage": null,
    "backImage": "genito-urinario/1d21e680-d2b2-145d-a8ca-69e3fadf7135.jpg",
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 80
  },
  {
    "id": "gm-13-0082",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os nomes das junções dos lábios menores do pudendo?",
    "a": "Superiormente- Frênulo do clitóris\n\nInferiormente- Frênulo dos Lábios do pudendo",
    "frontImage": null,
    "backImage": "genito-urinario/fb3ccb90-d34f-145d-a8ca-69e3fadf7135.jpg",
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 81
  },
  {
    "id": "gm-13-0083",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome do espaço da tuba uterina que recebe o oócito 2 ?",
    "a": "Óstio abdominal da tuba uterina\n\nOBS- possui as fímbrias no infundíbulo para \ndirecioná-lo ao local da fecundação  (geralmente a ampola)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 82
  },
  {
    "id": "gm-13-0084",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os casos de hipertensão maligna relacionados com o sistema renal?",
    "a": "Estenose da A. Renal\n(faz com que libere mais Renina, pois o rim entende que está baixa a pressão)\n\nTumor de suprarrenal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 83
  },
  {
    "id": "gm-13-0085",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "em qual ligamento do ovário está os vasos ováricos?",
    "a": "Vasos ováricos",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 84
  },
  {
    "id": "gm-13-0086",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "para onde drenam as Vv. Ováricas?",
    "a": "V. Ovárica direita- VCI\n\nV. Ovárica esquerda- V. Renal esquerda",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 85
  },
  {
    "id": "gm-13-0087",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o principal local de implantação na tuba uterina de uma gravidez ectópica ?",
    "a": "Ampola da tuba uterina",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 86
  },
  {
    "id": "gm-13-0088",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "de onde vem as Aa. Uterinas e Aa. Ováricas?",
    "a": "Aa. Uterinas- A. Ilíaca interna\n\nAa. Ováricas- Aorta abdominal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 87
  },
  {
    "id": "gm-13-0089",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a localização do ureter em relação aos Vasos Uterinos?",
    "a": "Ureter passa por baixo dos Vasos uterinos",
    "frontImage": null,
    "backImage": "genito-urinario/227fb0e0-14d1-146a-bec0-d9d050a7f33e.jpg",
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 88
  },
  {
    "id": "gm-13-0090",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "onde ocorre acúmulo de líquido na pelve feminina?",
    "a": "Escavação Retouterino (saco de douglas)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 89
  },
  {
    "id": "gm-13-0091",
    "cat": 13,
    "src": "ZIP",
    "b": "b-zip",
    "q": "epidimite deve ser palpada em qual porção do escroto?",
    "a": "posteriormente ao escroto",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "GENITO-URINÁRIO- Eduardo Lôbo",
    "deckSlug": "genito-urinario-eduardo-lobo-2e9efe70",
    "deckOrder": 90
  },
  {
    "id": "gm-14-0001",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Quais os musculos anteriores da coxa ? qual a ação deles? qual a inervação?",
    "a": "Fazem parte do Quadríceps femoral;\n\nM. Reto Femoral\nM. Vasto Medial\nM. Vasto Intermédio\nM. Vasto Lateral\n\nREALIZAM FLEXÃO DA COXA E EXTENSÃO DA PERNA\n\nInserção conjunta na tuberosidade da tíbia\n\n+M. Sartório (realiza a ação das pernas cruzadas)\n+M.Iliopsoas\n+M.Pectíneo\n\nInervados pelo N. Femoral\n\n\nOBS- M. Pectíneo possui dupla inervação (+N. Obturatório)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 1
  },
  {
    "id": "gm-14-0002",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Quais os musculos Adutores/ Mediais da coxa? qual a inervação deles?",
    "a": "M. pectíneo (dupla inervação)\nM. Obturador Externo(pelve)\n\nM. Adutor Curto\nM. Adutor Longo\nM. Adutor Magno (dupla inervação) \nM. grácil\n\nINERVADOS PELO N. OBTURATÓRIO\n\nOBS- M. Pectíneo possui inervação do N. Femoral+ \nM. Adutor Magno possui inervação do N. Isquiático",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 2
  },
  {
    "id": "gm-14-0003",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é a pata de ganso?",
    "a": "formado por:\n•M. Sartório\n•M. Grácil\n•M. Semitendíneo \n\n(SGT de anterior para posterior)\n\nOBS- SGT= SarGenTo\n\ninserção conjunta no côndilo medial da tíbia em formato de uma pata  de ganso",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 3
  },
  {
    "id": "gm-14-0004",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "verde- M. Piriforme\nAmarelo-M. Gemeo sup\npreto- M. obturador  int\nAzul- M. Gemeo Inf\nVermelho-M. Quadrado Femoral\n\nPromovem a rotação lateral e estabilidade da pelve",
    "frontImage": "mmii/b980e6f0-dffb-11b6-973d-258c32413666.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 4
  },
  {
    "id": "gm-14-0005",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Quais as estruturas apontadas? e sua inervação",
    "a": "Medial-> lateral:\n\nAzul-M. Tibial anterior\nPreto-Extensor Longo do Hálux\nAmarelo-Extensor Longo dos dedos\n\ninervação: N. fibular profundo- rodeia a cabeça da fíbula e se anterioriza para inervar o compartimento anterior da perna",
    "frontImage": "mmii/6473fdc0-e738-11b6-973d-258c32413666.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 5
  },
  {
    "id": "gm-14-0006",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Quais são as estruturas apresentadas? e qual a inervação?",
    "a": "verde-M. abdutor do dedo mínimo (N. Plantar lateral)\n\namarelo-M. Flexor curto dos dedos (N. Plantar medial)\n\nazul-M. abdutor do hálux\n(N. Plantar medial\n\n\nOBS- Nervo Plantar medial e lateral são ramos terminais do N. Tibial",
    "frontImage": "mmii/b1591380-f3bf-11b6-973d-258c32413666.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 8
  },
  {
    "id": "gm-14-0007",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais musculos estão na porção posterior da perna? e qual a inervação?",
    "a": "4 Músculos superficiais:\nM. Poplíteo\nM. Plantar\nM. Gastrocnêmio\nM. Sóleo\n\n3 músculos Profundos:\n\nmedial-> Lateral:\n\nM. tibial posterior\nM. flexor Longo dos dedos\nM. flexor Longo do Hálux\n\n• Inervados pelo N. Tibial",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 9
  },
  {
    "id": "gm-14-0008",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais sao as estruturas apontadas? e qual a inervação?",
    "a": "verde- M. lumbricais \n1º- N. Plantar medial)\n2º ao 4º- N. Plantar lateral)\n\nAzul-M. quadrado plantar\n(N. Plantar lateral)",
    "frontImage": "mmii/6bb88ab0-5619-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 10
  },
  {
    "id": "gm-14-0009",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais sao as estruturas apontadas? qual a inervação?",
    "a": "azul- M. Adutor do hálux\n( N. Plantar Lateral\n\nVermelho-M. flexor curto do Hálux (N. Plantar medial)\n\nAmarelo- M. flexor do dedo mínimo( N. Plantar lateral",
    "frontImage": "mmii/13da4630-57bd-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 11
  },
  {
    "id": "gm-14-0010",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais sao as estruturas apontadas? qual a inervação?",
    "a": "(SÓ POR DESENCARGO DE CONSCIÊNCIA )\n\namarelo- interósseos dorsais(4)\nVermelho- interósseos plantares(3 apenas)\n\nInervados pelo N. Plantar lateral",
    "frontImage": "mmii/51146c70-587a-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 12
  },
  {
    "id": "gm-14-0011",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas? qual a inervação?",
    "a": "Azul- Extensor curto do halux\nPreto- Extensor curto dos dedos\n\nInervados pelo N. Fibular comum que ultrapassa por baixo do retináculo dos extensores para inervá-los",
    "frontImage": "mmii/2c92db40-5945-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 13
  },
  {
    "id": "gm-14-0012",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais são as estruturas apresentadas?",
    "a": "Amarelo-N. Subcostal\n\nRoxo- N. Iliohipogastrico\n\nAzul- N. ilioinguinal- participa do canal inguinal\n\nVerde- N. Cutâneo Femoral Lateral (Lesão causa meralgia parestésica- inerva sensitivamente a porção mais lateral da coxa)",
    "frontImage": "mmii/8f03fa40-9854-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 15
  },
  {
    "id": "gm-14-0013",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas e suas inervações?",
    "a": "verde- N. Genitofemoral com dois ramos; Ramo genital e Ramo Femoral \n\nOBS- Ramo genital é mais medial\n(Anterior ao Psoas maior)\n•O ramo Genital Participa do funículo espermático nos homens•\n\nvermelho- N. obturatório, passa pelo forame obturatório e inerva a porção medial da coxa\n(medial ao Psoas maior)\n\nAzul- Nervo Femoral, inerva a porção anterior da coxa\n(Lateral ao Psoas maior)",
    "frontImage": "mmii/08448dd0-9a34-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 16
  },
  {
    "id": "gm-14-0014",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Cutâneo femoral lateral?",
    "a": "meralgia parestésica na porção mais lateral da coxa, ele é apenas sensitivo. \n\nLesão causada Principalmente  por causa de obesidade",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 17
  },
  {
    "id": "gm-14-0015",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Femoral?",
    "a": "Marcha alemã/prussiana, pois não consegue fazer flexão da coxa e extensão da perna",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 18
  },
  {
    "id": "gm-14-0016",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Obturatório?",
    "a": "Marcha Ceifante, causa uma maior ação dos musculos abdutores e pouco fechamento das coxas ao andar, pois esse nervo inerva os Músculos da margem medial da coxa, os adutores;\n\nM. Adutor Magno (Dupla inervação)\nM. Adutor curto\nM. adutor Longo\nM. Grácil",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 19
  },
  {
    "id": "gm-14-0017",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Glúteo Sup?",
    "a": "Marcha glútea/miopática , pois inerva o glúteo medio e mínimo, tendo o glúteo medio como o principal estabilizador da pelve e abdutor dos membros inferiores \n\nOBS- Dá o Sinal de trendelenburg positivo, não consegue fazer apoio unipodal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 20
  },
  {
    "id": "gm-14-0018",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. isquiático?",
    "a": "Marcha cambaleante\n\n o N. isquiático inerva a porção posterior da coxa( apenas motor nessa parte), na perna e no pé ele é motor e sensitivo",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 21
  },
  {
    "id": "gm-14-0019",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N.Fibular comum?",
    "a": "Marcha escarvante (Pé Caído), pois não conseguem fazer a extensão, andam arrastando a ponta do pé, está ligada com a fratura da cabeça/colo da fíbula\n\né um ramo do N. Isquiático( o qual bifurca-se na região da fossa poplítea). Ele inerva a região anterior da perna",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 22
  },
  {
    "id": "gm-14-0020",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesao do N. Fibular profundo?",
    "a": "Marcha escarvante (Pé Caído) \n\nO Nervo Passa anterior à membrana interóssea(após rodear a cabeça da fíbula e se anteriorizar) e inerva a porção anterior da perna (Pé caído por não fazer extensão// dorsiflexão)\n\né um ramo do N. Fibular comum",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 23
  },
  {
    "id": "gm-14-0021",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Tibial?",
    "a": "Marcha calcânea, andar apoiado apenas no calcâneo, impede a flexão plantar, inerva a porção posterior da perna",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 24
  },
  {
    "id": "gm-14-0022",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas sinalizadas?",
    "a": "azul- N. isquiático + A. para o N. Isquiatico (ramo da A. Glutea Inf) desce na região posterior proximo ao fêmur, ligado a fraturas desse osso\n\nVerde- N. glúteo inf\n\nVermelho- N. Glúteo Sup\n\nAmarelo- N. Pudendo\n\nOBS- Entre os Nervos isquiático e Pudendo, Há o N. Cutâneo femoral posterior",
    "frontImage": "mmii/16304650-a10a-11b7-973d-258c32413666.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 25
  },
  {
    "id": "gm-14-0023",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. isquiático",
    "a": "Ele inerva a porção posterior da coxa (apenas de forma motor), a perna  e o pé ele é misto\n\nLesão: Marcha Cambaleante\n(relacionada com síndrome do piriforme <compressão> e com ciclistas que se apoiam durante muito tempo sobre a região )\n\nDivide-se na região poplítea em N. tibial e N. fibular comum",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 27
  },
  {
    "id": "gm-14-0024",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais são os ramos da /A. Ilíaca Ext?",
    "a": "A. epigástrica inf (medial)\nA. Circunflexa Ilíaca profunda (lateral)\n\nTorna-se A. Femoral após o lig. Inguinal",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 30
  },
  {
    "id": "gm-14-0025",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Quais os ramos da A. Femoral ?",
    "a": "A. FEMORAL DÁ OS SEGUINTES RAMOS;\n6 ramos: \n\nque vão para Medial;\nA. Epigástrica superficial\nA. Pudenda Ext Superficial\nA. Pudenda Ext Profunda\n\nque vão para Lateral:\nA. Circunflexa Ilíaca superficial\nA. Femoral profunda\n\nPróximo ao canal dos adutores da o R. Genicular descendente\n\n\nOBS- O netter não retrata a A. Femoral Comum ou Superficial. Existe apenas a A. Femoral que dá o ramo A. Femoral profunda ( após dar o ramo, ela continua sendo apenas A. Femoral)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 31
  },
  {
    "id": "gm-14-0026",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Femoral profunda?",
    "a": "Principal nutrição da coxa\n\nA. Circunflexa femoral Lateral\nA. Circunflexa femoral Medial\n+Ramos perfurantes(3)\n+Ramos musculares",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 32
  },
  {
    "id": "gm-14-0027",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a anastomose cruciforme",
    "a": "anastomose na região superior da coxa e da região glútea\n\nA. Circunflexa femoral Lateral(ramo da A. Femoral profunda)\n\nA. Circunflexa femoral medial(ramo da A. Femoral profunda)\n\nA. glútea inferior (ramo do Tronco anterior da A. Iliaca interna)\n\n1º Ramo perfurante (ramo da A. femoral profunda)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 33
  },
  {
    "id": "gm-14-0028",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "diga os limites e conteúdo da fosse poplítea",
    "a": "Limites:\n\nSuperolateral: cabeça longa do M. Bíceps Femoral\nSuperomedial:\nM.Semimembranáceo \nInferior: M.Gastrocnêmico\n\nConteúdo:\nMedial-> lateral\nA. Poplítea\nV. Poplítea \nN. Tibial\nN. fibular comum\n\n+\nN. Cutâneo femoral posterior(ramo do plexo sacral S1, S2, S3)\nLinfonodos poplíteos\nV. Safena Parva",
    "frontImage": null,
    "backImage": "mmii/f328b050-14a6-11b8-973d-258c32413666.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 35
  },
  {
    "id": "gm-14-0029",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Poplítea?",
    "a": "São 6 seguindo a sequencia:\nA.DO JOELHO/A.GENICULAR\n\nA. Sup. Medial Do joelho\nA. Sup. Lateral do joelho\n\nA. Media do joelho\n\nA. Inf. Medial do joelho\nA. Inf Lateral do joelho\n\n++ Aa. Surais (desencargo de consciência)\n\n\nPÓS JOELHO:\n\nA. Tibial anterior\nA. Tibial Posterior\n\nOBS- Netter não retrata como Tronco tibiofibular e A. Tibial anterior (apenas terminando em A. Tibial anterior e A. Tibial posterior-- A. Fibular é ramo da A. Tibial posterior)",
    "frontImage": null,
    "backImage": "mmii/3fc338e0-b667-11ba-925d-0d4fd56ffb14.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 37
  },
  {
    "id": "gm-14-0030",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual Drenagem venosa Superficial da perna e formação?",
    "a": "Medial-V. Safena Magna- passa anterior ao maléolo medial e tributa na V. Femoral ao atravessar o hiato safeno\n•Acompanhada do N. safeno•\n\nformada a partir do arco venoso dorsal do pé+ V. Dorsal do halux\n\nLateral- V. Safena Parva- tributa na V. Poplítea (passa posterior ao maléolo lateral e caminha entre as cabeças do gastrocnêmio)\n\nformada a partir do arco venoso dorsal do pé + V. Dorsal do 5º dedo\n•Acompanhada do N. Sural•",
    "frontImage": null,
    "backImage": "mmii/57d124c0-1d1b-11b8-973d-258c32413666.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 39
  },
  {
    "id": "gm-14-0031",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os Limites do Canal Dos Adutores e conteúdo?",
    "a": "Anterolateral:M. Vasto Medial\nMedial e superior :M. Sartório\nPosterior e inferior: Adutor longo e Adutor magno\n\nVasos femorais \n\nLeva os vasos femorais  que trocam de posição e nome após atravessar o hiato dos adutores. Passam a ser chamados de Vasos poplíteos\n\nA. Poplítea passa a ser mais medial que a V. Poplítea",
    "frontImage": null,
    "backImage": "mmii/b0971240-bb6b-11ba-925d-0d4fd56ffb14.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 41
  },
  {
    "id": "gm-14-0032",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apresentada pelos pontos pretos?",
    "a": "M. e Tendão do Fibular 3º . Atua na Extensão// dorsiflexão do pé",
    "frontImage": "mmii/4e4c46e0-caf3-11ba-925d-0d4fd56ffb14.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 42
  },
  {
    "id": "gm-14-0033",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas? qual o conteúdo?",
    "a": "pinça- retináculo dos fibulares\n\nConteúdo; \n\nVerde- Tendão do M. Fibular curto (insere- se na tuberosidade do 5º metatarso)\n\nAmarelo- Tendão do M. Fibular Longo",
    "frontImage": "mmii/63ba6f90-cb41-11ba-925d-0d4fd56ffb14.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 43
  },
  {
    "id": "gm-14-0034",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apresentadas? alfinete preto e vermelho? Qual a inervação?",
    "a": "Preto- M. Plantar\nvermelho- Tendão do M. Plantar\n\nInervado pelo N. Tibial",
    "frontImage": "mmii/e90f0030-ce29-11ba-925d-0d4fd56ffb14.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 44
  },
  {
    "id": "gm-14-0035",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apresentadas nesse retináculo?",
    "a": "Retináculo dos flexores\n\nConteúdo;\n\nanterior-> posterior\n\nTP FL VAN do HALUX\n\nOBS- T. = Tendão\n\nT. do M. Tibial post\nT. do M. Flexor longo dos dedos\nVAN tibial posterior (Nervo é só N. Tibial)\nT. Do M. Flexor longo do hálux",
    "frontImage": "mmii/e22429e0-d134-11ba-925d-0d4fd56ffb14.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 46
  },
  {
    "id": "gm-14-0036",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada? qual a inervação?",
    "a": "M. Quadrado Plantar- por baixo do M. flexor curto dos dedos\n\nInervado pelo N. Plantar lateral",
    "frontImage": "mmii/9e915b30-e549-11c3-a34c-bf8a715d2244.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 47
  },
  {
    "id": "gm-14-0037",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais são os abdutores da coxa?",
    "a": "Glúteo Médio e Mínimo, realizam abdução (os mais importantes) e são inervados pelo N.glúteo superior- LESÃO: MARCHA GLÚTEA",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 48
  },
  {
    "id": "gm-14-0038",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais são os musculos isquiotibiais? qual a inserção deles?",
    "a": "M. Semitendíneo\nM. Semimembranáceo \nCabeça longa do M. Bíceps femoral\n\nInervados pelo N. Tibial\n\nSão os músculos do jarrete//\nRealizam extensão da coxa e flexão da perna\n\nInserção NÃO É conjunta na tíbia, mas a origem é comum no TÚBER ISQUIÁTICO\n(por isso são chamados de Isquiotibiais)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 51
  },
  {
    "id": "gm-14-0039",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é o trato iliotibial?",
    "a": "espessamento da fáscia lata que vai até o tuberculo de gerdy na tibia\n\nOBS- Trato iliotibial é o local de inserção do M. Tensor da Fáscia Lata",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 52
  },
  {
    "id": "gm-14-0040",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "por que pode existir uma lesão nervosa ao ter a cabeça da fíbula atingida por um impacto? qual o nome da marcha?",
    "a": "Porque o N. Fibular Comum passa lateralmente à cabeça da fíbula, podendo sofrer lesões com impacto nesse local\n\nLesão: Marcha escarvante",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 53
  },
  {
    "id": "gm-14-0041",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos mais importantes da A. Tibial Posterior?",
    "a": "A. Tibial posterior mais importante irrigamento sanguíneo do pé\n\nEla dá A. Fibular (que não atinge o pé)\n\nRamos terminais:\nA. Plantar Lateral\nA. Plantar Medial",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 56
  },
  {
    "id": "gm-14-0042",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos terminais do N. Tibial? o que eles inervam?",
    "a": "N. Plantar Medial :\n3 músculos e 0,1\n\nM. Abdutor do hálux\nM. Flexor Curto dos dedos\nM. Flexor curto do Hálux\n+ 1º Lumbrical\n \nN. Plantar Lateral \n3 músculos + Ramo profundo do N. Plantar lateral inerva mais 3:\n\nM. Abdutor do dedo mínimo\nM. Flexor curto do dedo mínimo\nM. Quadrado plantar\n\n\nR. Profundo;\nM. Adutor do Hálux\n2º ao 4º lumbricais\nTodos os interósseos plantares(3) e dorsais(4)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 57
  },
  {
    "id": "gm-14-0043",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "A. Dorsal do pé(pulso pedioso). Está lateral em relação ao tendao do extensor longo halux\n\ncontinuação da A. Tibial anterior(pós retináculo dos extensores)",
    "frontImage": "mmii/d04c5870-0e74-11c3-b344-6d69616151c6.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 58
  },
  {
    "id": "gm-14-0044",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura?",
    "a": "A. Femoral profunda, ramo  da A. Femoral.\n\nprincipal fonte sanguínea da coxa",
    "frontImage": "mmii/7e4bbca0-38d6-11c3-a34c-bf8a715d2244.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 59
  },
  {
    "id": "gm-14-0045",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura? e qual a inervação?",
    "a": "Trato iliotibial, é oriundo do espessamento da fascia lata e é tensionado pelo M. Tensor da fascia Lata- INERVADO PELO\n N.GLÚTEO SUPERIOR\n\n\n\nOBS- Fáscia lata está aderida aos músculos",
    "frontImage": "mmii/f1e16570-3845-11c3-a34c-bf8a715d2244.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 60
  },
  {
    "id": "gm-14-0046",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apresentada?",
    "a": "N. Pudendo- emerge pelo forame isquiático maior e depois passa pelo forame isquiatico menor(formado pelo lig. sacrotuberal)\n\nOBS- Não pode ser o N. Cutâneo Femoral posterior, pois não está colado no N. Isquiático e esse nervo está seguindo pelo forame isquiatico menor",
    "frontImage": "mmii/b1deb280-4ad2-11c3-a34c-bf8a715d2244.jpg",
    "backImage": "mmii/d94a0980-8293-136b-9780-b10ab99f5338.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 62
  },
  {
    "id": "gm-14-0047",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura sinalizada pelo dedo? qual a inervação?",
    "a": "tendao do M. Fibular Terceiro\n\nN. Fibular profundo",
    "frontImage": "mmii/814477e0-da74-11c3-a34c-bf8a715d2244.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 63
  },
  {
    "id": "gm-14-0048",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "Qual o conteúdo do túnel do tarso?",
    "a": "Mesma coisa que Retináculo dos flexores\n\nAnterior para posterior- \nTP FL VAN do HALUX\n\nTendao do M. Tibial Posterior\n\nTendao do Musculo Flexor longo dos dedos\n\nVasos Tibiais posteriores\n\nN. Tibial\n\nTendao do M. Flexor longo do halux",
    "frontImage": null,
    "backImage": "mmii/71ce48f0-dc1c-11c3-a34c-bf8a715d2244.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 64
  },
  {
    "id": "gm-14-0049",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura sinalizada? qual a lesão?",
    "a": "N. Cutâneo femoral lateral-\nEstá emergindo e passando por baixo da crista ilíaca e dentro da pelve para a lateral da coxa\n\n Lesão: meralgia parestésica",
    "frontImage": "mmii/784ebe60-6672-136b-9780-b10ab99f5338.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 65
  },
  {
    "id": "gm-14-0050",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura sinalizada?",
    "a": "vermelho esquerdo- Vasos Glúteos superiores\n\nAmarelo- N. Glúteo sup- lesao: marcha glútea, inerva os principais abdutores; Mm. Glúteo medio e minimo\n\nponto branco- M. piriforme\n\nVermelho direito- N. Isquiático- inerva a porção posterior da coxa, perna e pé (Lesao: marcha cambaleante)",
    "frontImage": "mmii/1c555020-de7a-11c3-a34c-bf8a715d2244.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 66
  },
  {
    "id": "gm-14-0051",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os pontos amarelo e vermelho do meio marcados?",
    "a": "Os ramos da A. Femoral\n\namarelo- A. Circunflexa ilíaca superficial (Lateral)\n\nvermelho- A. Epigástrica superficial (Medial)",
    "frontImage": "mmii/1e2270b0-639d-11c4-abeb-73318fb534da.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 70
  },
  {
    "id": "gm-14-0052",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina o quiasma plantar",
    "a": "X organizado pelos tendões do M. flexor longo dos dedos e M. flexor longo do hálux",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 73
  },
  {
    "id": "gm-14-0053",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os pontos laranjas?",
    "a": "São os ramos da A. Circunflexa femoral lateral\n\nSuperior: Ramo Ascendente \nMédio:Ramo Transverso\nInferior:Ramo Descendente",
    "frontImage": "mmii/dd704b90-74c3-11c4-abeb-73318fb534da.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 74
  },
  {
    "id": "gm-14-0054",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a localização da V. Safena magna e V. Safena Parva em relação aos maleolos? o que acompanha elas?",
    "a": "V. Safena parva- está posterior ao maleolo lateral\nAcompanhada do N. Sural\n\nV. Safena magna- está anterior ao maleolo medial\nAcompanhado do N. Safeno",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 76
  },
  {
    "id": "gm-14-0055",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é a tendinite anserina? onde eles se inserem?",
    "a": "inflamação do tendão anserino/ tendao da pata de ganso.\n\nInflamação nos tendões do M. Grácil, M. Sartório e M. Semitendíneo\n\nse inserem em conjunto no condilo medial da tíbia",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 77
  },
  {
    "id": "gm-14-0056",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual é o '' 5º tendão'' do M. Quadríceps Femoral?",
    "a": "(desencargo de consciência pra monitoria)\n\nM. articular do joelho",
    "frontImage": null,
    "backImage": "mmii/5972d760-f026-145e-8d33-0389727e56c8.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 79
  },
  {
    "id": "gm-14-0057",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual músculo se insera na tuberosidade do 5º metatarso?",
    "a": "M. Fibular curto",
    "frontImage": null,
    "backImage": "mmii/e8a3ce00-8c48-1359-af08-5119b6c9f6f8.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 80
  },
  {
    "id": "gm-14-0058",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "N. Cutaneo femoral lateral",
    "frontImage": "mmii/1fa824b0-f446-135c-b0ea-9d9be027019e.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 81
  },
  {
    "id": "gm-14-0059",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada pelo alfinete?",
    "a": "N. Ilioinguinal",
    "frontImage": "mmii/8fc247d0-f464-135c-b0ea-9d9be027019e.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 82
  },
  {
    "id": "gm-14-0060",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. Cutâneo femoral posterior",
    "a": "passa superficial ao M. Semitendíneo e inerva sensitivamente a porção posterior da coxa",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 83
  },
  {
    "id": "gm-14-0061",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a principal artéria que irriga o  Pé?",
    "a": "A. Tibial posterior",
    "frontImage": null,
    "backImage": "mmii/af07f0c0-a42f-136b-bd6e-975666b455ef.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 84
  },
  {
    "id": "gm-14-0062",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do canal inguinal?",
    "a": "OBS- APENAS PARA A MONITORIA!!\n\nAnel inguinal profundo (interno)\n\nAnel inguinal superficial (externo)\n\nLimites:\nAnterior: Aponeurose do M. Oblíquo ext\nPosterior: Fáscia Transversal\nTeto: aponeuroses dos Músculo Interno e Transverso do Abdômen\nAssoalho: Lig. Inguinal e Lig. Lacunar\n\nConteúdo:\nH- N. Ilioinguinal + Funículo Espermático\nM-N. Ilioinguinal+ Lig. Redondo do Útero",
    "frontImage": null,
    "backImage": "mmii/9271dca0-a687-136b-bd6e-975666b455ef.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 85
  },
  {
    "id": "gm-14-0063",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do Funículo espermático?",
    "a": "7 estruturas\n\nA. Cremastérica\nA. Do ducto deferente\nA. Testicular\nDucto deferente\nPlexo Pampiniforme\nRamo genital do N. Genitofemoral\nM. Cremáster",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 86
  },
  {
    "id": "gm-14-0064",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites do trígono inguinal ?",
    "a": "Trígono Inguinal/ Hasselbach\n\nLimites:\nMedial- Borda lateral do M. Reto Abdominal\nLateral- Vasos epigástricos inferiores\nInf- Lig. Inguinal\n\n\nHérnia Inguinais diretas são dentro do trígono. Indiretas são laterais aos vasos epigástricos inferiores// Fora do trígono",
    "frontImage": null,
    "backImage": "mmii/430c9e50-f3a2-145e-8d33-0389727e56c8.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 87
  },
  {
    "id": "gm-14-0065",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Tibial anterior?",
    "a": "Ela encontra-se anterior (passa a Membrana interóssea)\nEntre o M. Tibial Ant e o M. Extensor Longo do Hálux\n\nContinua como A. Dorsal do Pé (pós retináculo dos extensores) e dá os ramos no dorso do pé:\n\nA. Maleolar lateral e medial\nA. Arqueada (da os ramos metatarsais dorsais)\nA. Plantar profunda",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 89
  },
  {
    "id": "gm-14-0066",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e conteúdo do trígono femoral?",
    "a": "limites:\nsup: Lig. Inguinal\nLateral: Sartório\nMedial: M. Adutor Longo\nAssoalho:\n M. Pectíneo(medial) e M. Iliopsoas (lateral)\nteto: Fáscia lata\n\nConteúdo:\nMedial-> lateral\nVAN femoral\n\n\nOBS- V. Safena Magna vai tributar na V. Femoral ao atravessar o hiato safeno",
    "frontImage": null,
    "backImage": "mmii/cde56950-b12c-136b-bd6e-975666b455ef.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 90
  },
  {
    "id": "gm-14-0067",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. Femoral",
    "a": "origem dentro do Psoas maior e passa a ser lateral a ele. Trígono femoral se divide em ramos (principalmente o N. Safeno- inerva a porção anterolateral da perna e do pé- acompanha a V. Safena Magna-\n\nLesão: Marcha prussiana",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 91
  },
  {
    "id": "gm-14-0068",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. Obturatório",
    "a": "Emerge medial ao Psoas maior e desce pelo forame obturatório para inervar a região medial da coxa (divide-se em ramos anterior  e posterior e passa pelo obturador externo dividido)\n\nLesão: Marcha ceifante",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 92
  },
  {
    "id": "gm-14-0069",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. Isquiático",
    "a": "Emerge do recesso infrapiriforme e inerva os músculos do jarrete (posterior da coxa) e divide-se em N. Tibial e N. fibular comum na fossa poplítea\n\nLesão: Marcha cambaleante",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 93
  },
  {
    "id": "gm-14-0070",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. Glúteo sup",
    "a": "Emergem do recesso suprapiriforme\nInerva o M. Glúteo medio e M. Glúteo Mínimo\n\nrealizam abdução da coxa\n\nLesão: Marcha Glútea (Sinal de trendelenburg positivo)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 94
  },
  {
    "id": "gm-14-0071",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. Sural",
    "a": "OBS- Monitoria apenas!!\n\nformado pelo N. Sural medial (N. Tibial) e N. Sural Lateral a partir do N.  Fibular Comunicante  (N. Fibular Comum)\n\nDesce junto com a V. Safena parva e inerva sensitivamente a porção posterolateral da perna",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 95
  },
  {
    "id": "gm-14-0072",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. Safeno",
    "a": "Ramo terminal do N. Femoral que acompanha a V. Safena Magna e inerva sensitivamente a porção anterolateral da perna e do pé",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 96
  },
  {
    "id": "gm-14-0073",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. Fibular profundo",
    "a": "ele ultrapassa a membrana interóssea para inervar o compartimento anterior da perna e do dorso do pé\n\nOBS- Passa por dentro do retináculo dos extensores\n\nLesão: Marcha Escarvante (Pé em gota)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 97
  },
  {
    "id": "gm-14-0074",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. Fibular superficial",
    "a": "Emerge da divisão do fibular comum e vai entre o M. Fibular Longo e Curto\n\ninerva os músculos: \nFibular Longo e Fibular curto e sensitivamente a região anterior da perna",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 98
  },
  {
    "id": "gm-14-0075",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina a inervação do N. Tibial",
    "a": "Emerge após a divisão do N. Isquiático\n\nLocaliza- se sobre o M. Tibial post (posterior ao M. Sóleo) e inerva o compartimento post da perna\n\nDivide- se pós retináculo dos flexores em:\nN. Plantar medial e lateral\npara inervar a planta do pé\n\nLesão: Marcha Calcânea",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 99
  },
  {
    "id": "gm-14-0076",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do tendão do calcâneo? e sua inervação?",
    "a": "M. Gastrocnêmio\nM. Sóleo\nM. Plantar  (Músculo da bailarina)\n\nInervados pelo N. Tibial\n\n(OBS- M. Poplíteo também é inervado pelo N. Tibial, mas não participa do tendão do calcâneo)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 101
  },
  {
    "id": "gm-14-0077",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do retináculo dos extensores?",
    "a": "medial-> lateral\n\nT. do Tibial Anterior\nA. Dorsal do Pé\nN. Fibular profundo\n(divergem quanto a lateralidade da arteria e nervo)\nT. Do extensor longo do hálux\nT. Do extensor longo dos dedos\nT. do Fibular Terceiro",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 102
  },
  {
    "id": "gm-14-0078",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas que formam o tríceps sural?",
    "a": "Cabeça medial e lateral do M. Gastrocnêmio e M. Sóleo",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 103
  },
  {
    "id": "gm-14-0079",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do arco plantar profundo?",
    "a": "A. Plantar lateral que se curva e recebe também o Ramo plantar profundo da A. Dorsal do pé",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 104
  },
  {
    "id": "gm-14-0080",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "N. Genitofemoral \n(anterior ao M. Psoas maior)\n\nvermelho- Ramo genital \n(funículo espermático)\nverde- Ramo femoral",
    "frontImage": "mmii/c7ee5930-66c8-136f-96da-1bf036096190.jpg",
    "backImage": "mmii/add52c20-66d4-136f-96da-1bf036096190.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 105
  },
  {
    "id": "gm-14-0081",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do M. Bíceps femoral?",
    "a": "Cabeça longa(''em cima'' da cabeça curta e medial) - faz parte dos músculos do jarrete\nN. Tibial\n\nCabeça curta (lateral)- não faz parte dos músculos isquiotibiais\nN. Fibular comum",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 106
  },
  {
    "id": "gm-14-0082",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais nervos suprem os compartimentos da perna?",
    "a": "N. Fibular profundo- motricidade e sensibilidade da porção anterior da perna\n+parte do dorso do pé\n\nN. Fibular superficial- Motricidade e sensibilidade da porção lateral da perna + parte do dorso do pé \n\nN. Tibial- Motricidade e sensibilidade da porção posterior da perna\n\nN. Safeno- Sensibilidade da porção antero medial da perna e pé\n\nN. sural- Sensibilidade da porção postero lateral da perna e pé",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 107
  },
  {
    "id": "gm-14-0083",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais artérias suprem os compartimentos da perna?",
    "a": "A. Tibial anterior- Irriga a porção anterior da perna e pós retináculo dos extensores dá os ramos Tarsais lateral e mediais e se continua como artéria dorsal do pé\n\nA. Tibial posterior- Irriga a porção posterior da perna e quando passa pelo retináculo dos flexores dá os ramos; A. Plantar lateral e A. Plantar medial \n\n A. Fibular: Ramo da A. Tibial posterior e irriga a porção lateral da perna  (dá apenas ramos calcâneos no pé)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 108
  },
  {
    "id": "gm-14-0084",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a anastomose do joelho?",
    "a": "A. Recorrente tibial anterior (Ramo da A. Tibial Ant)\nA. Genicular sup lateral \nA. Genicular sup  medial\nA. Genicular inf lateral\nA. Genicular inf medial\nA. Genicular média\nAa. Surais\nA. Descendente do joelho (A. Femoral)\nA. Descendente da A. Circunflexa femoral lateral",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 109
  },
  {
    "id": "gm-14-0085",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inserção do M. Tibial anterior, M. Sóleo, M. Gastrocnêmio e M. Plantar? qual a ação deles?",
    "a": "OBS- MONITORIA APENAS!!\n\nM. Tibial anterior-\nDorsiflexão + Inversão do pé\n•inserção: cuneiforme medial e base do 1º metatarso\n(N. Fibular profundo)\n\nM. Sóleo, Gastrocnêmio e Plantar- realiza flexão plantar\n•inserção: superfície posterior do calcâneo\n(N. Tibial)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 110
  },
  {
    "id": "gm-14-0086",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inserção e a ação do M. Fibular curto e M. Fibular terceiro?",
    "a": "OBS- MONITORIA APENAS!!\n\nM. Fibular curto-\nRealiza Eversão do pé\n•inserção: Tuberosidade do 5º metatarso\n(N. Fibular superficial)\n\nM. Fibular terceiro- Realiza eversão do pé\n•Inserção: Dorso do 5º metatarso \n(N. Fibular profundo)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 111
  },
  {
    "id": "gm-14-0087",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais músculos tem origem no Tuber Isquiatico?",
    "a": "OBS- MONITORIA APENAS!!\n\nM. Isquiococcígeo\nM. Semitendíneo\nM. Semimembranáceo\nM. Bíceps femoral (Cabeça longa)\nM. Gêmeo inf\nM. Quadrado femoral\nM. Adutor magno (parte do jarrete)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 112
  },
  {
    "id": "gm-14-0088",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a anastomose da\n A. Ilíaca ext e da A. Ilíaca interna?",
    "a": "OBS- MONITORIA APENAS!!\n\nAnastomose entre:\nA. Ilíaca INT dá o ramo A. Obturatória\n\nA. Ilíaca EXT dá o ramo A. Obturatoria acessória (ramo da A. Epigástrica inferior)\n\nOBS- algumas vezes, a A. Obturatória sai da Ilíaca externa",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 113
  },
  {
    "id": "gm-14-0089",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual aa estrutura apresentada? qual a formação?",
    "a": "N. Sural\n\nN. sural medial (ramo do N. Tibial) + N. Fibular comunicante do N. Fibular comum",
    "frontImage": "mmii/c7663680-dc17-13d3-a719-0dcaa380b7be.jpg",
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 114
  },
  {
    "id": "gm-14-0090",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "de onde vem cada nervo cutaneo dorsal ? quais os ramos terminais ?",
    "a": "N. cutâneo dorsal medial -\nN. Fibular superficial\n\nN. cutâneo dorsal intermédio- N. Fibular superficial\n\nN. Cutâneo dorsal lateral- \nN. Sural\n\n\nRamos terminais: Rr.  digitais dorsais",
    "frontImage": null,
    "backImage": "mmii/2f272e20-a35a-1404-a6b0-d10825711520.jpg",
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 115
  },
  {
    "id": "gm-14-0091",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a principal irrigação da cabeça do fêmur?",
    "a": "A. Circunflexa femoral medial",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 116
  },
  {
    "id": "gm-14-0092",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Circunflexa femoral lateral?",
    "a": "R. Ascendente\nR. Transverso\nR. Descendente\n\n\nOBS- O ramo descendente segue para participar da anastomose do joelho",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 117
  },
  {
    "id": "gm-14-0093",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Circunflexa femoral medial?",
    "a": "R. Superior\nR. Médio\nR. Inferior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 118
  },
  {
    "id": "gm-14-0094",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do trígono femoral? qual a relação de lateralidade do conteúdo?",
    "a": "De medial para lateral:\n\nVAN Femoral\n\nV. Femoral\nA. Femoral\nN. Femoral",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 119
  },
  {
    "id": "gm-14-0095",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites do trígono femoral?",
    "a": "Superior: Ligamento Inguinal\n\nlateral: M. Sartório\n\nMedial: M. Adutor longo\n\nAssoalho medial: M. Pectíneo\n\nAssoalho lateral: M. Iliopsoas\n\nTeto: Fáscia lata",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 120
  },
  {
    "id": "gm-14-0096",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a relação de lateralidade do conteúdo da fossa poplítea",
    "a": "de medial para lateral:\n\nAVN- AViNi \n\nA. Poplítea\nV. Poplítea\nN. Isquiático (dividindo em N. Tibial e N. Fibular comum)\n\n\nOBS- N. Tibial é mais medial que o N. Fibular comum)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 121
  },
  {
    "id": "gm-14-0097",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é o tríceps sural?",
    "a": "Duas cabeças do M. Gastrocnêmio e o M. Sóleo\n\nResponsável pela flexão plantar \n\nInserção conjunta no calcâneo a partir do Tendão do Calcâneo\n\n\nOBS- O tendão do calcâneo recebe o Tendão do M. Plantar também",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 122
  },
  {
    "id": "gm-14-0098",
    "cat": 14,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a lesão do N. Fibular superficial?",
    "a": "Perda da capacidade de realizar a eversão do pé\n\n(M. Fibular curto e M. Fibular longo realizam)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "MMII- Eduardo Lôbo",
    "deckSlug": "mmii-eduardo-lobo-2e9efe70",
    "deckOrder": 123
  }
];
