window.IMPORTED_FLASHCARDS = [
  {
    "id": "91487fa0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que o N. Facial inerva na cabeça e pescoço?",
    "a": "Musculos da Mímica Facial\nM. Platisma( ramo cervical)\nM. Estapédio\nM. Estilo hióide\nVentre post do M. \nDigástrico\n\nTodas as glândulas exceto a Parótida\n\nsensibilidade gustativa de 2/3 anteriores da língua",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "9148cdc0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do Mm. Infra-hióides?",
    "a": "M.EsternoHióide\nM. Esternotireóide\nM.Tireohióide  (C1)\nM. Omohióide\n\nInervados pela alça cervical\n\nEXCETO O M. Tireohióide (inervado por C1- via hipoglosso)\n\nAlça Cervical: C1,C2 e C3\nporção sup: C1 e C2\nPorção inf: C2 e C3",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "9148f4d0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação dos Mm. Supra-hióides?",
    "a": "M. Geniohióide- C1 (fibras levados pelo Hipoglosso)\n\nM. Milohióide- N. para o músculo milo hióide\n (Ramo de V3)\n\nM. Digástrico- Ventre ant: N. Para o M. Milohióide (ramo de V3)\nVentre post: N. para o M. Digastrico (N. Facial)\n\nM. Estilohióide- N. Para o M. Estilohióide (N. Facial",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "91491be0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação da laringe?",
    "a": "N. Laringeo recorrente inerva os musculos intrínsecos (EXCETO O M. CRICOTIREOIDEO\n e sensitivamente 1/3 inferior\n\nN. Laringeo superior da os ramos Ext e Int\n\nRamo Int- porção sensitiva 2/3 superiores da laringe\n\nRamo Ext- M. Cricotireóideo \n\nOBS- Ramo ext  inerva parassimpaticamente a tireóide",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914942f0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do tronco tireocervical?",
    "a": "3  ramos\n\nA. Tireoidea inferior (origina a A. Cervical Ascendente)\nA. Supraescapular\nA. Cervical Transversa",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914942f1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do tronco costocervical?",
    "a": "A. Cervical Profunda \nA. Intercostal suprema",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "91496a00-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quantos trígonos existem no pescoço?",
    "a": "8 trígonos:\n-4 anteriores\n-3 laterais\n-1 posterior\n\n•Anteriores:\nTrígono Submentual\nTrígono Submandibular\nTrígono Muscular\nTrígono Carótico\n\n•Laterais:\nTrígono Omoclavicular\nFossa supraclavicular menor \nTrígono Occipital\n\n•Posterior:\nTrígono Suboccipital",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "91496a01-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono submandibular?",
    "a": "Limites:\n\nVentres do M. Digástrico e Margem Inf da Mandíbula\nassoalho-M. Milohióide\n\nConteúdo:\nGlândula submandibular\nN. Hipoglosso\n Vasos faciais\nN. Para o M. Milo hióide",
    "frontImage": null,
    "backImage": "9fbbf8e0-e7e0-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "91499110-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono submentual?",
    "a": "Limites:\n\ninf: Corpo do Osso Hióide \nLateral: Ventres anteriores do M. Digástrico esq e dir\nassoalho: M.Milohióide\n\nConteúdo:\npequenas veias que formam a Jugular anterior\nLinfonodos submentuais",
    "frontImage": null,
    "backImage": "8619f710-e9ee-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "91499111-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono carótico?",
    "a": "Limites:\n\nLateral- Margem anterior do M. ECM\nMedial- Ventra sup do M. Omo-hióide\nSuperior- Ventre Post do M. Digástrico\n\n\nConteúdo-\nA. Carótida Comum\nV. Jugular Interna\nN. Vago\nSaio Carotídeo\nCIRCUNDADOS PELA BAINHA CARÓTICA\n+N. Hipoglosso\n+N. Acessório\n+Faringe e laringe",
    "frontImage": null,
    "backImage": "49eb89b0-ea1c-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "9149b820-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono muscular?",
    "a": "Limites:\n\nSuperior- Ventre sup do\n M. Omohióide\nLateral-Borda anterior do \nM. ECM\nMedial- Plano mediano do pescoço \n\nConteúdo:\nM. Esternohióide\nM. Esternotireóide\nGlândula Tireoide\nGlândula ParaTireoide",
    "frontImage": null,
    "backImage": "f69b0250-ee3e-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "9149df30-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono omoclavicular?",
    "a": "Limites:\n\nInf- Clavícula\nSup- ventre inf do M. Omohióide\nMedial: Borda Post do \nM. ECM\n\n\nConteúdo:\n3ª Parte da A. Subclávia\nA. Supraescapular",
    "frontImage": null,
    "backImage": "97f8c4a0-50be-135c-a54c-991bc20cfc86.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "9149df31-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono Occipital?",
    "a": "Limites:\n\nLateral- Borda Anterior do M. Trapézio\nInf- Ventre Inf do\n M. Omohióide\nMedial- Borda Post do\n M. ECM\n\nConteúdo:\ntroncos do plexo braquial, N. Acessório, A. Cervical transversa",
    "frontImage": null,
    "backImage": "3fd85da0-f182-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914a0640-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono Suboccipital?",
    "a": "Limites:\n\nInf-M. Oblíquo Inf da Cabeça\nLateral-M. Oblíquo sup da Cabeça\nSuperior- M. Reto Post Maior da Cabeça\n\n\nConteúdo:\nA. Vertebral \nN. Suboccipital ( Ramo Post de C1- INERVA OS OBLÍQUOS E OS RETOS DA CABEÇA)",
    "frontImage": null,
    "backImage": "3eb71450-f3e1-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914a0641-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono de Guyon?",
    "a": "Limites:\n\nV. Jugular Interna\nTronco tireolinguofacial\nVentre Post do M.\n Digástrico\n\nConteúdo:\nBifurcação da Carótida e N. Hipoglosso",
    "frontImage": null,
    "backImage": "86095510-ffc2-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914a2d50-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo do trígono de farabeuf?",
    "a": "V. Jugular interna\nTronco Tireolinguofacial\nN. Hipoglosso\n\nConteúdo: Bifurcação da A. Carótida Comum\n\nImportância- Ponto de referência cirúrgica",
    "frontImage": null,
    "backImage": "b0854a20-ffb2-1241-b1fb-3b9fecf7e679.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914a2d51-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é o tronco tireolinguofacial?",
    "a": "Junção de veias que vão tributar juntas na jugular interna:\n\nV. Facial\nV. Lingual\nV. Tireoidea sup",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914a5460-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é e por que é perigoso tomar uma pancada no Ptério?",
    "a": "ptério é a área de encontro de 4 ossos:\nOsso Temporal\nOsso Frontal\nOsso Parietal\nOsso esfenóide\n\nPerigoso, porque é por onde passa ramo principal da A. Meningea Média, ramo frontal. O impacto pode causar uma lesão e, consequentemente, um hematoma Epidural/ Extradural",
    "frontImage": null,
    "backImage": "ed32a040-41f2-1313-822e-e5e73d524eff.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914aa280-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos supra hióideos? qual a ação?",
    "a": "são 4 músculos com a função de abaixar a mandíbula\n\nM. Digástrico(2 ventres)\nM. Estilo- Hióide\nM. Genio hióide\nM.Milo Hióide",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914aa281-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da tireóide? e a drenagem?",
    "a": "A. tireóidea sup (ramo da A. Carótida Ext)\n\nA. Tireóidea inf (ramo do Tronco tireocervical )\n\n\nDRENAGEM VENOSA:\nV. Tireóidea sup\nV. Tireóidea média\ndrenam para a V. Jugular interna\n\nV. tireóidea inf \ndrenam para a V. braquiocefálica",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914ac990-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação das paratireóides?",
    "a": "Aa. Tireóideas inferiores, apenas",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914ac991-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "A. Auricular posterior",
    "frontImage": "c97663a0-3f14-1347-9031-0556ba2a088d.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914af0a0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apresentada?",
    "a": "N. Laringeo recorrente esquerdo\n\npercorre o espaço traqueoesofágico",
    "frontImage": "248421e0-4ea3-1347-9031-0556ba2a088d.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914af0a1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos da A. Carótida externa?",
    "a": "anteriores: 4 ramos\n•A. Tireóidea sup\n•A. Lingual\n•A. Facial\n•A. Maxilar\n\nPosteriores: 2 ramos\nA. Occipital (sai no nível da A. Facial)\nA. Auricular post\n\nMedial: 1 ramo\nA. Faríngea ascendente\n\n\nSuperior: 1 ramo\nA. Temporal superficial \n(sai pra cima)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914b17b0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação dos músculos escalenos?",
    "a": "anterior- C5-C8\nmédio-C3-C7\nposterior-C5-C8",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914b3ec0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites e o conteúdo da fossa supraclavicular menor?",
    "a": "•Limites:\norigens do M. ECM (esternal e clavicular)+ Clavícula\n\n•Conteúdo:\nV. Jugular interna\n(local de acesso venoso central )",
    "frontImage": null,
    "backImage": "6f1f50f0-547c-135c-a54c-991bc20cfc86.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914b3ec1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação da V. Jugular externa e para onde ela drena?",
    "a": "V. Retromandibular\nV. Auricular posterior\n\ndrenam para a V. Subclávia\n(passam anteriormente ao ECM- ligadas a turgência jugular)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914b65d0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação e para onde V. Jugular anterior drena?",
    "a": "Vv. submandibulares superficiais e drena para a V. Jugular EXTERNA",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914b65d1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação da V. Jugular interna?",
    "a": "Seio sigmóide e Seio pretroso inferior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914b8ce0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo da bainha carótidea e sua lateralidade?",
    "a": "N. Vago posterior\nArtéria carótida medial\nV. Jugular interna lateral",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914b8ce1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os ramos do plexo cervical e qual a formação?",
    "a": "C1 - C4\n\nN. Cervical transverso\nN. Auricular Magno\nN. Occipital menor\nNn. Supraclaviculares",
    "frontImage": null,
    "backImage": "2b7e38d0-15df-1369-9bc8-a72790f82d72.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914bb3f0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação do glomo e seios carotídeos? e aórticos?",
    "a": "carotídeos:\nN. Glossofaríngeo\n\nAórtico:\nN. Vago",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914bb3f1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da laringe?",
    "a": "Aa. Laringeas superiores e inferiores ramos das Aa. Tireóideas superiores e inferiores\n\nDrenagem:\nV. Laringea superior- V. Jugular interna\n\nV. laringea inf- V. Tireóidea inf",
    "frontImage": null,
    "backImage": "d6108da0-6698-135c-a54c-991bc20cfc86.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914bdb00-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação da faringe?",
    "a": "Plexo faríngeo do N. Vago\npara todos os músculos, exceto;\n\n M. Estilofaríngeo- N. Glossofaríngeo",
    "frontImage": null,
    "backImage": "b6e3e190-66aa-135c-a54c-991bc20cfc86.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914bdb01-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação da sensibilidade da face? por onde esses nervos emergem?",
    "a": "Trigêmeo:\nV1- Fissura orbital sup\n(dorso do nariz até galea aponeurótica)\n\nV2- Forame redondo\n(maxilas e dentes maxilares)\n\nV3- Forame oval\n(dentes inferiores e mandíbula)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914c0210-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos da mastigação e sua inervação?",
    "a": "M. Temporal\nM. Masseter\nM. Pterigóideos (medial e lateral)\n\nTodos inervados por V3",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914c0211-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que é o trígono perigoso da face?",
    "a": "anastomose entre a V. Oftálmica superior (tributa no seio cavernoso) com a V. Angular.\n\nEssa anastomose pode levar bactérias para a circulação encefálica\n\nOBS- Há um vídeo no instagram da monitoria sobre o assunto (02/06/2025)",
    "frontImage": null,
    "backImage": "fded0e80-698f-135c-a54c-991bc20cfc86.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914c2920-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a inervação da glândula parótida?",
    "a": "N. Glossofaríngeo encaminha fibras nervosas pelo N. Auriculotemporal (que inerva sensitivamente)\n\nApesar de passar o plexo parotídeo do N. Facial, ele nn inerva\n\nOBS- Localizada anterior ao masseter, seu ducto fura o M. Bucinador e desemboca no 2º molar superior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914c2921-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "canal condilar (inconstante)\n\nconteúdo:\nVV. Emissárias \nA. Meníngea posterior",
    "frontImage": "95f6c700-6df2-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914c5030-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "forame estilomastóideo\n\nconteúdo: N. Facial",
    "frontImage": "d6bd7010-7007-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914c7740-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "forame jugular\n\n\nconteúdo: 9º,10° e 11º NC+ \nV. Jugular int + A. Meníngea posterior+ Seio petroso inf e Seio Sigmóide",
    "frontImage": "ab0bf4b0-7079-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914c9e50-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "fossa incisiva \n\nConteúdo;  N. Nasopalatino e Anastomose da  A. Palatina maior e A. Esfenopalatina \n\nOBS- as duas artérias irrigam o nariz",
    "frontImage": "618fffd0-71c2-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914c9e51-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "Forame Palatino menor\n\nVasos e N. Palatinos menores",
    "frontImage": "055b0d10-7242-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914cc560-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "Forame palatino maior\n\nConteúdo: Vasos e N. Palatino Maior",
    "frontImage": "d9f68c20-72a6-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914cc561-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "canal carotídeo\n\nconteúdo: A. Carótida Int",
    "frontImage": "bfbd61e0-72dc-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914cec70-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "forame lacerado\n\nConteúdo: \n\nN. Petroso maior // Sem conteúdo e tampado",
    "frontImage": "d36f9b30-7355-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914d1380-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "forame espinhoso\n\nConteúdo: Vasos Meníngeos médios + ramos meníngeos do trigêmeo (V3 principalmente)",
    "frontImage": "5f54ef40-73b7-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914d1381-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome das estruturas em azul?",
    "a": "Bregma (ponto de encontro das suturas parietais e sagital)\n\nLambda (ponto de encontro das suturas lambdóideas com a sagital)",
    "frontImage": "82fa8bc0-7412-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914d3a90-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o nome e qual o conteúdo?",
    "a": "Forame oval\n\nConteúdo: V3, A. Meníngea Acessória e N. Petroso menor",
    "frontImage": "13cef2d0-74ae-135c-a54c-991bc20cfc86.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914d3a91-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo da fissura orbital superior?",
    "a": "3º NC, 4º NC, V1, 6º NC, V. Oftálmica superior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914d61a0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo dos forames etmoidais anteriores e posteriores?",
    "a": "Vasos e Nervos com o mesmo nome",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914d61a1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do forame redondo?",
    "a": "V2",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914d88b0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do forame da mandíbula?",
    "a": "Vasos e N. Alveolar inferior",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914d88b1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo dos forames supraorbital, infraorbital e Mentual?",
    "a": "Vasos e Nervos do mesmo nome",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914dafc0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo da fissura orbital inferior ?",
    "a": "V. Oftálmica inf",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914dafc1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os círculos marcados?",
    "a": "verde- Astério\n(junção dos ossos occipital, parietal e temporal)\n\nVermelho- Ptério\n(junção dos ossos Frontal, esfenoide, parietal e temporal)",
    "frontImage": "ddeec480-f2af-135c-b0ea-9d9be027019e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914dd6d0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada? e qual sua inervação ?",
    "a": "Gânglio cervical superior- inerva simpaticamente a cabeça e pescoço",
    "frontImage": "e37d1db0-f3fa-135c-b0ea-9d9be027019e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914dd6d1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do Canal óptico?",
    "a": "A. Oftálmica\nN. Óptico (vasos centrais da retina dentro)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914dfde0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação e a inervação do N. Frênico?",
    "a": "C3,C4 e C5\n\nPassa anterior ao M. Escaleno anterior e anterior ao hilo pulmonar",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914dfde1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina toda a irrigação do couro cabeludo",
    "a": "5 artérias\n\nA. Carótida externa da 3 desses ramos :\n\nA. Temporal superficial\nA. Auricular post  \nA. Occipital\n\nA. Oftálmica dá 2 desses ramos:\n\nA. supraorbital\nA. Supratroclear",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914e24f0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do meato acústico interno?",
    "a": "N. Facial\nN. Vestibulococlear \nA. do Labirinto (Ramo da A. Basilar)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914e4c00-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "M. Estilo hióide\n\n(posterior em relação ao Ventre post do Digástrico)",
    "frontImage": "f65a40c0-144b-1369-9bc8-a72790f82d72.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914e7310-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "plexo parotídeo- 2 TRONCOS\n\n\nTronco Temporofacial\n\nverde- R. Temporal\nazul- R. Zigomático\n\nAmarelo- R. Bucal( FORMADO PELOS DOIS TRONCOS)\n\nTronco Cervicofacial\n\nVermelho- R. Marginal da \nmandíbula\nOBS- Ramo cervical é desse tronco, mas não está na figura",
    "frontImage": "1a707b50-1555-1369-9bc8-a72790f82d72.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914e7311-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a formação do seio cavernoso?",
    "a": "Veias oftálmicas (superior e inferior) \nV. Cerebral Média superficial\nSeio esfenoparietal\n\n\nOBS- O SEIO PETROSO INFERIOR CONECTA O CAVERNOSO À JUGULAR INTERNA",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914e9a20-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "vermelho- A. Facial (tortuosa e ramo da A. Carótida Externa)\n\nazul-V. Facial (continua como V. Angular e partipa da anastomose com a V. Supratroclear para o seio cavernoso)\n\nverde-Ducto parotídeo (anterior ao M. Masseter e fura o M. Bucinador no 2º molar superior)",
    "frontImage": "36018f10-3cce-136b-9780-b10ab99f5338.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914e9a21-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apresentadas?",
    "a": "verde- A. Alveolar inf\nazul-A. Maxilar\nbranco- A. Meníngea média",
    "frontImage": "8bac7fb0-fe4f-136e-96da-1bf036096190.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914ec130-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "Plexo parotídeo:\n\nTronco temporofacial\namarelo- N. Temporal \nazul- N. Zigomático\n\n\nverde- N. Bucal(formado pelos dois troncos)\n\nTronco Cervicofacial\n\n+ N. Marginal da mandíbula\nN. Cervical",
    "frontImage": "c2211840-637a-136f-96da-1bf036096190.jpg",
    "backImage": "798c3990-6477-136f-96da-1bf036096190.png",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914ec131-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "verde-R. Parietal\nazul- R. Frontal\nvermelho- A. Temporal superficial\namarelo-A. Facial transversa\n\nOBS- A. Facial transversa passa inferiormente ao arco zigomático",
    "frontImage": "7333e340-64e5-136f-96da-1bf036096190.jpg",
    "backImage": "99901b90-6601-136f-96da-1bf036096190.jpg",
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914ee840-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "N. Acessório \n\npassa posterior ao ECM e segue para o M. trapézio",
    "frontImage": "76cb75d0-27c0-137d-80fc-fb3bcbf6d10a.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914ee841-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "alfinete- N. Lingual",
    "frontImage": "9f1c2c20-8595-1384-92f3-23a0bfa74904.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914f0f50-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais as estruturas apontadas?",
    "a": "verde- A. Meníngea média\n\n\nazul-A. Maxilar (continua para dar mais ramos na fossa pterigopalatina)",
    "frontImage": "d33ab410-a843-1384-92f3-23a0bfa74904.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914f0f51-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "cite 10 ramos da A. Maxilar",
    "a": "A. Alveolar inf( forame da mandíbula)\nA. Meníngea Média (forame espinhoso) \nA. Meníngea Acessória (forame oval)\nA. Temporal profunda \nanterior \nA. Temporal profunda posterior\nA. Pterigóidea lateral\nA. Pterigóidea medial\nA. Massetérica\nA. Esfenopalatina (Forame esfenopalatina + Área de kiesselbach)\nA. Infraorbital (forame infraorbital)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914f3660-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "defina o anel linfático da faringe (de waldeyer)",
    "a": "De cima para baixo:\n\nTonsila faríngea\nTonsila Tubária (tuba auditiva)\nTonsila Palatina\nTonsila lingual",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914f3661-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos do palato? e qual a sua inervação?",
    "a": "M. Tensor do Véu palatino\n(V3)\n\nM. da Úvula\nM. Levantador do véu palatino\nM. Palatoglosso\nM. Palatofaríngeo\n(Plexo faríngeo do N. Vago)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914f5d70-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "diga os limites da faringe",
    "a": "nasofaringe: \nanterior:coanas \nposterior: parede posterior da faringe \nsup: osso esfenóide\ninf: palato mole\n\norofaringe: \nanterior: Raiz da língua \nsup: palato mole\nposterior: istmo das fauces \ninf: Ponta da epiglote\n\nlaringofaringe:\nsup: ponta da epiglote\ninf: borda inferior da cartilagem cricóide\nposterior:",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914f5d71-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos da faringe?",
    "a": "M. Constritor superior\nM. Constritor médio\nM. Constritor inferior \nM. Salpingofaríngeo\nM. Palatofaríngeo\n(plexo faríngeo do N. Vago)\n\nM. Estilofaríngeo\n(N. Glossofaríngeo)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914f8480-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "o que forma o esfíncter esofágico superior?",
    "a": "Espaço abaixo do M. Constritor inf da faringe\n(transição faringoesofágica)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914f8481-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "A. Laringea superior",
    "frontImage": "6f8bfb20-e539-13a8-9245-e1d016fcd73e.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914fab90-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os músculos externos da orelha e a sua inervação?",
    "a": "M.Auricular posterior\nM.Auricular superior\nM. Auricular anterior\n\ninervação;\nN. Auricular posterior e Ramo temporal do N. Facial",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914fab91-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual o conteúdo do forame magno?",
    "a": "Bulbo\nArtéria vertebral\nMeninges\nRaiz espinhal do N. Acessório",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914fd2a0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "V. Jugular externa",
    "frontImage": "24d029f0-e5d5-13af-af73-dba57ec0e66c.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914fd2a1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "Raiz medial do N. Mediano",
    "frontImage": "b371f6d0-e5f2-13af-af73-dba57ec0e66c.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "914ff9b0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites do trígono cervical anterior? quais os subtrígonos dentro?",
    "a": "posterior- Borda anterior do ECM\n\nanterior- Linha mediana do pescoço\n\nSuperior- margem inf da Mandíbula\n\n•Subtrígonos:\nTrígono Muscular\nTrígono Carotídeo\nTrígono Submentual\nTrígono Submandibular",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "915047d0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os limites do trígono cervical lateral? quais os subtrígonos dele?",
    "a": "anterior- Borda posterior do ECM\n\nposterior - borda anterior do M. Trapézio \n\nInf- Clavícula\n\n•subtrígonos:\nTrígono Omoclavicular\nTrígono Occipital",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "915047d1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a irrigação da parótida?",
    "a": "A. Facial transversa\n\n(ramo da A. Temporal superficial)",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "91506ee0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apontada?",
    "a": "V. Tireóidea Média",
    "frontImage": "bad10c50-c59b-13d0-8de0-5188da034ea2.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "91506ee1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual a estrutura apresentada?",
    "a": "Ramo cervical do N. Facial\n\n(indo para o platisma)",
    "frontImage": "9cd9df90-a7f1-13d6-8347-93585b352879.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "915095f0-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "quais os números 24,25,32,33?",
    "a": "24- N. Alveolar inf\n25- N. Lingual + N. Corda do tímpano\n32- M. Levantador do véu palatino\n33-M. Tensor do véu palatino\n\n(M. tensor do véu palatino é mais lateral que o M. levantador do véu palatino)",
    "frontImage": "76c7e280-f97d-13e8-ae36-6344e9df5f2f.jpg",
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  },
  {
    "id": "915095f1-5d3d-17fa-805b-7f38bac114e9",
    "cat": 8,
    "src": "ZIP",
    "b": "b-zip",
    "q": "qual vaso passa entre o tronco superior e médio do plexo braquial?",
    "a": "A. Dorsal da escápula",
    "frontImage": null,
    "backImage": null,
    "deckTitle": "CABEÇA E PESCOÇO- MONITORIA- Eduardo Lôbo"
  }
];
